// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assistance.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAssistanceRequest = `-- name: CreateAssistanceRequest :one
INSERT INTO assistance_requests (session_id, table_id, participant_id, type)
VALUES ($1, $2, $3, $4)
RETURNING id, session_id, table_id, participant_id, type, status, created_at, resolved_at
`

type CreateAssistanceRequestParams struct {
	SessionID     uuid.UUID      `json:"session_id"`
	TableID       int64          `json:"table_id"`
	ParticipantID pgtype.Int8    `json:"participant_id"`
	Type          AssistanceType `json:"type"`
}

func (q *Queries) CreateAssistanceRequest(ctx context.Context, arg CreateAssistanceRequestParams) (AssistanceRequest, error) {
	row := q.db.QueryRow(ctx, createAssistanceRequest,
		arg.SessionID,
		arg.TableID,
		arg.ParticipantID,
		arg.Type,
	)
	var i AssistanceRequest
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TableID,
		&i.ParticipantID,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getAssistanceRequestByID = `-- name: GetAssistanceRequestByID :one
SELECT id, session_id, table_id, participant_id, type, status, created_at, resolved_at FROM assistance_requests WHERE id = $1
`

func (q *Queries) GetAssistanceRequestByID(ctx context.Context, id int64) (AssistanceRequest, error) {
	row := q.db.QueryRow(ctx, getAssistanceRequestByID, id)
	var i AssistanceRequest
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TableID,
		&i.ParticipantID,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listActiveAssistanceForBranch = `-- name: ListActiveAssistanceForBranch :many
SELECT
  ar.id, ar.session_id, ar.table_id, ar.participant_id, ar.type, ar.status, ar.created_at, ar.resolved_at,
  t.identifier AS table_identifier,
  s.session_number
FROM assistance_requests ar
JOIN sessions s ON s.id = ar.session_id
JOIN tables t ON t.id = ar.table_id
WHERE t.branch_id = $1
  AND ar.status IN ('pending', 'acknowledged')
ORDER BY ar.created_at ASC
`

type ListActiveAssistanceForBranchRow struct {
	ID              int64              `json:"id"`
	SessionID       uuid.UUID          `json:"session_id"`
	TableID         int64              `json:"table_id"`
	ParticipantID   pgtype.Int8        `json:"participant_id"`
	Type            AssistanceType     `json:"type"`
	Status          AssistanceStatus   `json:"status"`
	CreatedAt       time.Time          `json:"created_at"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
	TableIdentifier string             `json:"table_identifier"`
	SessionNumber   string             `json:"session_number"`
}

func (q *Queries) ListActiveAssistanceForBranch(ctx context.Context, branchID int64) ([]ListActiveAssistanceForBranchRow, error) {
	rows, err := q.db.Query(ctx, listActiveAssistanceForBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAssistanceForBranchRow{}
	for rows.Next() {
		var i ListActiveAssistanceForBranchRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TableID,
			&i.ParticipantID,
			&i.Type,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.TableIdentifier,
			&i.SessionNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssistanceForSession = `-- name: ListAssistanceForSession :many
SELECT id, session_id, table_id, participant_id, type, status, created_at, resolved_at FROM assistance_requests
WHERE session_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAssistanceForSession(ctx context.Context, sessionID uuid.UUID) ([]AssistanceRequest, error) {
	rows, err := q.db.Query(ctx, listAssistanceForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssistanceRequest{}
	for rows.Next() {
		var i AssistanceRequest
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TableID,
			&i.ParticipantID,
			&i.Type,
			&i.Status,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssistanceStatus = `-- name: UpdateAssistanceStatus :one
UPDATE assistance_requests
SET status = $2,
    resolved_at = CASE WHEN $2::assistance_status = 'resolved' THEN NOW() ELSE resolved_at END
WHERE id = $1
RETURNING id, session_id, table_id, participant_id, type, status, created_at, resolved_at
`

type UpdateAssistanceStatusParams struct {
	ID     int64            `json:"id"`
	Status AssistanceStatus `json:"status"`
}

func (q *Queries) UpdateAssistanceStatus(ctx context.Context, arg UpdateAssistanceStatusParams) (AssistanceRequest, error) {
	row := q.db.QueryRow(ctx, updateAssistanceStatus, arg.ID, arg.Status)
	var i AssistanceRequest
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TableID,
		&i.ParticipantID,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const updateAssistanceStatusScoped = `-- name: UpdateAssistanceStatusScoped :one
UPDATE assistance_requests ar
SET status = $3,
    resolved_at = CASE WHEN $3::assistance_status = 'resolved' THEN NOW() ELSE ar.resolved_at END
FROM sessions s
WHERE ar.id = $1
  AND ar.session_id = s.id
  AND s.branch_id = $2
RETURNING ar.id, ar.session_id, ar.table_id, ar.participant_id, ar.type, ar.status, ar.created_at, ar.resolved_at
`

type UpdateAssistanceStatusScopedParams struct {
	ID       int64            `json:"id"`
	BranchID int64            `json:"branch_id"`
	Status   AssistanceStatus `json:"status"`
}

func (q *Queries) UpdateAssistanceStatusScoped(ctx context.Context, arg UpdateAssistanceStatusScopedParams) (AssistanceRequest, error) {
	row := q.db.QueryRow(ctx, updateAssistanceStatusScoped, arg.ID, arg.BranchID, arg.Status)
	var i AssistanceRequest
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TableID,
		&i.ParticipantID,
		&i.Type,
		&i.Status,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}
