// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO subscription_invoices (
    organization_id, subscription_id, invoice_number, status,
    amount, currency, due_date, notes, created_by_platform_user_id
) VALUES ($1, $2, $3, 'draft', $4::numeric, $5, $6, $7, $8)
RETURNING id, organization_id, subscription_id, invoice_number, status, amount, currency, issue_date, due_date, paid_at, notes, metadata_json, created_by_platform_user_id, created_at, updated_at
`

type CreateInvoiceParams struct {
	OrganizationID          int64              `json:"organization_id"`
	SubscriptionID          pgtype.Int8        `json:"subscription_id"`
	InvoiceNumber           string             `json:"invoice_number"`
	Column4                 pgtype.Numeric     `json:"column_4"`
	Currency                string             `json:"currency"`
	DueDate                 pgtype.Timestamptz `json:"due_date"`
	Notes                   string             `json:"notes"`
	CreatedByPlatformUserID pgtype.Int8        `json:"created_by_platform_user_id"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (SubscriptionInvoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.OrganizationID,
		arg.SubscriptionID,
		arg.InvoiceNumber,
		arg.Column4,
		arg.Currency,
		arg.DueDate,
		arg.Notes,
		arg.CreatedByPlatformUserID,
	)
	var i SubscriptionInvoice
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SubscriptionID,
		&i.InvoiceNumber,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.IssueDate,
		&i.DueDate,
		&i.PaidAt,
		&i.Notes,
		&i.MetadataJson,
		&i.CreatedByPlatformUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganizationSubscription = `-- name: CreateOrganizationSubscription :one
INSERT INTO organization_subscriptions (
    organization_id, plan_id, status, provider_type,
    started_at, trial_ends_at, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, plan_id, status, provider_type, provider_subscription_id, provider_customer_id, started_at, trial_ends_at, expires_at, renewed_at, cancelled_at, suspended_at, cancellation_reason, metadata_json, created_at, updated_at
`

type CreateOrganizationSubscriptionParams struct {
	OrganizationID int64              `json:"organization_id"`
	PlanID         int64              `json:"plan_id"`
	Status         string             `json:"status"`
	ProviderType   string             `json:"provider_type"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	TrialEndsAt    pgtype.Timestamptz `json:"trial_ends_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOrganizationSubscription(ctx context.Context, arg CreateOrganizationSubscriptionParams) (OrganizationSubscription, error) {
	row := q.db.QueryRow(ctx, createOrganizationSubscription,
		arg.OrganizationID,
		arg.PlanID,
		arg.Status,
		arg.ProviderType,
		arg.StartedAt,
		arg.TrialEndsAt,
		arg.ExpiresAt,
	)
	var i OrganizationSubscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.ProviderType,
		&i.ProviderSubscriptionID,
		&i.ProviderCustomerID,
		&i.StartedAt,
		&i.TrialEndsAt,
		&i.ExpiresAt,
		&i.RenewedAt,
		&i.CancelledAt,
		&i.SuspendedAt,
		&i.CancellationReason,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubscriptionPayment = `-- name: CreateSubscriptionPayment :one
INSERT INTO subscription_payments (
    organization_id, subscription_id, invoice_id, provider_type, method,
    amount, currency, reference_number, notes, received_at, recorded_by_platform_user_id
) VALUES ($1, $2, $3, $4, $5, $6::numeric, $7, $8, $9, $10, $11)
RETURNING id, organization_id, subscription_id, invoice_id, provider_type, method, amount, currency, reference_number, provider_payment_id, notes, received_at, recorded_by_platform_user_id, metadata_json, created_at
`

type CreateSubscriptionPaymentParams struct {
	OrganizationID           int64          `json:"organization_id"`
	SubscriptionID           pgtype.Int8    `json:"subscription_id"`
	InvoiceID                pgtype.Int8    `json:"invoice_id"`
	ProviderType             string         `json:"provider_type"`
	Method                   string         `json:"method"`
	Column6                  pgtype.Numeric `json:"column_6"`
	Currency                 string         `json:"currency"`
	ReferenceNumber          string         `json:"reference_number"`
	Notes                    string         `json:"notes"`
	ReceivedAt               time.Time      `json:"received_at"`
	RecordedByPlatformUserID pgtype.Int8    `json:"recorded_by_platform_user_id"`
}

func (q *Queries) CreateSubscriptionPayment(ctx context.Context, arg CreateSubscriptionPaymentParams) (SubscriptionPayment, error) {
	row := q.db.QueryRow(ctx, createSubscriptionPayment,
		arg.OrganizationID,
		arg.SubscriptionID,
		arg.InvoiceID,
		arg.ProviderType,
		arg.Method,
		arg.Column6,
		arg.Currency,
		arg.ReferenceNumber,
		arg.Notes,
		arg.ReceivedAt,
		arg.RecordedByPlatformUserID,
	)
	var i SubscriptionPayment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SubscriptionID,
		&i.InvoiceID,
		&i.ProviderType,
		&i.Method,
		&i.Amount,
		&i.Currency,
		&i.ReferenceNumber,
		&i.ProviderPaymentID,
		&i.Notes,
		&i.ReceivedAt,
		&i.RecordedByPlatformUserID,
		&i.MetadataJson,
		&i.CreatedAt,
	)
	return i, err
}

const getBillingProfile = `-- name: GetBillingProfile :one
SELECT organization_id, business_name, gst_number, tax_identifier, billing_email, billing_contact, billing_address, currency, metadata_json, created_at, updated_at FROM organization_billing_profiles WHERE organization_id = $1
`

func (q *Queries) GetBillingProfile(ctx context.Context, organizationID int64) (OrganizationBillingProfile, error) {
	row := q.db.QueryRow(ctx, getBillingProfile, organizationID)
	var i OrganizationBillingProfile
	err := row.Scan(
		&i.OrganizationID,
		&i.BusinessName,
		&i.GstNumber,
		&i.TaxIdentifier,
		&i.BillingEmail,
		&i.BillingContact,
		&i.BillingAddress,
		&i.Currency,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, organization_id, subscription_id, invoice_number, status, amount, currency, issue_date, due_date, paid_at, notes, metadata_json, created_by_platform_user_id, created_at, updated_at FROM subscription_invoices WHERE id = $1
`

func (q *Queries) GetInvoiceByID(ctx context.Context, id int64) (SubscriptionInvoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, id)
	var i SubscriptionInvoice
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SubscriptionID,
		&i.InvoiceNumber,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.IssueDate,
		&i.DueDate,
		&i.PaidAt,
		&i.Notes,
		&i.MetadataJson,
		&i.CreatedByPlatformUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByOrg = `-- name: GetSubscriptionByOrg :one

SELECT id, organization_id, plan_id, status, provider_type, provider_subscription_id, provider_customer_id, started_at, trial_ends_at, expires_at, renewed_at, cancelled_at, suspended_at, cancellation_reason, metadata_json, created_at, updated_at FROM organization_subscriptions WHERE organization_id = $1
`

// Org-level subscription lifecycle + billing foundation queries.
// Mutations are driven by BillingService; status is recorded/audited, not enforced.
func (q *Queries) GetSubscriptionByOrg(ctx context.Context, organizationID int64) (OrganizationSubscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByOrg, organizationID)
	var i OrganizationSubscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.ProviderType,
		&i.ProviderSubscriptionID,
		&i.ProviderCustomerID,
		&i.StartedAt,
		&i.TrialEndsAt,
		&i.ExpiresAt,
		&i.RenewedAt,
		&i.CancelledAt,
		&i.SuspendedAt,
		&i.CancellationReason,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvoicesByOrg = `-- name: ListInvoicesByOrg :many
SELECT id, organization_id, subscription_id, invoice_number, status, amount, currency, issue_date, due_date, paid_at, notes, metadata_json, created_by_platform_user_id, created_at, updated_at FROM subscription_invoices WHERE organization_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListInvoicesByOrg(ctx context.Context, organizationID int64) ([]SubscriptionInvoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionInvoice{}
	for rows.Next() {
		var i SubscriptionInvoice
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SubscriptionID,
			&i.InvoiceNumber,
			&i.Status,
			&i.Amount,
			&i.Currency,
			&i.IssueDate,
			&i.DueDate,
			&i.PaidAt,
			&i.Notes,
			&i.MetadataJson,
			&i.CreatedByPlatformUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByOrg = `-- name: ListPaymentsByOrg :many
SELECT id, organization_id, subscription_id, invoice_id, provider_type, method, amount, currency, reference_number, provider_payment_id, notes, received_at, recorded_by_platform_user_id, metadata_json, created_at FROM subscription_payments WHERE organization_id = $1 ORDER BY received_at DESC
`

func (q *Queries) ListPaymentsByOrg(ctx context.Context, organizationID int64) ([]SubscriptionPayment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionPayment{}
	for rows.Next() {
		var i SubscriptionPayment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.SubscriptionID,
			&i.InvoiceID,
			&i.ProviderType,
			&i.Method,
			&i.Amount,
			&i.Currency,
			&i.ReferenceNumber,
			&i.ProviderPaymentID,
			&i.Notes,
			&i.ReceivedAt,
			&i.RecordedByPlatformUserID,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextInvoiceNumber = `-- name: NextInvoiceNumber :one
SELECT nextval('billing_invoice_number_seq')::bigint AS seq
`

func (q *Queries) NextInvoiceNumber(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextInvoiceNumber)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :one
UPDATE subscription_invoices
SET status     = $2,
    issue_date = $3,
    paid_at    = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, organization_id, subscription_id, invoice_number, status, amount, currency, issue_date, due_date, paid_at, notes, metadata_json, created_by_platform_user_id, created_at, updated_at
`

type UpdateInvoiceStatusParams struct {
	ID        int64              `json:"id"`
	Status    string             `json:"status"`
	IssueDate pgtype.Timestamptz `json:"issue_date"`
	PaidAt    pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (SubscriptionInvoice, error) {
	row := q.db.QueryRow(ctx, updateInvoiceStatus,
		arg.ID,
		arg.Status,
		arg.IssueDate,
		arg.PaidAt,
	)
	var i SubscriptionInvoice
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.SubscriptionID,
		&i.InvoiceNumber,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.IssueDate,
		&i.DueDate,
		&i.PaidAt,
		&i.Notes,
		&i.MetadataJson,
		&i.CreatedByPlatformUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationSubscription = `-- name: UpdateOrganizationSubscription :one
UPDATE organization_subscriptions
SET plan_id                  = $2,
    status                   = $3,
    provider_type            = $4,
    provider_subscription_id = $5,
    provider_customer_id     = $6,
    started_at               = $7,
    trial_ends_at            = $8,
    expires_at               = $9,
    renewed_at               = $10,
    cancelled_at             = $11,
    suspended_at             = $12,
    cancellation_reason      = $13,
    updated_at               = NOW()
WHERE organization_id = $1
RETURNING id, organization_id, plan_id, status, provider_type, provider_subscription_id, provider_customer_id, started_at, trial_ends_at, expires_at, renewed_at, cancelled_at, suspended_at, cancellation_reason, metadata_json, created_at, updated_at
`

type UpdateOrganizationSubscriptionParams struct {
	OrganizationID         int64              `json:"organization_id"`
	PlanID                 int64              `json:"plan_id"`
	Status                 string             `json:"status"`
	ProviderType           string             `json:"provider_type"`
	ProviderSubscriptionID string             `json:"provider_subscription_id"`
	ProviderCustomerID     string             `json:"provider_customer_id"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
	TrialEndsAt            pgtype.Timestamptz `json:"trial_ends_at"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	RenewedAt              pgtype.Timestamptz `json:"renewed_at"`
	CancelledAt            pgtype.Timestamptz `json:"cancelled_at"`
	SuspendedAt            pgtype.Timestamptz `json:"suspended_at"`
	CancellationReason     string             `json:"cancellation_reason"`
}

func (q *Queries) UpdateOrganizationSubscription(ctx context.Context, arg UpdateOrganizationSubscriptionParams) (OrganizationSubscription, error) {
	row := q.db.QueryRow(ctx, updateOrganizationSubscription,
		arg.OrganizationID,
		arg.PlanID,
		arg.Status,
		arg.ProviderType,
		arg.ProviderSubscriptionID,
		arg.ProviderCustomerID,
		arg.StartedAt,
		arg.TrialEndsAt,
		arg.ExpiresAt,
		arg.RenewedAt,
		arg.CancelledAt,
		arg.SuspendedAt,
		arg.CancellationReason,
	)
	var i OrganizationSubscription
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.ProviderType,
		&i.ProviderSubscriptionID,
		&i.ProviderCustomerID,
		&i.StartedAt,
		&i.TrialEndsAt,
		&i.ExpiresAt,
		&i.RenewedAt,
		&i.CancelledAt,
		&i.SuspendedAt,
		&i.CancellationReason,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBillingProfile = `-- name: UpsertBillingProfile :one
INSERT INTO organization_billing_profiles (
    organization_id, business_name, gst_number, tax_identifier,
    billing_email, billing_contact, billing_address, currency
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (organization_id) DO UPDATE SET
    business_name   = EXCLUDED.business_name,
    gst_number      = EXCLUDED.gst_number,
    tax_identifier  = EXCLUDED.tax_identifier,
    billing_email   = EXCLUDED.billing_email,
    billing_contact = EXCLUDED.billing_contact,
    billing_address = EXCLUDED.billing_address,
    currency        = EXCLUDED.currency,
    updated_at      = NOW()
RETURNING organization_id, business_name, gst_number, tax_identifier, billing_email, billing_contact, billing_address, currency, metadata_json, created_at, updated_at
`

type UpsertBillingProfileParams struct {
	OrganizationID int64  `json:"organization_id"`
	BusinessName   string `json:"business_name"`
	GstNumber      string `json:"gst_number"`
	TaxIdentifier  string `json:"tax_identifier"`
	BillingEmail   string `json:"billing_email"`
	BillingContact string `json:"billing_contact"`
	BillingAddress string `json:"billing_address"`
	Currency       string `json:"currency"`
}

func (q *Queries) UpsertBillingProfile(ctx context.Context, arg UpsertBillingProfileParams) (OrganizationBillingProfile, error) {
	row := q.db.QueryRow(ctx, upsertBillingProfile,
		arg.OrganizationID,
		arg.BusinessName,
		arg.GstNumber,
		arg.TaxIdentifier,
		arg.BillingEmail,
		arg.BillingContact,
		arg.BillingAddress,
		arg.Currency,
	)
	var i OrganizationBillingProfile
	err := row.Scan(
		&i.OrganizationID,
		&i.BusinessName,
		&i.GstNumber,
		&i.TaxIdentifier,
		&i.BillingEmail,
		&i.BillingContact,
		&i.BillingAddress,
		&i.Currency,
		&i.MetadataJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
