// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: carts.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCartItem = `-- name: AddCartItem :one
INSERT INTO cart_items (cart_id, menu_item_id, quantity, selected_modifiers_json, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, cart_id, menu_item_id, quantity, selected_modifiers_json, note
`

type AddCartItemParams struct {
	CartID                int64           `json:"cart_id"`
	MenuItemID            int64           `json:"menu_item_id"`
	Quantity              int16           `json:"quantity"`
	SelectedModifiersJson json.RawMessage `json:"selected_modifiers_json"`
	Note                  string          `json:"note"`
}

func (q *Queries) AddCartItem(ctx context.Context, arg AddCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, addCartItem,
		arg.CartID,
		arg.MenuItemID,
		arg.Quantity,
		arg.SelectedModifiersJson,
		arg.Note,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.MenuItemID,
		&i.Quantity,
		&i.SelectedModifiersJson,
		&i.Note,
	)
	return i, err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart_items WHERE cart_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, cartID int64) error {
	_, err := q.db.Exec(ctx, clearCart, cartID)
	return err
}

const getCartByID = `-- name: GetCartByID :one
SELECT id, session_id, participant_id FROM carts WHERE id = $1
`

func (q *Queries) GetCartByID(ctx context.Context, id int64) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByID, id)
	var i Cart
	err := row.Scan(&i.ID, &i.SessionID, &i.ParticipantID)
	return i, err
}

const getCartBySessionAndParticipant = `-- name: GetCartBySessionAndParticipant :one
SELECT id, session_id, participant_id FROM carts WHERE session_id = $1 AND participant_id = $2
`

type GetCartBySessionAndParticipantParams struct {
	SessionID     uuid.UUID   `json:"session_id"`
	ParticipantID pgtype.Int8 `json:"participant_id"`
}

func (q *Queries) GetCartBySessionAndParticipant(ctx context.Context, arg GetCartBySessionAndParticipantParams) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartBySessionAndParticipant, arg.SessionID, arg.ParticipantID)
	var i Cart
	err := row.Scan(&i.ID, &i.SessionID, &i.ParticipantID)
	return i, err
}

const getCartItem = `-- name: GetCartItem :one
SELECT id, cart_id, menu_item_id, quantity, selected_modifiers_json, note FROM cart_items WHERE id = $1
`

func (q *Queries) GetCartItem(ctx context.Context, id int64) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartItem, id)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.MenuItemID,
		&i.Quantity,
		&i.SelectedModifiersJson,
		&i.Note,
	)
	return i, err
}

const getOrCreateCart = `-- name: GetOrCreateCart :one
INSERT INTO carts (session_id, participant_id)
VALUES ($1, $2)
ON CONFLICT (session_id, participant_id) DO UPDATE SET session_id = EXCLUDED.session_id
RETURNING id, session_id, participant_id
`

type GetOrCreateCartParams struct {
	SessionID     uuid.UUID   `json:"session_id"`
	ParticipantID pgtype.Int8 `json:"participant_id"`
}

func (q *Queries) GetOrCreateCart(ctx context.Context, arg GetOrCreateCartParams) (Cart, error) {
	row := q.db.QueryRow(ctx, getOrCreateCart, arg.SessionID, arg.ParticipantID)
	var i Cart
	err := row.Scan(&i.ID, &i.SessionID, &i.ParticipantID)
	return i, err
}

const getOrCreateSessionCart = `-- name: GetOrCreateSessionCart :one
INSERT INTO carts (session_id, participant_id)
VALUES ($1, NULL)
ON CONFLICT (session_id) WHERE participant_id IS NULL
DO UPDATE SET session_id = EXCLUDED.session_id
RETURNING id, session_id, participant_id
`

func (q *Queries) GetOrCreateSessionCart(ctx context.Context, sessionID uuid.UUID) (Cart, error) {
	row := q.db.QueryRow(ctx, getOrCreateSessionCart, sessionID)
	var i Cart
	err := row.Scan(&i.ID, &i.SessionID, &i.ParticipantID)
	return i, err
}

const listCartItems = `-- name: ListCartItems :many
SELECT
    ci.id,
    ci.cart_id,
    ci.menu_item_id,
    ci.quantity,
    ci.selected_modifiers_json,
    ci.note,
    mi.name AS item_name,
    mi.price AS item_price,
    mi.image_url,
    mi.is_available
FROM cart_items ci
JOIN menu_items mi ON mi.id = ci.menu_item_id
WHERE ci.cart_id = $1
ORDER BY ci.id ASC
`

type ListCartItemsRow struct {
	ID                    int64           `json:"id"`
	CartID                int64           `json:"cart_id"`
	MenuItemID            int64           `json:"menu_item_id"`
	Quantity              int16           `json:"quantity"`
	SelectedModifiersJson json.RawMessage `json:"selected_modifiers_json"`
	Note                  string          `json:"note"`
	ItemName              string          `json:"item_name"`
	ItemPrice             pgtype.Numeric  `json:"item_price"`
	ImageUrl              pgtype.Text     `json:"image_url"`
	IsAvailable           bool            `json:"is_available"`
}

func (q *Queries) ListCartItems(ctx context.Context, cartID int64) ([]ListCartItemsRow, error) {
	rows, err := q.db.Query(ctx, listCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCartItemsRow{}
	for rows.Next() {
		var i ListCartItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.MenuItemID,
			&i.Quantity,
			&i.SelectedModifiersJson,
			&i.Note,
			&i.ItemName,
			&i.ItemPrice,
			&i.ImageUrl,
			&i.IsAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCartItem = `-- name: RemoveCartItem :exec
DELETE FROM cart_items WHERE id = $1 AND cart_id = $2
`

type RemoveCartItemParams struct {
	ID     int64 `json:"id"`
	CartID int64 `json:"cart_id"`
}

func (q *Queries) RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error {
	_, err := q.db.Exec(ctx, removeCartItem, arg.ID, arg.CartID)
	return err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
UPDATE cart_items SET quantity = $2 WHERE id = $1
RETURNING id, cart_id, menu_item_id, quantity, selected_modifiers_json, note
`

type UpdateCartItemQuantityParams struct {
	ID       int64 `json:"id"`
	Quantity int16 `json:"quantity"`
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItemQuantity, arg.ID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.MenuItemID,
		&i.Quantity,
		&i.SelectedModifiersJson,
		&i.Note,
	)
	return i, err
}
