// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collateral.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBranchCollateral = `-- name: GetBranchCollateral :one
SELECT branch_id, config_json, updated_by_platform_user_id, created_at, updated_at FROM branch_collateral WHERE branch_id = $1
`

func (q *Queries) GetBranchCollateral(ctx context.Context, branchID int64) (BranchCollateral, error) {
	row := q.db.QueryRow(ctx, getBranchCollateral, branchID)
	var i BranchCollateral
	err := row.Scan(
		&i.BranchID,
		&i.ConfigJson,
		&i.UpdatedByPlatformUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBranchCollateral = `-- name: UpsertBranchCollateral :one
INSERT INTO branch_collateral (branch_id, config_json, updated_by_platform_user_id)
VALUES ($1, $2, $3)
ON CONFLICT (branch_id)
DO UPDATE SET config_json = EXCLUDED.config_json,
              updated_by_platform_user_id = EXCLUDED.updated_by_platform_user_id, updated_at = NOW()
RETURNING branch_id, config_json, updated_by_platform_user_id, created_at, updated_at
`

type UpsertBranchCollateralParams struct {
	BranchID                int64           `json:"branch_id"`
	ConfigJson              json.RawMessage `json:"config_json"`
	UpdatedByPlatformUserID pgtype.Int8     `json:"updated_by_platform_user_id"`
}

func (q *Queries) UpsertBranchCollateral(ctx context.Context, arg UpsertBranchCollateralParams) (BranchCollateral, error) {
	row := q.db.QueryRow(ctx, upsertBranchCollateral, arg.BranchID, arg.ConfigJson, arg.UpdatedByPlatformUserID)
	var i BranchCollateral
	err := row.Scan(
		&i.BranchID,
		&i.ConfigJson,
		&i.UpdatedByPlatformUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
