// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCustomer = `-- name: DeleteCustomer :exec
DELETE FROM customers WHERE id = $1 AND restaurant_id = $2
`

type DeleteCustomerParams struct {
	ID           int64 `json:"id"`
	RestaurantID int64 `json:"restaurant_id"`
}

func (q *Queries) DeleteCustomer(ctx context.Context, arg DeleteCustomerParams) error {
	_, err := q.db.Exec(ctx, deleteCustomer, arg.ID, arg.RestaurantID)
	return err
}

const getCustomerByPhone = `-- name: GetCustomerByPhone :one
SELECT id, restaurant_id, phone_e164, display_name, opted_in, opted_in_at, last_seen_at, visit_count, created_at FROM customers WHERE restaurant_id = $1 AND phone_e164 = $2
`

type GetCustomerByPhoneParams struct {
	RestaurantID int64  `json:"restaurant_id"`
	PhoneE164    string `json:"phone_e164"`
}

func (q *Queries) GetCustomerByPhone(ctx context.Context, arg GetCustomerByPhoneParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByPhone, arg.RestaurantID, arg.PhoneE164)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.PhoneE164,
		&i.DisplayName,
		&i.OptedIn,
		&i.OptedInAt,
		&i.LastSeenAt,
		&i.VisitCount,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerSessionHistory = `-- name: GetCustomerSessionHistory :many
SELECT
    s.id AS session_id,
    s.created_at,
    s.closed_at,
    t.identifier AS table_identifier,
    COALESCE(SUM(o.total_amount), 0::numeric) AS total_spent
FROM sessions s
JOIN tables t ON t.id = s.table_id
LEFT JOIN orders o ON o.session_id = s.id AND o.status != 'cancelled'
WHERE s.customer_id = $1
GROUP BY s.id, s.created_at, s.closed_at, t.identifier
ORDER BY s.created_at DESC
LIMIT 20
`

type GetCustomerSessionHistoryRow struct {
	SessionID       uuid.UUID          `json:"session_id"`
	CreatedAt       time.Time          `json:"created_at"`
	ClosedAt        pgtype.Timestamptz `json:"closed_at"`
	TableIdentifier string             `json:"table_identifier"`
	TotalSpent      interface{}        `json:"total_spent"`
}

func (q *Queries) GetCustomerSessionHistory(ctx context.Context, customerID pgtype.Int8) ([]GetCustomerSessionHistoryRow, error) {
	rows, err := q.db.Query(ctx, getCustomerSessionHistory, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCustomerSessionHistoryRow{}
	for rows.Next() {
		var i GetCustomerSessionHistoryRow
		if err := rows.Scan(
			&i.SessionID,
			&i.CreatedAt,
			&i.ClosedAt,
			&i.TableIdentifier,
			&i.TotalSpent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkSessionToCustomer = `-- name: LinkSessionToCustomer :exec
UPDATE sessions SET customer_id = $2 WHERE id = $1
`

type LinkSessionToCustomerParams struct {
	ID         uuid.UUID   `json:"id"`
	CustomerID pgtype.Int8 `json:"customer_id"`
}

func (q *Queries) LinkSessionToCustomer(ctx context.Context, arg LinkSessionToCustomerParams) error {
	_, err := q.db.Exec(ctx, linkSessionToCustomer, arg.ID, arg.CustomerID)
	return err
}

const searchCustomersByPhone = `-- name: SearchCustomersByPhone :many
SELECT id, restaurant_id, phone_e164, display_name, opted_in, opted_in_at, last_seen_at, visit_count, created_at FROM customers
WHERE restaurant_id = $1 AND phone_e164 LIKE $2 || '%'
ORDER BY last_seen_at DESC
LIMIT 20
`

type SearchCustomersByPhoneParams struct {
	RestaurantID int64       `json:"restaurant_id"`
	Column2      pgtype.Text `json:"column_2"`
}

func (q *Queries) SearchCustomersByPhone(ctx context.Context, arg SearchCustomersByPhoneParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, searchCustomersByPhone, arg.RestaurantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.PhoneE164,
			&i.DisplayName,
			&i.OptedIn,
			&i.OptedInAt,
			&i.LastSeenAt,
			&i.VisitCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCustomer = `-- name: UpsertCustomer :one
INSERT INTO customers (restaurant_id, phone_e164, display_name, opted_in, opted_in_at, last_seen_at)
VALUES ($1, $2, $3, TRUE, NOW(), NOW())
ON CONFLICT (restaurant_id, phone_e164) DO UPDATE
SET
    display_name = CASE WHEN EXCLUDED.display_name != '' THEN EXCLUDED.display_name ELSE customers.display_name END,
    last_seen_at = NOW(),
    visit_count  = customers.visit_count + 1,
    opted_in     = TRUE,
    opted_in_at  = COALESCE(customers.opted_in_at, NOW())
RETURNING id, restaurant_id, phone_e164, display_name, opted_in, opted_in_at, last_seen_at, visit_count, created_at
`

type UpsertCustomerParams struct {
	RestaurantID int64  `json:"restaurant_id"`
	PhoneE164    string `json:"phone_e164"`
	DisplayName  string `json:"display_name"`
}

func (q *Queries) UpsertCustomer(ctx context.Context, arg UpsertCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, upsertCustomer, arg.RestaurantID, arg.PhoneE164, arg.DisplayName)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.PhoneE164,
		&i.DisplayName,
		&i.OptedIn,
		&i.OptedInAt,
		&i.LastSeenAt,
		&i.VisitCount,
		&i.CreatedAt,
	)
	return i, err
}
