// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enforcement_observability.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listFlagCatalogKeys = `-- name: ListFlagCatalogKeys :many
SELECT key, name, default_enabled FROM platform_feature_flags ORDER BY key
`

type ListFlagCatalogKeysRow struct {
	Key            string `json:"key"`
	Name           string `json:"name"`
	DefaultEnabled bool   `json:"default_enabled"`
}

func (q *Queries) ListFlagCatalogKeys(ctx context.Context) ([]ListFlagCatalogKeysRow, error) {
	rows, err := q.db.Query(ctx, listFlagCatalogKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFlagCatalogKeysRow{}
	for rows.Next() {
		var i ListFlagCatalogKeysRow
		if err := rows.Scan(&i.Key, &i.Name, &i.DefaultEnabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFlagOverrideCounts = `-- name: ListFlagOverrideCounts :many
SELECT flag_key, 'global'::text AS scope, COUNT(*)::bigint AS n FROM platform_flag_global_overrides GROUP BY flag_key
UNION ALL
SELECT flag_key, 'organization'::text AS scope, COUNT(*)::bigint AS n FROM platform_flag_organization_overrides GROUP BY flag_key
UNION ALL
SELECT flag_key, 'branch'::text AS scope, COUNT(*)::bigint AS n FROM platform_flag_branch_overrides GROUP BY flag_key
`

type ListFlagOverrideCountsRow struct {
	FlagKey string `json:"flag_key"`
	Scope   string `json:"scope"`
	N       int64  `json:"n"`
}

func (q *Queries) ListFlagOverrideCounts(ctx context.Context) ([]ListFlagOverrideCountsRow, error) {
	rows, err := q.db.Query(ctx, listFlagOverrideCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFlagOverrideCountsRow{}
	for rows.Next() {
		var i ListFlagOverrideCountsRow
		if err := rows.Scan(&i.FlagKey, &i.Scope, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgResourceCounts = `-- name: ListOrgResourceCounts :many
SELECT o.id AS organization_id, o.code, o.name,
  (SELECT COUNT(*) FROM branches b WHERE b.organization_id = o.id)::bigint AS branch_count,
  (SELECT COUNT(*) FROM staff s JOIN branches b ON b.id = s.branch_id
     WHERE b.organization_id = o.id AND s.is_active)::bigint AS staff_count,
  COALESCE((
    SELECT MAX(c) FROM (
      SELECT COUNT(*) AS c FROM tables t JOIN branches b ON b.id = t.branch_id
      WHERE b.organization_id = o.id GROUP BY t.branch_id
    ) per_branch
  ), 0)::bigint AS max_tables_per_branch
FROM organizations o
ORDER BY o.name
`

type ListOrgResourceCountsRow struct {
	OrganizationID     int64  `json:"organization_id"`
	Code               string `json:"code"`
	Name               string `json:"name"`
	BranchCount        int64  `json:"branch_count"`
	StaffCount         int64  `json:"staff_count"`
	MaxTablesPerBranch int64  `json:"max_tables_per_branch"`
}

func (q *Queries) ListOrgResourceCounts(ctx context.Context) ([]ListOrgResourceCountsRow, error) {
	rows, err := q.db.Query(ctx, listOrgResourceCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgResourceCountsRow{}
	for rows.Next() {
		var i ListOrgResourceCountsRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.Code,
			&i.Name,
			&i.BranchCount,
			&i.StaffCount,
			&i.MaxTablesPerBranch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsForObservability = `-- name: ListSubscriptionsForObservability :many

SELECT os.organization_id, o.code AS org_code, o.name AS org_name, os.status,
       sp.tier AS plan_tier, os.trial_ends_at, os.expires_at
FROM organization_subscriptions os
JOIN organizations o ON o.id = os.organization_id
JOIN subscription_plans sp ON sp.id = os.plan_id
ORDER BY o.name
`

type ListSubscriptionsForObservabilityRow struct {
	OrganizationID int64              `json:"organization_id"`
	OrgCode        string             `json:"org_code"`
	OrgName        string             `json:"org_name"`
	Status         string             `json:"status"`
	PlanTier       PlanTier           `json:"plan_tier"`
	TrialEndsAt    pgtype.Timestamptz `json:"trial_ends_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

// Enforcement observability: read-only aggregates that surface where enforcement
// WOULD bite if it were turned on. Observe-only — nothing here gates any path.
func (q *Queries) ListSubscriptionsForObservability(ctx context.Context) ([]ListSubscriptionsForObservabilityRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsForObservability)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscriptionsForObservabilityRow{}
	for rows.Next() {
		var i ListSubscriptionsForObservabilityRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.OrgCode,
			&i.OrgName,
			&i.Status,
			&i.PlanTier,
			&i.TrialEndsAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
