// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entitlements.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO subscription_plans (name, tier, price_monthly, features_json)
VALUES ($1, $2::plan_tier, $3::numeric, $4::jsonb)
RETURNING id, name, tier, price_monthly, features_json, created_at
`

type CreatePlanParams struct {
	Name    string          `json:"name"`
	Column2 PlanTier        `json:"column_2"`
	Column3 pgtype.Numeric  `json:"column_3"`
	Column4 json.RawMessage `json:"column_4"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.Name,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tier,
		&i.PriceMonthly,
		&i.FeaturesJson,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrganizationEntitlementOverride = `-- name: DeleteOrganizationEntitlementOverride :exec
DELETE FROM organization_entitlement_overrides
WHERE organization_id = $1 AND entitlement_key = $2
`

type DeleteOrganizationEntitlementOverrideParams struct {
	OrganizationID int64  `json:"organization_id"`
	EntitlementKey string `json:"entitlement_key"`
}

func (q *Queries) DeleteOrganizationEntitlementOverride(ctx context.Context, arg DeleteOrganizationEntitlementOverrideParams) error {
	_, err := q.db.Exec(ctx, deleteOrganizationEntitlementOverride, arg.OrganizationID, arg.EntitlementKey)
	return err
}

const deletePlanEntitlements = `-- name: DeletePlanEntitlements :exec
DELETE FROM plan_entitlements WHERE plan_id = $1
`

func (q *Queries) DeletePlanEntitlements(ctx context.Context, planID int64) error {
	_, err := q.db.Exec(ctx, deletePlanEntitlements, planID)
	return err
}

const getEntitlement = `-- name: GetEntitlement :one
SELECT key, kind, description, created_at FROM entitlements WHERE key = $1
`

func (q *Queries) GetEntitlement(ctx context.Context, key string) (Entitlement, error) {
	row := q.db.QueryRow(ctx, getEntitlement, key)
	var i Entitlement
	err := row.Scan(
		&i.Key,
		&i.Kind,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationPlanAssignment = `-- name: GetOrganizationPlanAssignment :one
SELECT organization_id, plan_id, status, assigned_by_platform_user_id, created_at, updated_at FROM organization_plan_assignments WHERE organization_id = $1
`

func (q *Queries) GetOrganizationPlanAssignment(ctx context.Context, organizationID int64) (OrganizationPlanAssignment, error) {
	row := q.db.QueryRow(ctx, getOrganizationPlanAssignment, organizationID)
	var i OrganizationPlanAssignment
	err := row.Scan(
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.AssignedByPlatformUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, name, tier, price_monthly, features_json, created_at FROM subscription_plans WHERE id = $1
`

func (q *Queries) GetPlanByID(ctx context.Context, id int64) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tier,
		&i.PriceMonthly,
		&i.FeaturesJson,
		&i.CreatedAt,
	)
	return i, err
}

const listEntitlementCatalog = `-- name: ListEntitlementCatalog :many
SELECT key, kind, description, created_at FROM entitlements ORDER BY kind, key
`

func (q *Queries) ListEntitlementCatalog(ctx context.Context) ([]Entitlement, error) {
	rows, err := q.db.Query(ctx, listEntitlementCatalog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entitlement{}
	for rows.Next() {
		var i Entitlement
		if err := rows.Scan(
			&i.Key,
			&i.Kind,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationEntitlementOverrides = `-- name: ListOrganizationEntitlementOverrides :many
SELECT organization_id, entitlement_key, enabled, limit_value, reason, created_by_platform_user_id, created_at, updated_at FROM organization_entitlement_overrides WHERE organization_id = $1 ORDER BY entitlement_key
`

func (q *Queries) ListOrganizationEntitlementOverrides(ctx context.Context, organizationID int64) ([]OrganizationEntitlementOverride, error) {
	rows, err := q.db.Query(ctx, listOrganizationEntitlementOverrides, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationEntitlementOverride{}
	for rows.Next() {
		var i OrganizationEntitlementOverride
		if err := rows.Scan(
			&i.OrganizationID,
			&i.EntitlementKey,
			&i.Enabled,
			&i.LimitValue,
			&i.Reason,
			&i.CreatedByPlatformUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanEntitlements = `-- name: ListPlanEntitlements :many
SELECT plan_id, entitlement_key, enabled, limit_value, created_at, updated_at FROM plan_entitlements WHERE plan_id = $1 ORDER BY entitlement_key
`

func (q *Queries) ListPlanEntitlements(ctx context.Context, planID int64) ([]PlanEntitlement, error) {
	rows, err := q.db.Query(ctx, listPlanEntitlements, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanEntitlement{}
	for rows.Next() {
		var i PlanEntitlement
		if err := rows.Scan(
			&i.PlanID,
			&i.EntitlementKey,
			&i.Enabled,
			&i.LimitValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE subscription_plans
SET name = $2, price_monthly = $3::numeric, features_json = $4::jsonb
WHERE id = $1
RETURNING id, name, tier, price_monthly, features_json, created_at
`

type UpdatePlanParams struct {
	ID      int64           `json:"id"`
	Name    string          `json:"name"`
	Column3 pgtype.Numeric  `json:"column_3"`
	Column4 json.RawMessage `json:"column_4"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.ID,
		arg.Name,
		arg.Column3,
		arg.Column4,
	)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tier,
		&i.PriceMonthly,
		&i.FeaturesJson,
		&i.CreatedAt,
	)
	return i, err
}

const upsertOrganizationEntitlementOverride = `-- name: UpsertOrganizationEntitlementOverride :one
INSERT INTO organization_entitlement_overrides
    (organization_id, entitlement_key, enabled, limit_value, reason, created_by_platform_user_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (organization_id, entitlement_key)
DO UPDATE SET enabled = EXCLUDED.enabled, limit_value = EXCLUDED.limit_value,
              reason = EXCLUDED.reason, created_by_platform_user_id = EXCLUDED.created_by_platform_user_id,
              updated_at = NOW()
RETURNING organization_id, entitlement_key, enabled, limit_value, reason, created_by_platform_user_id, created_at, updated_at
`

type UpsertOrganizationEntitlementOverrideParams struct {
	OrganizationID          int64       `json:"organization_id"`
	EntitlementKey          string      `json:"entitlement_key"`
	Enabled                 pgtype.Bool `json:"enabled"`
	LimitValue              pgtype.Int8 `json:"limit_value"`
	Reason                  string      `json:"reason"`
	CreatedByPlatformUserID pgtype.Int8 `json:"created_by_platform_user_id"`
}

func (q *Queries) UpsertOrganizationEntitlementOverride(ctx context.Context, arg UpsertOrganizationEntitlementOverrideParams) (OrganizationEntitlementOverride, error) {
	row := q.db.QueryRow(ctx, upsertOrganizationEntitlementOverride,
		arg.OrganizationID,
		arg.EntitlementKey,
		arg.Enabled,
		arg.LimitValue,
		arg.Reason,
		arg.CreatedByPlatformUserID,
	)
	var i OrganizationEntitlementOverride
	err := row.Scan(
		&i.OrganizationID,
		&i.EntitlementKey,
		&i.Enabled,
		&i.LimitValue,
		&i.Reason,
		&i.CreatedByPlatformUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrganizationPlanAssignment = `-- name: UpsertOrganizationPlanAssignment :one
INSERT INTO organization_plan_assignments (organization_id, plan_id, status, assigned_by_platform_user_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (organization_id)
DO UPDATE SET plan_id = EXCLUDED.plan_id, status = EXCLUDED.status,
              assigned_by_platform_user_id = EXCLUDED.assigned_by_platform_user_id, updated_at = NOW()
RETURNING organization_id, plan_id, status, assigned_by_platform_user_id, created_at, updated_at
`

type UpsertOrganizationPlanAssignmentParams struct {
	OrganizationID           int64       `json:"organization_id"`
	PlanID                   int64       `json:"plan_id"`
	Status                   string      `json:"status"`
	AssignedByPlatformUserID pgtype.Int8 `json:"assigned_by_platform_user_id"`
}

func (q *Queries) UpsertOrganizationPlanAssignment(ctx context.Context, arg UpsertOrganizationPlanAssignmentParams) (OrganizationPlanAssignment, error) {
	row := q.db.QueryRow(ctx, upsertOrganizationPlanAssignment,
		arg.OrganizationID,
		arg.PlanID,
		arg.Status,
		arg.AssignedByPlatformUserID,
	)
	var i OrganizationPlanAssignment
	err := row.Scan(
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.AssignedByPlatformUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPlanEntitlement = `-- name: UpsertPlanEntitlement :one
INSERT INTO plan_entitlements (plan_id, entitlement_key, enabled, limit_value)
VALUES ($1, $2, $3, $4)
ON CONFLICT (plan_id, entitlement_key)
DO UPDATE SET enabled = EXCLUDED.enabled, limit_value = EXCLUDED.limit_value, updated_at = NOW()
RETURNING plan_id, entitlement_key, enabled, limit_value, created_at, updated_at
`

type UpsertPlanEntitlementParams struct {
	PlanID         int64       `json:"plan_id"`
	EntitlementKey string      `json:"entitlement_key"`
	Enabled        bool        `json:"enabled"`
	LimitValue     pgtype.Int8 `json:"limit_value"`
}

func (q *Queries) UpsertPlanEntitlement(ctx context.Context, arg UpsertPlanEntitlementParams) (PlanEntitlement, error) {
	row := q.db.QueryRow(ctx, upsertPlanEntitlement,
		arg.PlanID,
		arg.EntitlementKey,
		arg.Enabled,
		arg.LimitValue,
	)
	var i PlanEntitlement
	err := row.Scan(
		&i.PlanID,
		&i.EntitlementKey,
		&i.Enabled,
		&i.LimitValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
