// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_log.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEventsBySession = `-- name: GetEventsBySession :many
SELECT id, session_id, branch_id, event_type, actor_type, actor_id, payload, created_at FROM event_log
WHERE session_id = $1
ORDER BY created_at ASC
LIMIT 200
`

func (q *Queries) GetEventsBySession(ctx context.Context, sessionID pgtype.UUID) ([]EventLog, error) {
	rows, err := q.db.Query(ctx, getEventsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventLog{}
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.BranchID,
			&i.EventType,
			&i.ActorType,
			&i.ActorID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentEventsByBranch = `-- name: GetRecentEventsByBranch :many
SELECT id, session_id, branch_id, event_type, actor_type, actor_id, payload, created_at FROM event_log
WHERE branch_id = $1
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) GetRecentEventsByBranch(ctx context.Context, branchID pgtype.Int8) ([]EventLog, error) {
	rows, err := q.db.Query(ctx, getRecentEventsByBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventLog{}
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.BranchID,
			&i.EventType,
			&i.ActorType,
			&i.ActorID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEventLog = `-- name: InsertEventLog :exec
INSERT INTO event_log (session_id, branch_id, event_type, actor_type, actor_id, payload)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertEventLogParams struct {
	SessionID pgtype.UUID     `json:"session_id"`
	BranchID  pgtype.Int8     `json:"branch_id"`
	EventType string          `json:"event_type"`
	ActorType string          `json:"actor_type"`
	ActorID   pgtype.Text     `json:"actor_id"`
	Payload   json.RawMessage `json:"payload"`
}

func (q *Queries) InsertEventLog(ctx context.Context, arg InsertEventLogParams) error {
	_, err := q.db.Exec(ctx, insertEventLog,
		arg.SessionID,
		arg.BranchID,
		arg.EventType,
		arg.ActorType,
		arg.ActorID,
		arg.Payload,
	)
	return err
}
