// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flags.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFeatureFlag = `-- name: CreateFeatureFlag :one
INSERT INTO platform_feature_flags (key, name, description, default_enabled)
VALUES ($1, $2, $3, $4)
RETURNING key, name, description, default_enabled, created_at, updated_at
`

type CreateFeatureFlagParams struct {
	Key            string `json:"key"`
	Name           string `json:"name"`
	Description    string `json:"description"`
	DefaultEnabled bool   `json:"default_enabled"`
}

func (q *Queries) CreateFeatureFlag(ctx context.Context, arg CreateFeatureFlagParams) (PlatformFeatureFlag, error) {
	row := q.db.QueryRow(ctx, createFeatureFlag,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.DefaultEnabled,
	)
	var i PlatformFeatureFlag
	err := row.Scan(
		&i.Key,
		&i.Name,
		&i.Description,
		&i.DefaultEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBranchFlagOverride = `-- name: DeleteBranchFlagOverride :exec
DELETE FROM platform_flag_branch_overrides WHERE branch_id = $1 AND flag_key = $2
`

type DeleteBranchFlagOverrideParams struct {
	BranchID int64  `json:"branch_id"`
	FlagKey  string `json:"flag_key"`
}

func (q *Queries) DeleteBranchFlagOverride(ctx context.Context, arg DeleteBranchFlagOverrideParams) error {
	_, err := q.db.Exec(ctx, deleteBranchFlagOverride, arg.BranchID, arg.FlagKey)
	return err
}

const deleteGlobalFlagOverride = `-- name: DeleteGlobalFlagOverride :exec
DELETE FROM platform_flag_global_overrides WHERE flag_key = $1
`

func (q *Queries) DeleteGlobalFlagOverride(ctx context.Context, flagKey string) error {
	_, err := q.db.Exec(ctx, deleteGlobalFlagOverride, flagKey)
	return err
}

const deleteOrganizationFlagOverride = `-- name: DeleteOrganizationFlagOverride :exec
DELETE FROM platform_flag_organization_overrides WHERE organization_id = $1 AND flag_key = $2
`

type DeleteOrganizationFlagOverrideParams struct {
	OrganizationID int64  `json:"organization_id"`
	FlagKey        string `json:"flag_key"`
}

func (q *Queries) DeleteOrganizationFlagOverride(ctx context.Context, arg DeleteOrganizationFlagOverrideParams) error {
	_, err := q.db.Exec(ctx, deleteOrganizationFlagOverride, arg.OrganizationID, arg.FlagKey)
	return err
}

const getFeatureFlag = `-- name: GetFeatureFlag :one
SELECT key, name, description, default_enabled, created_at, updated_at FROM platform_feature_flags WHERE key = $1
`

func (q *Queries) GetFeatureFlag(ctx context.Context, key string) (PlatformFeatureFlag, error) {
	row := q.db.QueryRow(ctx, getFeatureFlag, key)
	var i PlatformFeatureFlag
	err := row.Scan(
		&i.Key,
		&i.Name,
		&i.Description,
		&i.DefaultEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBranchFlagOverrides = `-- name: ListBranchFlagOverrides :many
SELECT branch_id, flag_key, enabled, reason, updated_by_platform_user_id, created_at, updated_at FROM platform_flag_branch_overrides WHERE branch_id = $1 ORDER BY flag_key
`

func (q *Queries) ListBranchFlagOverrides(ctx context.Context, branchID int64) ([]PlatformFlagBranchOverride, error) {
	rows, err := q.db.Query(ctx, listBranchFlagOverrides, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformFlagBranchOverride{}
	for rows.Next() {
		var i PlatformFlagBranchOverride
		if err := rows.Scan(
			&i.BranchID,
			&i.FlagKey,
			&i.Enabled,
			&i.Reason,
			&i.UpdatedByPlatformUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatureFlags = `-- name: ListFeatureFlags :many
SELECT key, name, description, default_enabled, created_at, updated_at FROM platform_feature_flags ORDER BY key
`

func (q *Queries) ListFeatureFlags(ctx context.Context) ([]PlatformFeatureFlag, error) {
	rows, err := q.db.Query(ctx, listFeatureFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformFeatureFlag{}
	for rows.Next() {
		var i PlatformFeatureFlag
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.Description,
			&i.DefaultEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalFlagOverrides = `-- name: ListGlobalFlagOverrides :many
SELECT flag_key, enabled, updated_by_platform_user_id, created_at, updated_at FROM platform_flag_global_overrides ORDER BY flag_key
`

func (q *Queries) ListGlobalFlagOverrides(ctx context.Context) ([]PlatformFlagGlobalOverride, error) {
	rows, err := q.db.Query(ctx, listGlobalFlagOverrides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformFlagGlobalOverride{}
	for rows.Next() {
		var i PlatformFlagGlobalOverride
		if err := rows.Scan(
			&i.FlagKey,
			&i.Enabled,
			&i.UpdatedByPlatformUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationFlagOverrides = `-- name: ListOrganizationFlagOverrides :many
SELECT organization_id, flag_key, enabled, reason, updated_by_platform_user_id, created_at, updated_at FROM platform_flag_organization_overrides WHERE organization_id = $1 ORDER BY flag_key
`

func (q *Queries) ListOrganizationFlagOverrides(ctx context.Context, organizationID int64) ([]PlatformFlagOrganizationOverride, error) {
	rows, err := q.db.Query(ctx, listOrganizationFlagOverrides, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformFlagOrganizationOverride{}
	for rows.Next() {
		var i PlatformFlagOrganizationOverride
		if err := rows.Scan(
			&i.OrganizationID,
			&i.FlagKey,
			&i.Enabled,
			&i.Reason,
			&i.UpdatedByPlatformUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeatureFlag = `-- name: UpdateFeatureFlag :one
UPDATE platform_feature_flags
SET name = $2, description = $3, default_enabled = $4, updated_at = NOW()
WHERE key = $1
RETURNING key, name, description, default_enabled, created_at, updated_at
`

type UpdateFeatureFlagParams struct {
	Key            string `json:"key"`
	Name           string `json:"name"`
	Description    string `json:"description"`
	DefaultEnabled bool   `json:"default_enabled"`
}

func (q *Queries) UpdateFeatureFlag(ctx context.Context, arg UpdateFeatureFlagParams) (PlatformFeatureFlag, error) {
	row := q.db.QueryRow(ctx, updateFeatureFlag,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.DefaultEnabled,
	)
	var i PlatformFeatureFlag
	err := row.Scan(
		&i.Key,
		&i.Name,
		&i.Description,
		&i.DefaultEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBranchFlagOverride = `-- name: UpsertBranchFlagOverride :one
INSERT INTO platform_flag_branch_overrides (branch_id, flag_key, enabled, reason, updated_by_platform_user_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (branch_id, flag_key)
DO UPDATE SET enabled = EXCLUDED.enabled, reason = EXCLUDED.reason,
              updated_by_platform_user_id = EXCLUDED.updated_by_platform_user_id, updated_at = NOW()
RETURNING branch_id, flag_key, enabled, reason, updated_by_platform_user_id, created_at, updated_at
`

type UpsertBranchFlagOverrideParams struct {
	BranchID                int64       `json:"branch_id"`
	FlagKey                 string      `json:"flag_key"`
	Enabled                 bool        `json:"enabled"`
	Reason                  string      `json:"reason"`
	UpdatedByPlatformUserID pgtype.Int8 `json:"updated_by_platform_user_id"`
}

func (q *Queries) UpsertBranchFlagOverride(ctx context.Context, arg UpsertBranchFlagOverrideParams) (PlatformFlagBranchOverride, error) {
	row := q.db.QueryRow(ctx, upsertBranchFlagOverride,
		arg.BranchID,
		arg.FlagKey,
		arg.Enabled,
		arg.Reason,
		arg.UpdatedByPlatformUserID,
	)
	var i PlatformFlagBranchOverride
	err := row.Scan(
		&i.BranchID,
		&i.FlagKey,
		&i.Enabled,
		&i.Reason,
		&i.UpdatedByPlatformUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGlobalFlagOverride = `-- name: UpsertGlobalFlagOverride :one
INSERT INTO platform_flag_global_overrides (flag_key, enabled, updated_by_platform_user_id)
VALUES ($1, $2, $3)
ON CONFLICT (flag_key)
DO UPDATE SET enabled = EXCLUDED.enabled,
              updated_by_platform_user_id = EXCLUDED.updated_by_platform_user_id,
              updated_at = NOW()
RETURNING flag_key, enabled, updated_by_platform_user_id, created_at, updated_at
`

type UpsertGlobalFlagOverrideParams struct {
	FlagKey                 string      `json:"flag_key"`
	Enabled                 bool        `json:"enabled"`
	UpdatedByPlatformUserID pgtype.Int8 `json:"updated_by_platform_user_id"`
}

func (q *Queries) UpsertGlobalFlagOverride(ctx context.Context, arg UpsertGlobalFlagOverrideParams) (PlatformFlagGlobalOverride, error) {
	row := q.db.QueryRow(ctx, upsertGlobalFlagOverride, arg.FlagKey, arg.Enabled, arg.UpdatedByPlatformUserID)
	var i PlatformFlagGlobalOverride
	err := row.Scan(
		&i.FlagKey,
		&i.Enabled,
		&i.UpdatedByPlatformUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrganizationFlagOverride = `-- name: UpsertOrganizationFlagOverride :one
INSERT INTO platform_flag_organization_overrides (organization_id, flag_key, enabled, reason, updated_by_platform_user_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (organization_id, flag_key)
DO UPDATE SET enabled = EXCLUDED.enabled, reason = EXCLUDED.reason,
              updated_by_platform_user_id = EXCLUDED.updated_by_platform_user_id, updated_at = NOW()
RETURNING organization_id, flag_key, enabled, reason, updated_by_platform_user_id, created_at, updated_at
`

type UpsertOrganizationFlagOverrideParams struct {
	OrganizationID          int64       `json:"organization_id"`
	FlagKey                 string      `json:"flag_key"`
	Enabled                 bool        `json:"enabled"`
	Reason                  string      `json:"reason"`
	UpdatedByPlatformUserID pgtype.Int8 `json:"updated_by_platform_user_id"`
}

func (q *Queries) UpsertOrganizationFlagOverride(ctx context.Context, arg UpsertOrganizationFlagOverrideParams) (PlatformFlagOrganizationOverride, error) {
	row := q.db.QueryRow(ctx, upsertOrganizationFlagOverride,
		arg.OrganizationID,
		arg.FlagKey,
		arg.Enabled,
		arg.Reason,
		arg.UpdatedByPlatformUserID,
	)
	var i PlatformFlagOrganizationOverride
	err := row.Scan(
		&i.OrganizationID,
		&i.FlagKey,
		&i.Enabled,
		&i.Reason,
		&i.UpdatedByPlatformUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
