// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys
SET response_resource_type = $6,
    response_resource_id = $7,
    status = 'completed'
WHERE scope_type = $1
  AND scope_id = $2
  AND actor_type = $3
  AND actor_id = $4
  AND key = $5
`

type CompleteIdempotencyKeyParams struct {
	ScopeType            string      `json:"scope_type"`
	ScopeID              string      `json:"scope_id"`
	ActorType            string      `json:"actor_type"`
	ActorID              string      `json:"actor_id"`
	Key                  string      `json:"key"`
	ResponseResourceType pgtype.Text `json:"response_resource_type"`
	ResponseResourceID   pgtype.Text `json:"response_resource_id"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.ScopeType,
		arg.ScopeID,
		arg.ActorType,
		arg.ActorID,
		arg.Key,
		arg.ResponseResourceType,
		arg.ResponseResourceID,
	)
	return err
}

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (
  scope_type, scope_id, actor_type, actor_id, key, request_hash, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (scope_type, scope_id, actor_type, actor_id, key) DO NOTHING
RETURNING id, scope_type, scope_id, actor_type, actor_id, key, request_hash, response_resource_type, response_resource_id, status, created_at, expires_at
`

type CreateIdempotencyKeyParams struct {
	ScopeType   string    `json:"scope_type"`
	ScopeID     string    `json:"scope_id"`
	ActorType   string    `json:"actor_type"`
	ActorID     string    `json:"actor_id"`
	Key         string    `json:"key"`
	RequestHash string    `json:"request_hash"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey,
		arg.ScopeType,
		arg.ScopeID,
		arg.ActorType,
		arg.ActorID,
		arg.Key,
		arg.RequestHash,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.ScopeID,
		&i.ActorType,
		&i.ActorID,
		&i.Key,
		&i.RequestHash,
		&i.ResponseResourceType,
		&i.ResponseResourceID,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const failIdempotencyKey = `-- name: FailIdempotencyKey :exec
UPDATE idempotency_keys
SET status = 'failed'
WHERE scope_type = $1
  AND scope_id = $2
  AND actor_type = $3
  AND actor_id = $4
  AND key = $5
  AND status = 'pending'
`

type FailIdempotencyKeyParams struct {
	ScopeType string `json:"scope_type"`
	ScopeID   string `json:"scope_id"`
	ActorType string `json:"actor_type"`
	ActorID   string `json:"actor_id"`
	Key       string `json:"key"`
}

func (q *Queries) FailIdempotencyKey(ctx context.Context, arg FailIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, failIdempotencyKey,
		arg.ScopeType,
		arg.ScopeID,
		arg.ActorType,
		arg.ActorID,
		arg.Key,
	)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, scope_type, scope_id, actor_type, actor_id, key, request_hash, response_resource_type, response_resource_id, status, created_at, expires_at FROM idempotency_keys
WHERE scope_type = $1
  AND scope_id = $2
  AND actor_type = $3
  AND actor_id = $4
  AND key = $5
`

type GetIdempotencyKeyParams struct {
	ScopeType string `json:"scope_type"`
	ScopeID   string `json:"scope_id"`
	ActorType string `json:"actor_type"`
	ActorID   string `json:"actor_id"`
	Key       string `json:"key"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey,
		arg.ScopeType,
		arg.ScopeID,
		arg.ActorType,
		arg.ActorID,
		arg.Key,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.ScopeType,
		&i.ScopeID,
		&i.ActorType,
		&i.ActorID,
		&i.Key,
		&i.RequestHash,
		&i.ResponseResourceType,
		&i.ResponseResourceID,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
