// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: loyalty.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const adjustLoyaltyPoints = `-- name: AdjustLoyaltyPoints :one
UPDATE customer_loyalty_accounts
SET points_balance           = points_balance + $1::BIGINT,
    lifetime_points_earned   = lifetime_points_earned + GREATEST($1::BIGINT, 0),
    lifetime_points_redeemed = lifetime_points_redeemed + GREATEST(-$1::BIGINT, 0),
    updated_at               = NOW()
WHERE id = $2
  AND organization_id = $3
  AND points_balance + $1::BIGINT >= 0
RETURNING id, customer_id, organization_id, points_balance, lifetime_points_earned, lifetime_points_redeemed, visit_count, lifetime_spend, created_at, updated_at
`

type AdjustLoyaltyPointsParams struct {
	PointsDelta    int64 `json:"points_delta"`
	AccountID      int64 `json:"account_id"`
	OrganizationID int64 `json:"organization_id"`
}

// Signed manual adjustment; floors at zero. Positive part counts as earned,
// negative part as redeemed so balance = earned - redeemed stays invariant.
func (q *Queries) AdjustLoyaltyPoints(ctx context.Context, arg AdjustLoyaltyPointsParams) (CustomerLoyaltyAccount, error) {
	row := q.db.QueryRow(ctx, adjustLoyaltyPoints, arg.PointsDelta, arg.AccountID, arg.OrganizationID)
	var i CustomerLoyaltyAccount
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.OrganizationID,
		&i.PointsBalance,
		&i.LifetimePointsEarned,
		&i.LifetimePointsRedeemed,
		&i.VisitCount,
		&i.LifetimeSpend,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countEarnTransactionsForAccountSession = `-- name: CountEarnTransactionsForAccountSession :one
SELECT COUNT(*)::BIGINT
FROM customer_loyalty_transactions
WHERE account_id = $1 AND session_id = $2 AND type = 'earn'
`

type CountEarnTransactionsForAccountSessionParams struct {
	AccountID int64       `json:"account_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) CountEarnTransactionsForAccountSession(ctx context.Context, arg CountEarnTransactionsForAccountSessionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEarnTransactionsForAccountSession, arg.AccountID, arg.SessionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countLoyaltyAccounts = `-- name: CountLoyaltyAccounts :one
SELECT COUNT(*)::BIGINT FROM customer_loyalty_accounts WHERE organization_id = $1
`

func (q *Queries) CountLoyaltyAccounts(ctx context.Context, organizationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLoyaltyAccounts, organizationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deductLoyaltyPoints = `-- name: DeductLoyaltyPoints :one
UPDATE customer_loyalty_accounts
SET points_balance           = points_balance - $1::BIGINT,
    lifetime_points_redeemed = lifetime_points_redeemed + $1::BIGINT,
    updated_at               = NOW()
WHERE id = $2
  AND organization_id = $3
  AND points_balance >= $1::BIGINT
RETURNING id, customer_id, organization_id, points_balance, lifetime_points_earned, lifetime_points_redeemed, visit_count, lifetime_spend, created_at, updated_at
`

type DeductLoyaltyPointsParams struct {
	Points         int64 `json:"points"`
	AccountID      int64 `json:"account_id"`
	OrganizationID int64 `json:"organization_id"`
}

// Guarded deduction: returns no row when the balance is insufficient. The row
// lock serializes concurrent redeems; the points_balance >= 0 CHECK is the
// backstop.
func (q *Queries) DeductLoyaltyPoints(ctx context.Context, arg DeductLoyaltyPointsParams) (CustomerLoyaltyAccount, error) {
	row := q.db.QueryRow(ctx, deductLoyaltyPoints, arg.Points, arg.AccountID, arg.OrganizationID)
	var i CustomerLoyaltyAccount
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.OrganizationID,
		&i.PointsBalance,
		&i.LifetimePointsEarned,
		&i.LifetimePointsRedeemed,
		&i.VisitCount,
		&i.LifetimeSpend,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLoyaltyAccountByCustomer = `-- name: GetLoyaltyAccountByCustomer :one
SELECT id, customer_id, organization_id, points_balance, lifetime_points_earned, lifetime_points_redeemed, visit_count, lifetime_spend, created_at, updated_at FROM customer_loyalty_accounts WHERE customer_id = $1 AND organization_id = $2
`

type GetLoyaltyAccountByCustomerParams struct {
	CustomerID     int64 `json:"customer_id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) GetLoyaltyAccountByCustomer(ctx context.Context, arg GetLoyaltyAccountByCustomerParams) (CustomerLoyaltyAccount, error) {
	row := q.db.QueryRow(ctx, getLoyaltyAccountByCustomer, arg.CustomerID, arg.OrganizationID)
	var i CustomerLoyaltyAccount
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.OrganizationID,
		&i.PointsBalance,
		&i.LifetimePointsEarned,
		&i.LifetimePointsRedeemed,
		&i.VisitCount,
		&i.LifetimeSpend,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLoyaltyAccountByID = `-- name: GetLoyaltyAccountByID :one
SELECT id, customer_id, organization_id, points_balance, lifetime_points_earned, lifetime_points_redeemed, visit_count, lifetime_spend, created_at, updated_at FROM customer_loyalty_accounts WHERE id = $1 AND organization_id = $2
`

type GetLoyaltyAccountByIDParams struct {
	ID             int64 `json:"id"`
	OrganizationID int64 `json:"organization_id"`
}

func (q *Queries) GetLoyaltyAccountByID(ctx context.Context, arg GetLoyaltyAccountByIDParams) (CustomerLoyaltyAccount, error) {
	row := q.db.QueryRow(ctx, getLoyaltyAccountByID, arg.ID, arg.OrganizationID)
	var i CustomerLoyaltyAccount
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.OrganizationID,
		&i.PointsBalance,
		&i.LifetimePointsEarned,
		&i.LifetimePointsRedeemed,
		&i.VisitCount,
		&i.LifetimeSpend,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLoyaltyParticipation = `-- name: GetLoyaltyParticipation :one
SELECT
    COUNT(DISTINCT s.id)::BIGINT           AS total_sessions,
    COUNT(DISTINCT t.session_id)::BIGINT   AS loyalty_sessions
FROM sessions s
JOIN branches b ON b.id = s.branch_id
LEFT JOIN customer_loyalty_transactions t ON t.session_id = s.id AND t.type = 'earn'
WHERE b.organization_id = $1
  AND s.created_at >= $2::timestamptz
  AND s.created_at <  $3::timestamptz
`

type GetLoyaltyParticipationParams struct {
	OrganizationID int64     `json:"organization_id"`
	FromTime       time.Time `json:"from_time"`
	ToTime         time.Time `json:"to_time"`
}

type GetLoyaltyParticipationRow struct {
	TotalSessions   int64 `json:"total_sessions"`
	LoyaltySessions int64 `json:"loyalty_sessions"`
}

// Participation: sessions in the window that produced a loyalty earn vs all
// sessions, org-scoped via branches.
func (q *Queries) GetLoyaltyParticipation(ctx context.Context, arg GetLoyaltyParticipationParams) (GetLoyaltyParticipationRow, error) {
	row := q.db.QueryRow(ctx, getLoyaltyParticipation, arg.OrganizationID, arg.FromTime, arg.ToTime)
	var i GetLoyaltyParticipationRow
	err := row.Scan(&i.TotalSessions, &i.LoyaltySessions)
	return i, err
}

const getLoyaltyPointsSummary = `-- name: GetLoyaltyPointsSummary :one
SELECT
    COALESCE(SUM(t.points)  FILTER (WHERE t.type = 'earn'), 0)::BIGINT   AS points_issued,
    COALESCE(SUM(-t.points) FILTER (WHERE t.type = 'redeem'), 0)::BIGINT AS points_redeemed,
    COUNT(*) FILTER (WHERE t.type = 'earn')::BIGINT                      AS earn_count,
    COUNT(*) FILTER (WHERE t.type = 'redeem')::BIGINT                    AS redeem_count,
    COUNT(DISTINCT a.customer_id)::BIGINT                                AS active_customers
FROM customer_loyalty_transactions t
JOIN customer_loyalty_accounts a ON a.id = t.account_id
WHERE a.organization_id = $1
  AND t.created_at >= $2::timestamptz
  AND t.created_at <  $3::timestamptz
`

type GetLoyaltyPointsSummaryParams struct {
	OrganizationID int64     `json:"organization_id"`
	FromTime       time.Time `json:"from_time"`
	ToTime         time.Time `json:"to_time"`
}

type GetLoyaltyPointsSummaryRow struct {
	PointsIssued    int64 `json:"points_issued"`
	PointsRedeemed  int64 `json:"points_redeemed"`
	EarnCount       int64 `json:"earn_count"`
	RedeemCount     int64 `json:"redeem_count"`
	ActiveCustomers int64 `json:"active_customers"`
}

func (q *Queries) GetLoyaltyPointsSummary(ctx context.Context, arg GetLoyaltyPointsSummaryParams) (GetLoyaltyPointsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getLoyaltyPointsSummary, arg.OrganizationID, arg.FromTime, arg.ToTime)
	var i GetLoyaltyPointsSummaryRow
	err := row.Scan(
		&i.PointsIssued,
		&i.PointsRedeemed,
		&i.EarnCount,
		&i.RedeemCount,
		&i.ActiveCustomers,
	)
	return i, err
}

const getLoyaltyProgram = `-- name: GetLoyaltyProgram :one
SELECT organization_id, is_active, earn_rate_points, earn_rate_amount, updated_by_staff_id, created_at, updated_at FROM organization_loyalty_programs WHERE organization_id = $1
`

func (q *Queries) GetLoyaltyProgram(ctx context.Context, organizationID int64) (OrganizationLoyaltyProgram, error) {
	row := q.db.QueryRow(ctx, getLoyaltyProgram, organizationID)
	var i OrganizationLoyaltyProgram
	err := row.Scan(
		&i.OrganizationID,
		&i.IsActive,
		&i.EarnRatePoints,
		&i.EarnRateAmount,
		&i.UpdatedByStaffID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTopLoyaltyCustomers = `-- name: GetTopLoyaltyCustomers :many
SELECT
    a.id AS account_id,
    a.customer_id,
    c.display_name,
    c.phone_e164,
    a.points_balance,
    a.lifetime_points_earned,
    a.visit_count,
    a.lifetime_spend
FROM customer_loyalty_accounts a
JOIN customers c ON c.id = a.customer_id
WHERE a.organization_id = $1
ORDER BY a.lifetime_points_earned DESC, a.lifetime_spend DESC
LIMIT 10
`

type GetTopLoyaltyCustomersRow struct {
	AccountID            int64          `json:"account_id"`
	CustomerID           int64          `json:"customer_id"`
	DisplayName          string         `json:"display_name"`
	PhoneE164            string         `json:"phone_e164"`
	PointsBalance        int64          `json:"points_balance"`
	LifetimePointsEarned int64          `json:"lifetime_points_earned"`
	VisitCount           int64          `json:"visit_count"`
	LifetimeSpend        pgtype.Numeric `json:"lifetime_spend"`
}

func (q *Queries) GetTopLoyaltyCustomers(ctx context.Context, organizationID int64) ([]GetTopLoyaltyCustomersRow, error) {
	rows, err := q.db.Query(ctx, getTopLoyaltyCustomers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopLoyaltyCustomersRow{}
	for rows.Next() {
		var i GetTopLoyaltyCustomersRow
		if err := rows.Scan(
			&i.AccountID,
			&i.CustomerID,
			&i.DisplayName,
			&i.PhoneE164,
			&i.PointsBalance,
			&i.LifetimePointsEarned,
			&i.VisitCount,
			&i.LifetimeSpend,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLoyaltyTransaction = `-- name: InsertLoyaltyTransaction :one
INSERT INTO customer_loyalty_transactions
    (account_id, type, points, amount, payment_id, session_id, performed_by_actor_type, performed_by_staff_id, reason)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, account_id, type, points, amount, payment_id, session_id, performed_by_actor_type, performed_by_staff_id, reason, created_at
`

type InsertLoyaltyTransactionParams struct {
	AccountID            int64          `json:"account_id"`
	Type                 string         `json:"type"`
	Points               int64          `json:"points"`
	Amount               pgtype.Numeric `json:"amount"`
	PaymentID            pgtype.Int8    `json:"payment_id"`
	SessionID            pgtype.UUID    `json:"session_id"`
	PerformedByActorType string         `json:"performed_by_actor_type"`
	PerformedByStaffID   pgtype.Int8    `json:"performed_by_staff_id"`
	Reason               string         `json:"reason"`
}

func (q *Queries) InsertLoyaltyTransaction(ctx context.Context, arg InsertLoyaltyTransactionParams) (CustomerLoyaltyTransaction, error) {
	row := q.db.QueryRow(ctx, insertLoyaltyTransaction,
		arg.AccountID,
		arg.Type,
		arg.Points,
		arg.Amount,
		arg.PaymentID,
		arg.SessionID,
		arg.PerformedByActorType,
		arg.PerformedByStaffID,
		arg.Reason,
	)
	var i CustomerLoyaltyTransaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.Points,
		&i.Amount,
		&i.PaymentID,
		&i.SessionID,
		&i.PerformedByActorType,
		&i.PerformedByStaffID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listLoyaltyTransactions = `-- name: ListLoyaltyTransactions :many
SELECT id, account_id, type, points, amount, payment_id, session_id, performed_by_actor_type, performed_by_staff_id, reason, created_at FROM customer_loyalty_transactions
WHERE account_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListLoyaltyTransactionsParams struct {
	AccountID int64 `json:"account_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListLoyaltyTransactions(ctx context.Context, arg ListLoyaltyTransactionsParams) ([]CustomerLoyaltyTransaction, error) {
	rows, err := q.db.Query(ctx, listLoyaltyTransactions, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerLoyaltyTransaction{}
	for rows.Next() {
		var i CustomerLoyaltyTransaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Type,
			&i.Points,
			&i.Amount,
			&i.PaymentID,
			&i.SessionID,
			&i.PerformedByActorType,
			&i.PerformedByStaffID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLoyaltyAccountForEarn = `-- name: UpsertLoyaltyAccountForEarn :one
INSERT INTO customer_loyalty_accounts
    (customer_id, organization_id, points_balance, lifetime_points_earned, visit_count, lifetime_spend)
VALUES
    ($1, $2, $3, $3, $4, $5)
ON CONFLICT (customer_id, organization_id) DO UPDATE
SET points_balance         = customer_loyalty_accounts.points_balance + EXCLUDED.points_balance,
    lifetime_points_earned = customer_loyalty_accounts.lifetime_points_earned + EXCLUDED.lifetime_points_earned,
    visit_count            = customer_loyalty_accounts.visit_count + EXCLUDED.visit_count,
    lifetime_spend         = customer_loyalty_accounts.lifetime_spend + EXCLUDED.lifetime_spend,
    updated_at             = NOW()
RETURNING id, customer_id, organization_id, points_balance, lifetime_points_earned, lifetime_points_redeemed, visit_count, lifetime_spend, created_at, updated_at
`

type UpsertLoyaltyAccountForEarnParams struct {
	CustomerID     int64          `json:"customer_id"`
	OrganizationID int64          `json:"organization_id"`
	Points         int64          `json:"points"`
	VisitIncrement int64          `json:"visit_increment"`
	Amount         pgtype.Numeric `json:"amount"`
}

// Accrual upsert: creates the account on first earn, otherwise adds points,
// spend, and (first earn per session only — caller decides) a visit.
func (q *Queries) UpsertLoyaltyAccountForEarn(ctx context.Context, arg UpsertLoyaltyAccountForEarnParams) (CustomerLoyaltyAccount, error) {
	row := q.db.QueryRow(ctx, upsertLoyaltyAccountForEarn,
		arg.CustomerID,
		arg.OrganizationID,
		arg.Points,
		arg.VisitIncrement,
		arg.Amount,
	)
	var i CustomerLoyaltyAccount
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.OrganizationID,
		&i.PointsBalance,
		&i.LifetimePointsEarned,
		&i.LifetimePointsRedeemed,
		&i.VisitCount,
		&i.LifetimeSpend,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLoyaltyProgram = `-- name: UpsertLoyaltyProgram :one

INSERT INTO organization_loyalty_programs (organization_id, is_active, earn_rate_points, earn_rate_amount, updated_by_staff_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (organization_id) DO UPDATE
SET is_active           = EXCLUDED.is_active,
    earn_rate_points    = EXCLUDED.earn_rate_points,
    earn_rate_amount    = EXCLUDED.earn_rate_amount,
    updated_by_staff_id = EXCLUDED.updated_by_staff_id,
    updated_at          = NOW()
RETURNING organization_id, is_active, earn_rate_points, earn_rate_amount, updated_by_staff_id, created_at, updated_at
`

type UpsertLoyaltyProgramParams struct {
	OrganizationID   int64          `json:"organization_id"`
	IsActive         bool           `json:"is_active"`
	EarnRatePoints   int64          `json:"earn_rate_points"`
	EarnRateAmount   pgtype.Numeric `json:"earn_rate_amount"`
	UpdatedByStaffID pgtype.Int8    `json:"updated_by_staff_id"`
}

// Customer loyalty (migration 000035). Accounts are org-scoped; the
// transactions table is an append-only signed points ledger.
func (q *Queries) UpsertLoyaltyProgram(ctx context.Context, arg UpsertLoyaltyProgramParams) (OrganizationLoyaltyProgram, error) {
	row := q.db.QueryRow(ctx, upsertLoyaltyProgram,
		arg.OrganizationID,
		arg.IsActive,
		arg.EarnRatePoints,
		arg.EarnRateAmount,
		arg.UpdatedByStaffID,
	)
	var i OrganizationLoyaltyProgram
	err := row.Scan(
		&i.OrganizationID,
		&i.IsActive,
		&i.EarnRatePoints,
		&i.EarnRateAmount,
		&i.UpdatedByStaffID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
