// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menu.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countItemsInCategory = `-- name: CountItemsInCategory :one
SELECT COUNT(*) FROM menu_items WHERE category_id = $1
`

func (q *Queries) CountItemsInCategory(ctx context.Context, categoryID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countItemsInCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItemModifier = `-- name: CreateItemModifier :one
INSERT INTO item_modifiers (item_id, name, price_delta, is_required, modifier_group)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, item_id, name, price_delta, is_required, modifier_group
`

type CreateItemModifierParams struct {
	ItemID        int64          `json:"item_id"`
	Name          string         `json:"name"`
	PriceDelta    pgtype.Numeric `json:"price_delta"`
	IsRequired    bool           `json:"is_required"`
	ModifierGroup string         `json:"modifier_group"`
}

func (q *Queries) CreateItemModifier(ctx context.Context, arg CreateItemModifierParams) (ItemModifier, error) {
	row := q.db.QueryRow(ctx, createItemModifier,
		arg.ItemID,
		arg.Name,
		arg.PriceDelta,
		arg.IsRequired,
		arg.ModifierGroup,
	)
	var i ItemModifier
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Name,
		&i.PriceDelta,
		&i.IsRequired,
		&i.ModifierGroup,
	)
	return i, err
}

const createItemModifierScoped = `-- name: CreateItemModifierScoped :one
INSERT INTO item_modifiers (item_id, name, price_delta, is_required, modifier_group)
SELECT $1, $3, $4, $5, $6
FROM menu_items
WHERE id = $1 AND branch_id = $2
RETURNING id, item_id, name, price_delta, is_required, modifier_group
`

type CreateItemModifierScopedParams struct {
	ItemID        int64          `json:"item_id"`
	BranchID      int64          `json:"branch_id"`
	Name          string         `json:"name"`
	PriceDelta    pgtype.Numeric `json:"price_delta"`
	IsRequired    bool           `json:"is_required"`
	ModifierGroup string         `json:"modifier_group"`
}

func (q *Queries) CreateItemModifierScoped(ctx context.Context, arg CreateItemModifierScopedParams) (ItemModifier, error) {
	row := q.db.QueryRow(ctx, createItemModifierScoped,
		arg.ItemID,
		arg.BranchID,
		arg.Name,
		arg.PriceDelta,
		arg.IsRequired,
		arg.ModifierGroup,
	)
	var i ItemModifier
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Name,
		&i.PriceDelta,
		&i.IsRequired,
		&i.ModifierGroup,
	)
	return i, err
}

const createTable = `-- name: CreateTable :one
INSERT INTO tables (branch_id, identifier, capacity, qr_code_token)
VALUES ($1, $2, $3, $4)
RETURNING id, branch_id, identifier, capacity, qr_code_token, status, created_at
`

type CreateTableParams struct {
	BranchID    int64  `json:"branch_id"`
	Identifier  string `json:"identifier"`
	Capacity    int16  `json:"capacity"`
	QrCodeToken string `json:"qr_code_token"`
}

func (q *Queries) CreateTable(ctx context.Context, arg CreateTableParams) (Table, error) {
	row := q.db.QueryRow(ctx, createTable,
		arg.BranchID,
		arg.Identifier,
		arg.Capacity,
		arg.QrCodeToken,
	)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Identifier,
		&i.Capacity,
		&i.QrCodeToken,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteItemModifier = `-- name: DeleteItemModifier :exec
DELETE FROM item_modifiers WHERE id = $1
`

func (q *Queries) DeleteItemModifier(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteItemModifier, id)
	return err
}

const deleteItemModifierScoped = `-- name: DeleteItemModifierScoped :exec
DELETE FROM item_modifiers
USING menu_items
WHERE item_modifiers.id = $1
  AND item_modifiers.item_id = menu_items.id
  AND menu_items.branch_id = $2
`

type DeleteItemModifierScopedParams struct {
	ID       int64 `json:"id"`
	BranchID int64 `json:"branch_id"`
}

func (q *Queries) DeleteItemModifierScoped(ctx context.Context, arg DeleteItemModifierScopedParams) error {
	_, err := q.db.Exec(ctx, deleteItemModifierScoped, arg.ID, arg.BranchID)
	return err
}

const deleteMenuCategory = `-- name: DeleteMenuCategory :exec
DELETE FROM menu_categories WHERE id = $1 AND branch_id = $2
`

type DeleteMenuCategoryParams struct {
	ID       int64 `json:"id"`
	BranchID int64 `json:"branch_id"`
}

func (q *Queries) DeleteMenuCategory(ctx context.Context, arg DeleteMenuCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteMenuCategory, arg.ID, arg.BranchID)
	return err
}

const deleteMenuItem = `-- name: DeleteMenuItem :exec
DELETE FROM menu_items WHERE id = $1 AND branch_id = $2
`

type DeleteMenuItemParams struct {
	ID       int64 `json:"id"`
	BranchID int64 `json:"branch_id"`
}

func (q *Queries) DeleteMenuItem(ctx context.Context, arg DeleteMenuItemParams) error {
	_, err := q.db.Exec(ctx, deleteMenuItem, arg.ID, arg.BranchID)
	return err
}

const getMenuCategoryByID = `-- name: GetMenuCategoryByID :one
SELECT id, branch_id, name, position, is_active FROM menu_categories WHERE id = $1
`

func (q *Queries) GetMenuCategoryByID(ctx context.Context, id int64) (MenuCategory, error) {
	row := q.db.QueryRow(ctx, getMenuCategoryByID, id)
	var i MenuCategory
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.Position,
		&i.IsActive,
	)
	return i, err
}

const getMenuItemByID = `-- name: GetMenuItemByID :one
SELECT id, category_id, branch_id, name, description, price, is_available, position, is_featured, featured_sort_order, dietary_flags, item_badges, spice_level, image_url FROM menu_items WHERE id = $1
`

func (q *Queries) GetMenuItemByID(ctx context.Context, id int64) (MenuItem, error) {
	row := q.db.QueryRow(ctx, getMenuItemByID, id)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.BranchID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.IsAvailable,
		&i.Position,
		&i.IsFeatured,
		&i.FeaturedSortOrder,
		&i.DietaryFlags,
		&i.ItemBadges,
		&i.SpiceLevel,
		&i.ImageUrl,
	)
	return i, err
}

const getMenuItemsByIDs = `-- name: GetMenuItemsByIDs :many
SELECT id, category_id, branch_id, name, description, price, is_available, position, is_featured, featured_sort_order, dietary_flags, item_badges, spice_level, image_url FROM menu_items WHERE id = ANY($1::bigint[])
`

func (q *Queries) GetMenuItemsByIDs(ctx context.Context, dollar_1 []int64) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, getMenuItemsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuItem{}
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.BranchID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.IsAvailable,
			&i.Position,
			&i.IsFeatured,
			&i.FeaturedSortOrder,
			&i.DietaryFlags,
			&i.ItemBadges,
			&i.SpiceLevel,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModifierWithItemBranch = `-- name: GetModifierWithItemBranch :one
SELECT im.id, im.item_id, im.name, im.price_delta, im.is_required, im.modifier_group, mi.branch_id
FROM item_modifiers im
JOIN menu_items mi ON mi.id = im.item_id
WHERE im.id = $1
`

type GetModifierWithItemBranchRow struct {
	ID            int64          `json:"id"`
	ItemID        int64          `json:"item_id"`
	Name          string         `json:"name"`
	PriceDelta    pgtype.Numeric `json:"price_delta"`
	IsRequired    bool           `json:"is_required"`
	ModifierGroup string         `json:"modifier_group"`
	BranchID      int64          `json:"branch_id"`
}

func (q *Queries) GetModifierWithItemBranch(ctx context.Context, id int64) (GetModifierWithItemBranchRow, error) {
	row := q.db.QueryRow(ctx, getModifierWithItemBranch, id)
	var i GetModifierWithItemBranchRow
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Name,
		&i.PriceDelta,
		&i.IsRequired,
		&i.ModifierGroup,
		&i.BranchID,
	)
	return i, err
}

const getTableByID = `-- name: GetTableByID :one
SELECT id, branch_id, identifier, capacity, qr_code_token, status, created_at FROM tables WHERE id = $1
`

func (q *Queries) GetTableByID(ctx context.Context, id int64) (Table, error) {
	row := q.db.QueryRow(ctx, getTableByID, id)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Identifier,
		&i.Capacity,
		&i.QrCodeToken,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTableByQRToken = `-- name: GetTableByQRToken :one
SELECT id, branch_id, identifier, capacity, qr_code_token, status, created_at FROM tables WHERE qr_code_token = $1
`

func (q *Queries) GetTableByQRToken(ctx context.Context, qrCodeToken string) (Table, error) {
	row := q.db.QueryRow(ctx, getTableByQRToken, qrCodeToken)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Identifier,
		&i.Capacity,
		&i.QrCodeToken,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertMenuCategory = `-- name: InsertMenuCategory :one
INSERT INTO menu_categories (branch_id, name, position)
VALUES ($1, $2, $3)
RETURNING id, branch_id, name, position, is_active
`

type InsertMenuCategoryParams struct {
	BranchID int64  `json:"branch_id"`
	Name     string `json:"name"`
	Position int16  `json:"position"`
}

func (q *Queries) InsertMenuCategory(ctx context.Context, arg InsertMenuCategoryParams) (MenuCategory, error) {
	row := q.db.QueryRow(ctx, insertMenuCategory, arg.BranchID, arg.Name, arg.Position)
	var i MenuCategory
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.Position,
		&i.IsActive,
	)
	return i, err
}

const insertMenuItem = `-- name: InsertMenuItem :one
INSERT INTO menu_items (category_id, branch_id, name, description, price, is_available, position)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, category_id, branch_id, name, description, price, is_available, position, is_featured, featured_sort_order, dietary_flags, item_badges, spice_level, image_url
`

type InsertMenuItemParams struct {
	CategoryID  int64          `json:"category_id"`
	BranchID    int64          `json:"branch_id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	IsAvailable bool           `json:"is_available"`
	Position    int16          `json:"position"`
}

func (q *Queries) InsertMenuItem(ctx context.Context, arg InsertMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, insertMenuItem,
		arg.CategoryID,
		arg.BranchID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.IsAvailable,
		arg.Position,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.BranchID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.IsAvailable,
		&i.Position,
		&i.IsFeatured,
		&i.FeaturedSortOrder,
		&i.DietaryFlags,
		&i.ItemBadges,
		&i.SpiceLevel,
		&i.ImageUrl,
	)
	return i, err
}

const listAllMenuCategoriesForBranch = `-- name: ListAllMenuCategoriesForBranch :many
SELECT id, branch_id, name, position, is_active FROM menu_categories
WHERE branch_id = $1
ORDER BY position ASC, id ASC
`

func (q *Queries) ListAllMenuCategoriesForBranch(ctx context.Context, branchID int64) ([]MenuCategory, error) {
	rows, err := q.db.Query(ctx, listAllMenuCategoriesForBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuCategory{}
	for rows.Next() {
		var i MenuCategory
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Name,
			&i.Position,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllMenuItemsForCategory = `-- name: ListAllMenuItemsForCategory :many
SELECT id, category_id, branch_id, name, description, price, is_available, position, is_featured, featured_sort_order, dietary_flags, item_badges, spice_level, image_url FROM menu_items
WHERE category_id = $1
ORDER BY position ASC, id ASC
`

func (q *Queries) ListAllMenuItemsForCategory(ctx context.Context, categoryID int64) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listAllMenuItemsForCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuItem{}
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.BranchID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.IsAvailable,
			&i.Position,
			&i.IsFeatured,
			&i.FeaturedSortOrder,
			&i.DietaryFlags,
			&i.ItemBadges,
			&i.SpiceLevel,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturedMenuItems = `-- name: ListFeaturedMenuItems :many
SELECT id, category_id, branch_id, name, description, price, is_available, position, is_featured, featured_sort_order, dietary_flags, item_badges, spice_level, image_url FROM menu_items
WHERE branch_id = $1
  AND is_featured = TRUE
  AND is_available = TRUE
ORDER BY featured_sort_order ASC, id ASC
`

func (q *Queries) ListFeaturedMenuItems(ctx context.Context, branchID int64) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listFeaturedMenuItems, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuItem{}
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.BranchID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.IsAvailable,
			&i.Position,
			&i.IsFeatured,
			&i.FeaturedSortOrder,
			&i.DietaryFlags,
			&i.ItemBadges,
			&i.SpiceLevel,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuCategoriesForBranch = `-- name: ListMenuCategoriesForBranch :many
SELECT id, branch_id, name, position, is_active FROM menu_categories
WHERE branch_id = $1 AND is_active = TRUE
ORDER BY position ASC
`

func (q *Queries) ListMenuCategoriesForBranch(ctx context.Context, branchID int64) ([]MenuCategory, error) {
	rows, err := q.db.Query(ctx, listMenuCategoriesForBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuCategory{}
	for rows.Next() {
		var i MenuCategory
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Name,
			&i.Position,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItemsForCategory = `-- name: ListMenuItemsForCategory :many
SELECT id, category_id, branch_id, name, description, price, is_available, position, is_featured, featured_sort_order, dietary_flags, item_badges, spice_level, image_url FROM menu_items
WHERE category_id = $1 AND is_available = TRUE
ORDER BY position ASC
`

func (q *Queries) ListMenuItemsForCategory(ctx context.Context, categoryID int64) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listMenuItemsForCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuItem{}
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.BranchID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.IsAvailable,
			&i.Position,
			&i.IsFeatured,
			&i.FeaturedSortOrder,
			&i.DietaryFlags,
			&i.ItemBadges,
			&i.SpiceLevel,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModifiersForItem = `-- name: ListModifiersForItem :many
SELECT id, item_id, name, price_delta, is_required, modifier_group FROM item_modifiers WHERE item_id = $1 ORDER BY id ASC
`

func (q *Queries) ListModifiersForItem(ctx context.Context, itemID int64) ([]ItemModifier, error) {
	rows, err := q.db.Query(ctx, listModifiersForItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemModifier{}
	for rows.Next() {
		var i ItemModifier
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Name,
			&i.PriceDelta,
			&i.IsRequired,
			&i.ModifierGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModifiersForItems = `-- name: ListModifiersForItems :many
SELECT id, item_id, name, price_delta, is_required, modifier_group FROM item_modifiers WHERE item_id = ANY($1::bigint[]) ORDER BY item_id, id ASC
`

func (q *Queries) ListModifiersForItems(ctx context.Context, dollar_1 []int64) ([]ItemModifier, error) {
	rows, err := q.db.Query(ctx, listModifiersForItems, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemModifier{}
	for rows.Next() {
		var i ItemModifier
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Name,
			&i.PriceDelta,
			&i.IsRequired,
			&i.ModifierGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTablesForBranch = `-- name: ListTablesForBranch :many
SELECT id, branch_id, identifier, capacity, qr_code_token, status, created_at FROM tables WHERE branch_id = $1 ORDER BY identifier ASC
`

func (q *Queries) ListTablesForBranch(ctx context.Context, branchID int64) ([]Table, error) {
	rows, err := q.db.Query(ctx, listTablesForBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Table{}
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Identifier,
			&i.Capacity,
			&i.QrCodeToken,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshTableQRToken = `-- name: RefreshTableQRToken :one
UPDATE tables SET qr_code_token = $2 WHERE id = $1 RETURNING id, branch_id, identifier, capacity, qr_code_token, status, created_at
`

type RefreshTableQRTokenParams struct {
	ID          int64  `json:"id"`
	QrCodeToken string `json:"qr_code_token"`
}

func (q *Queries) RefreshTableQRToken(ctx context.Context, arg RefreshTableQRTokenParams) (Table, error) {
	row := q.db.QueryRow(ctx, refreshTableQRToken, arg.ID, arg.QrCodeToken)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Identifier,
		&i.Capacity,
		&i.QrCodeToken,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateMenuCategory = `-- name: UpdateMenuCategory :one
UPDATE menu_categories
SET name = $2, position = $3, is_active = $4
WHERE id = $1 AND branch_id = $5
RETURNING id, branch_id, name, position, is_active
`

type UpdateMenuCategoryParams struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Position int16  `json:"position"`
	IsActive bool   `json:"is_active"`
	BranchID int64  `json:"branch_id"`
}

func (q *Queries) UpdateMenuCategory(ctx context.Context, arg UpdateMenuCategoryParams) (MenuCategory, error) {
	row := q.db.QueryRow(ctx, updateMenuCategory,
		arg.ID,
		arg.Name,
		arg.Position,
		arg.IsActive,
		arg.BranchID,
	)
	var i MenuCategory
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.Position,
		&i.IsActive,
	)
	return i, err
}

const updateMenuItem = `-- name: UpdateMenuItem :one
UPDATE menu_items
SET name = $2, description = $3, price = $4, position = $5,
    dietary_flags = $6, item_badges = $7, spice_level = $8,
    category_id = COALESCE($9, category_id),
    image_url = COALESCE($10, image_url)
WHERE id = $1
RETURNING id, category_id, branch_id, name, description, price, is_available, position, is_featured, featured_sort_order, dietary_flags, item_badges, spice_level, image_url
`

type UpdateMenuItemParams struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Description  string         `json:"description"`
	Price        pgtype.Numeric `json:"price"`
	Position     int16          `json:"position"`
	DietaryFlags []string       `json:"dietary_flags"`
	ItemBadges   []string       `json:"item_badges"`
	SpiceLevel   int16          `json:"spice_level"`
	CategoryID   pgtype.Int8    `json:"category_id"`
	ImageUrl     pgtype.Text    `json:"image_url"`
}

func (q *Queries) UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, updateMenuItem,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Position,
		arg.DietaryFlags,
		arg.ItemBadges,
		arg.SpiceLevel,
		arg.CategoryID,
		arg.ImageUrl,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.BranchID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.IsAvailable,
		&i.Position,
		&i.IsFeatured,
		&i.FeaturedSortOrder,
		&i.DietaryFlags,
		&i.ItemBadges,
		&i.SpiceLevel,
		&i.ImageUrl,
	)
	return i, err
}

const updateMenuItemAvailability = `-- name: UpdateMenuItemAvailability :exec
UPDATE menu_items SET is_available = $2 WHERE id = $1
`

type UpdateMenuItemAvailabilityParams struct {
	ID          int64 `json:"id"`
	IsAvailable bool  `json:"is_available"`
}

func (q *Queries) UpdateMenuItemAvailability(ctx context.Context, arg UpdateMenuItemAvailabilityParams) error {
	_, err := q.db.Exec(ctx, updateMenuItemAvailability, arg.ID, arg.IsAvailable)
	return err
}

const updateMenuItemAvailabilityScoped = `-- name: UpdateMenuItemAvailabilityScoped :exec
UPDATE menu_items SET is_available = $3 WHERE id = $1 AND branch_id = $2
`

type UpdateMenuItemAvailabilityScopedParams struct {
	ID          int64 `json:"id"`
	BranchID    int64 `json:"branch_id"`
	IsAvailable bool  `json:"is_available"`
}

func (q *Queries) UpdateMenuItemAvailabilityScoped(ctx context.Context, arg UpdateMenuItemAvailabilityScopedParams) error {
	_, err := q.db.Exec(ctx, updateMenuItemAvailabilityScoped, arg.ID, arg.BranchID, arg.IsAvailable)
	return err
}

const updateMenuItemFeatured = `-- name: UpdateMenuItemFeatured :exec
UPDATE menu_items SET is_featured = $2, featured_sort_order = $3 WHERE id = $1
`

type UpdateMenuItemFeaturedParams struct {
	ID                int64 `json:"id"`
	IsFeatured        bool  `json:"is_featured"`
	FeaturedSortOrder int16 `json:"featured_sort_order"`
}

func (q *Queries) UpdateMenuItemFeatured(ctx context.Context, arg UpdateMenuItemFeaturedParams) error {
	_, err := q.db.Exec(ctx, updateMenuItemFeatured, arg.ID, arg.IsFeatured, arg.FeaturedSortOrder)
	return err
}

const updateMenuItemFeaturedScoped = `-- name: UpdateMenuItemFeaturedScoped :exec
UPDATE menu_items SET is_featured = $3, featured_sort_order = $4 WHERE id = $1 AND branch_id = $2
`

type UpdateMenuItemFeaturedScopedParams struct {
	ID                int64 `json:"id"`
	BranchID          int64 `json:"branch_id"`
	IsFeatured        bool  `json:"is_featured"`
	FeaturedSortOrder int16 `json:"featured_sort_order"`
}

func (q *Queries) UpdateMenuItemFeaturedScoped(ctx context.Context, arg UpdateMenuItemFeaturedScopedParams) error {
	_, err := q.db.Exec(ctx, updateMenuItemFeaturedScoped,
		arg.ID,
		arg.BranchID,
		arg.IsFeatured,
		arg.FeaturedSortOrder,
	)
	return err
}

const updateMenuItemScoped = `-- name: UpdateMenuItemScoped :one
UPDATE menu_items
SET name = $3, description = $4, price = $5, position = $6,
    dietary_flags = $7, item_badges = $8, spice_level = $9,
    category_id = COALESCE($10, category_id),
    image_url = COALESCE($11, image_url)
WHERE id = $1 AND branch_id = $2
RETURNING id, category_id, branch_id, name, description, price, is_available, position, is_featured, featured_sort_order, dietary_flags, item_badges, spice_level, image_url
`

type UpdateMenuItemScopedParams struct {
	ID           int64          `json:"id"`
	BranchID     int64          `json:"branch_id"`
	Name         string         `json:"name"`
	Description  string         `json:"description"`
	Price        pgtype.Numeric `json:"price"`
	Position     int16          `json:"position"`
	DietaryFlags []string       `json:"dietary_flags"`
	ItemBadges   []string       `json:"item_badges"`
	SpiceLevel   int16          `json:"spice_level"`
	CategoryID   pgtype.Int8    `json:"category_id"`
	ImageUrl     pgtype.Text    `json:"image_url"`
}

func (q *Queries) UpdateMenuItemScoped(ctx context.Context, arg UpdateMenuItemScopedParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, updateMenuItemScoped,
		arg.ID,
		arg.BranchID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Position,
		arg.DietaryFlags,
		arg.ItemBadges,
		arg.SpiceLevel,
		arg.CategoryID,
		arg.ImageUrl,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.BranchID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.IsAvailable,
		&i.Position,
		&i.IsFeatured,
		&i.FeaturedSortOrder,
		&i.DietaryFlags,
		&i.ItemBadges,
		&i.SpiceLevel,
		&i.ImageUrl,
	)
	return i, err
}

const updateTableStatus = `-- name: UpdateTableStatus :exec
UPDATE tables SET status = $2 WHERE id = $1
`

type UpdateTableStatusParams struct {
	ID     int64       `json:"id"`
	Status TableStatus `json:"status"`
}

func (q *Queries) UpdateTableStatus(ctx context.Context, arg UpdateTableStatusParams) error {
	_, err := q.db.Exec(ctx, updateTableStatus, arg.ID, arg.Status)
	return err
}
