// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menu.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTable = `-- name: CreateTable :one
INSERT INTO tables (branch_id, identifier, capacity, qr_code_token)
VALUES ($1, $2, $3, $4)
RETURNING id, branch_id, identifier, capacity, qr_code_token, status, created_at
`

type CreateTableParams struct {
	BranchID    int64  `json:"branch_id"`
	Identifier  string `json:"identifier"`
	Capacity    int16  `json:"capacity"`
	QrCodeToken string `json:"qr_code_token"`
}

func (q *Queries) CreateTable(ctx context.Context, arg CreateTableParams) (Table, error) {
	row := q.db.QueryRow(ctx, createTable,
		arg.BranchID,
		arg.Identifier,
		arg.Capacity,
		arg.QrCodeToken,
	)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Identifier,
		&i.Capacity,
		&i.QrCodeToken,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getMenuItemByID = `-- name: GetMenuItemByID :one
SELECT id, category_id, branch_id, name, description, price, is_available, position FROM menu_items WHERE id = $1
`

func (q *Queries) GetMenuItemByID(ctx context.Context, id int64) (MenuItem, error) {
	row := q.db.QueryRow(ctx, getMenuItemByID, id)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.BranchID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.IsAvailable,
		&i.Position,
	)
	return i, err
}

const getMenuItemsByIDs = `-- name: GetMenuItemsByIDs :many
SELECT id, category_id, branch_id, name, description, price, is_available, position FROM menu_items WHERE id = ANY($1::bigint[])
`

func (q *Queries) GetMenuItemsByIDs(ctx context.Context, dollar_1 []int64) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, getMenuItemsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuItem{}
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.BranchID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.IsAvailable,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTableByID = `-- name: GetTableByID :one
SELECT id, branch_id, identifier, capacity, qr_code_token, status, created_at FROM tables WHERE id = $1
`

func (q *Queries) GetTableByID(ctx context.Context, id int64) (Table, error) {
	row := q.db.QueryRow(ctx, getTableByID, id)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Identifier,
		&i.Capacity,
		&i.QrCodeToken,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTableByQRToken = `-- name: GetTableByQRToken :one
SELECT id, branch_id, identifier, capacity, qr_code_token, status, created_at FROM tables WHERE qr_code_token = $1
`

func (q *Queries) GetTableByQRToken(ctx context.Context, qrCodeToken string) (Table, error) {
	row := q.db.QueryRow(ctx, getTableByQRToken, qrCodeToken)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Identifier,
		&i.Capacity,
		&i.QrCodeToken,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertMenuCategory = `-- name: InsertMenuCategory :one
INSERT INTO menu_categories (branch_id, name, position)
VALUES ($1, $2, $3)
RETURNING id, branch_id, name, position, is_active
`

type InsertMenuCategoryParams struct {
	BranchID int64  `json:"branch_id"`
	Name     string `json:"name"`
	Position int16  `json:"position"`
}

func (q *Queries) InsertMenuCategory(ctx context.Context, arg InsertMenuCategoryParams) (MenuCategory, error) {
	row := q.db.QueryRow(ctx, insertMenuCategory, arg.BranchID, arg.Name, arg.Position)
	var i MenuCategory
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.Position,
		&i.IsActive,
	)
	return i, err
}

const insertMenuItem = `-- name: InsertMenuItem :one
INSERT INTO menu_items (category_id, branch_id, name, description, price, is_available, position)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, category_id, branch_id, name, description, price, is_available, position
`

type InsertMenuItemParams struct {
	CategoryID  int64          `json:"category_id"`
	BranchID    int64          `json:"branch_id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	IsAvailable bool           `json:"is_available"`
	Position    int16          `json:"position"`
}

func (q *Queries) InsertMenuItem(ctx context.Context, arg InsertMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, insertMenuItem,
		arg.CategoryID,
		arg.BranchID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.IsAvailable,
		arg.Position,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.BranchID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.IsAvailable,
		&i.Position,
	)
	return i, err
}

const listMenuCategoriesForBranch = `-- name: ListMenuCategoriesForBranch :many
SELECT id, branch_id, name, position, is_active FROM menu_categories
WHERE branch_id = $1 AND is_active = TRUE
ORDER BY position ASC
`

func (q *Queries) ListMenuCategoriesForBranch(ctx context.Context, branchID int64) ([]MenuCategory, error) {
	rows, err := q.db.Query(ctx, listMenuCategoriesForBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuCategory{}
	for rows.Next() {
		var i MenuCategory
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Name,
			&i.Position,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItemsForCategory = `-- name: ListMenuItemsForCategory :many
SELECT id, category_id, branch_id, name, description, price, is_available, position FROM menu_items
WHERE category_id = $1 AND is_available = TRUE
ORDER BY position ASC
`

func (q *Queries) ListMenuItemsForCategory(ctx context.Context, categoryID int64) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listMenuItemsForCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuItem{}
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.BranchID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.IsAvailable,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModifiersForItem = `-- name: ListModifiersForItem :many
SELECT id, item_id, name, price_delta, is_required FROM item_modifiers WHERE item_id = $1 ORDER BY id ASC
`

func (q *Queries) ListModifiersForItem(ctx context.Context, itemID int64) ([]ItemModifier, error) {
	rows, err := q.db.Query(ctx, listModifiersForItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemModifier{}
	for rows.Next() {
		var i ItemModifier
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Name,
			&i.PriceDelta,
			&i.IsRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModifiersForItems = `-- name: ListModifiersForItems :many
SELECT id, item_id, name, price_delta, is_required FROM item_modifiers WHERE item_id = ANY($1::bigint[]) ORDER BY item_id, id ASC
`

func (q *Queries) ListModifiersForItems(ctx context.Context, dollar_1 []int64) ([]ItemModifier, error) {
	rows, err := q.db.Query(ctx, listModifiersForItems, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemModifier{}
	for rows.Next() {
		var i ItemModifier
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Name,
			&i.PriceDelta,
			&i.IsRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTablesForBranch = `-- name: ListTablesForBranch :many
SELECT id, branch_id, identifier, capacity, qr_code_token, status, created_at FROM tables WHERE branch_id = $1 ORDER BY identifier ASC
`

func (q *Queries) ListTablesForBranch(ctx context.Context, branchID int64) ([]Table, error) {
	rows, err := q.db.Query(ctx, listTablesForBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Table{}
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Identifier,
			&i.Capacity,
			&i.QrCodeToken,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshTableQRToken = `-- name: RefreshTableQRToken :one
UPDATE tables SET qr_code_token = $2 WHERE id = $1 RETURNING id, branch_id, identifier, capacity, qr_code_token, status, created_at
`

type RefreshTableQRTokenParams struct {
	ID          int64  `json:"id"`
	QrCodeToken string `json:"qr_code_token"`
}

func (q *Queries) RefreshTableQRToken(ctx context.Context, arg RefreshTableQRTokenParams) (Table, error) {
	row := q.db.QueryRow(ctx, refreshTableQRToken, arg.ID, arg.QrCodeToken)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Identifier,
		&i.Capacity,
		&i.QrCodeToken,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateMenuItem = `-- name: UpdateMenuItem :one
UPDATE menu_items
SET name = $2, description = $3, price = $4, position = $5
WHERE id = $1
RETURNING id, category_id, branch_id, name, description, price, is_available, position
`

type UpdateMenuItemParams struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	Position    int16          `json:"position"`
}

func (q *Queries) UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, updateMenuItem,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Position,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.BranchID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.IsAvailable,
		&i.Position,
	)
	return i, err
}

const updateMenuItemAvailability = `-- name: UpdateMenuItemAvailability :exec
UPDATE menu_items SET is_available = $2 WHERE id = $1
`

type UpdateMenuItemAvailabilityParams struct {
	ID          int64 `json:"id"`
	IsAvailable bool  `json:"is_available"`
}

func (q *Queries) UpdateMenuItemAvailability(ctx context.Context, arg UpdateMenuItemAvailabilityParams) error {
	_, err := q.db.Exec(ctx, updateMenuItemAvailability, arg.ID, arg.IsAvailable)
	return err
}

const updateTableStatus = `-- name: UpdateTableStatus :exec
UPDATE tables SET status = $2 WHERE id = $1
`

type UpdateTableStatusParams struct {
	ID     int64       `json:"id"`
	Status TableStatus `json:"status"`
}

func (q *Queries) UpdateTableStatus(ctx context.Context, arg UpdateTableStatusParams) error {
	_, err := q.db.Exec(ctx, updateTableStatus, arg.ID, arg.Status)
	return err
}
