// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AssistanceStatus string

const (
	AssistanceStatusPending      AssistanceStatus = "pending"
	AssistanceStatusAcknowledged AssistanceStatus = "acknowledged"
	AssistanceStatusResolved     AssistanceStatus = "resolved"
)

func (e *AssistanceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssistanceStatus(s)
	case string:
		*e = AssistanceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AssistanceStatus: %T", src)
	}
	return nil
}

type NullAssistanceStatus struct {
	AssistanceStatus AssistanceStatus `json:"assistance_status"`
	Valid            bool             `json:"valid"` // Valid is true if AssistanceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssistanceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AssistanceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssistanceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssistanceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssistanceStatus), nil
}

type AssistanceType string

const (
	AssistanceTypeWaiter AssistanceType = "waiter"
	AssistanceTypeBill   AssistanceType = "bill"
	AssistanceTypeOther  AssistanceType = "other"
)

func (e *AssistanceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssistanceType(s)
	case string:
		*e = AssistanceType(s)
	default:
		return fmt.Errorf("unsupported scan type for AssistanceType: %T", src)
	}
	return nil
}

type NullAssistanceType struct {
	AssistanceType AssistanceType `json:"assistance_type"`
	Valid          bool           `json:"valid"` // Valid is true if AssistanceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssistanceType) Scan(value interface{}) error {
	if value == nil {
		ns.AssistanceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssistanceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssistanceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssistanceType), nil
}

type AuditActorType string

const (
	AuditActorTypePlatformUser     AuditActorType = "platform_user"
	AuditActorTypeOrganizationUser AuditActorType = "organization_user"
	AuditActorTypeStaff            AuditActorType = "staff"
	AuditActorTypeGuest            AuditActorType = "guest"
	AuditActorTypeSystem           AuditActorType = "system"
	AuditActorTypeWebhook          AuditActorType = "webhook"
)

func (e *AuditActorType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditActorType(s)
	case string:
		*e = AuditActorType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditActorType: %T", src)
	}
	return nil
}

type NullAuditActorType struct {
	AuditActorType AuditActorType `json:"audit_actor_type"`
	Valid          bool           `json:"valid"` // Valid is true if AuditActorType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditActorType) Scan(value interface{}) error {
	if value == nil {
		ns.AuditActorType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditActorType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditActorType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditActorType), nil
}

type AuditResultType string

const (
	AuditResultTypeSuccess AuditResultType = "success"
	AuditResultTypeFailure AuditResultType = "failure"
	AuditResultTypeDenied  AuditResultType = "denied"
)

func (e *AuditResultType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditResultType(s)
	case string:
		*e = AuditResultType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditResultType: %T", src)
	}
	return nil
}

type NullAuditResultType struct {
	AuditResultType AuditResultType `json:"audit_result_type"`
	Valid           bool            `json:"valid"` // Valid is true if AuditResultType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditResultType) Scan(value interface{}) error {
	if value == nil {
		ns.AuditResultType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditResultType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditResultType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditResultType), nil
}

type AuditRiskLevel string

const (
	AuditRiskLevelLow      AuditRiskLevel = "low"
	AuditRiskLevelMedium   AuditRiskLevel = "medium"
	AuditRiskLevelHigh     AuditRiskLevel = "high"
	AuditRiskLevelCritical AuditRiskLevel = "critical"
)

func (e *AuditRiskLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditRiskLevel(s)
	case string:
		*e = AuditRiskLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditRiskLevel: %T", src)
	}
	return nil
}

type NullAuditRiskLevel struct {
	AuditRiskLevel AuditRiskLevel `json:"audit_risk_level"`
	Valid          bool           `json:"valid"` // Valid is true if AuditRiskLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditRiskLevel) Scan(value interface{}) error {
	if value == nil {
		ns.AuditRiskLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditRiskLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditRiskLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditRiskLevel), nil
}

type AuditSourceType string

const (
	AuditSourceTypeWeb     AuditSourceType = "web"
	AuditSourceTypeMobile  AuditSourceType = "mobile"
	AuditSourceTypePwa     AuditSourceType = "pwa"
	AuditSourceTypeApi     AuditSourceType = "api"
	AuditSourceTypeWebhook AuditSourceType = "webhook"
	AuditSourceTypeSystem  AuditSourceType = "system"
)

func (e *AuditSourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditSourceType(s)
	case string:
		*e = AuditSourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditSourceType: %T", src)
	}
	return nil
}

type NullAuditSourceType struct {
	AuditSourceType AuditSourceType `json:"audit_source_type"`
	Valid           bool            `json:"valid"` // Valid is true if AuditSourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditSourceType) Scan(value interface{}) error {
	if value == nil {
		ns.AuditSourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditSourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditSourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditSourceType), nil
}

type OrderStatus string

const (
	OrderStatusPending   OrderStatus = "pending"
	OrderStatusConfirmed OrderStatus = "confirmed"
	OrderStatusPreparing OrderStatus = "preparing"
	OrderStatusReady     OrderStatus = "ready"
	OrderStatusServed    OrderStatus = "served"
	OrderStatusCancelled OrderStatus = "cancelled"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type PaymentMethod string

const (
	PaymentMethodCash       PaymentMethod = "cash"
	PaymentMethodCard       PaymentMethod = "card"
	PaymentMethodDigital    PaymentMethod = "digital"
	PaymentMethodCardManual PaymentMethod = "card_manual"
	PaymentMethodUpi        PaymentMethod = "upi"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type PaymentStatus string

const (
	PaymentStatusPending                   PaymentStatus = "pending"
	PaymentStatusCompleted                 PaymentStatus = "completed"
	PaymentStatusFailed                    PaymentStatus = "failed"
	PaymentStatusRefunded                  PaymentStatus = "refunded"
	PaymentStatusRequested                 PaymentStatus = "requested"
	PaymentStatusProviderPending           PaymentStatus = "provider_pending"
	PaymentStatusRequiresStaffConfirmation PaymentStatus = "requires_staff_confirmation"
	PaymentStatusCancelled                 PaymentStatus = "cancelled"
	PaymentStatusPartiallyRefunded         PaymentStatus = "partially_refunded"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type PlanTier string

const (
	PlanTierFree     PlanTier = "free"
	PlanTierStandard PlanTier = "standard"
	PlanTierPremium  PlanTier = "premium"
)

func (e *PlanTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlanTier(s)
	case string:
		*e = PlanTier(s)
	default:
		return fmt.Errorf("unsupported scan type for PlanTier: %T", src)
	}
	return nil
}

type NullPlanTier struct {
	PlanTier PlanTier `json:"plan_tier"`
	Valid    bool     `json:"valid"` // Valid is true if PlanTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlanTier) Scan(value interface{}) error {
	if value == nil {
		ns.PlanTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlanTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlanTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlanTier), nil
}

type PromoType string

const (
	PromoTypeFlatAmount PromoType = "flat_amount"
	PromoTypePercentage PromoType = "percentage"
)

func (e *PromoType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PromoType(s)
	case string:
		*e = PromoType(s)
	default:
		return fmt.Errorf("unsupported scan type for PromoType: %T", src)
	}
	return nil
}

type NullPromoType struct {
	PromoType PromoType `json:"promo_type"`
	Valid     bool      `json:"valid"` // Valid is true if PromoType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPromoType) Scan(value interface{}) error {
	if value == nil {
		ns.PromoType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PromoType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPromoType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PromoType), nil
}

type SessionStatus string

const (
	SessionStatusActive               SessionStatus = "active"
	SessionStatusClosed               SessionStatus = "closed"
	SessionStatusAbandoned            SessionStatus = "abandoned"
	SessionStatusPaymentPending       SessionStatus = "payment_pending"
	SessionStatusAwaitingReactivation SessionStatus = "awaiting_reactivation"
	SessionStatusExpired              SessionStatus = "expired"
)

func (e *SessionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionStatus(s)
	case string:
		*e = SessionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionStatus: %T", src)
	}
	return nil
}

type NullSessionStatus struct {
	SessionStatus SessionStatus `json:"session_status"`
	Valid         bool          `json:"valid"` // Valid is true if SessionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SessionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionStatus), nil
}

type StaffRole string

const (
	StaffRoleOwner   StaffRole = "owner"
	StaffRoleManager StaffRole = "manager"
	StaffRoleWaiter  StaffRole = "waiter"
	StaffRoleKitchen StaffRole = "kitchen"
)

func (e *StaffRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StaffRole(s)
	case string:
		*e = StaffRole(s)
	default:
		return fmt.Errorf("unsupported scan type for StaffRole: %T", src)
	}
	return nil
}

type NullStaffRole struct {
	StaffRole StaffRole `json:"staff_role"`
	Valid     bool      `json:"valid"` // Valid is true if StaffRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStaffRole) Scan(value interface{}) error {
	if value == nil {
		ns.StaffRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StaffRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStaffRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StaffRole), nil
}

type TableStatus string

const (
	TableStatusAvailable TableStatus = "available"
	TableStatusOccupied  TableStatus = "occupied"
	TableStatusReserved  TableStatus = "reserved"
)

func (e *TableStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TableStatus(s)
	case string:
		*e = TableStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TableStatus: %T", src)
	}
	return nil
}

type NullTableStatus struct {
	TableStatus TableStatus `json:"table_status"`
	Valid       bool        `json:"valid"` // Valid is true if TableStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTableStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TableStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TableStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTableStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TableStatus), nil
}

type AssistanceRequest struct {
	ID            int64              `json:"id"`
	SessionID     uuid.UUID          `json:"session_id"`
	TableID       int64              `json:"table_id"`
	ParticipantID pgtype.Int8        `json:"participant_id"`
	Type          AssistanceType     `json:"type"`
	Status        AssistanceStatus   `json:"status"`
	CreatedAt     time.Time          `json:"created_at"`
	ResolvedAt    pgtype.Timestamptz `json:"resolved_at"`
}

type AuditLog struct {
	ID             int64           `json:"id"`
	OrganizationID pgtype.Int8     `json:"organization_id"`
	BranchID       pgtype.Int8     `json:"branch_id"`
	RestaurantID   pgtype.Int8     `json:"restaurant_id"`
	SessionID      pgtype.UUID     `json:"session_id"`
	TableID        pgtype.Int8     `json:"table_id"`
	ResourceType   string          `json:"resource_type"`
	ResourceID     string          `json:"resource_id"`
	Action         string          `json:"action"`
	Result         AuditResultType `json:"result"`
	ActorType      AuditActorType  `json:"actor_type"`
	ActorID        string          `json:"actor_id"`
	ActorDisplay   string          `json:"actor_display"`
	ActorScopeJson json.RawMessage `json:"actor_scope_json"`
	RequestID      string          `json:"request_id"`
	CorrelationID  string          `json:"correlation_id"`
	IdempotencyKey string          `json:"idempotency_key"`
	Ip             string          `json:"ip"`
	UserAgent      string          `json:"user_agent"`
	Source         AuditSourceType `json:"source"`
	BeforeJson     []byte          `json:"before_json"`
	AfterJson      []byte          `json:"after_json"`
	MetadataJson   json.RawMessage `json:"metadata_json"`
	RiskLevel      AuditRiskLevel  `json:"risk_level"`
	RowHash        pgtype.Text     `json:"row_hash"`
	PreviousHash   pgtype.Text     `json:"previous_hash"`
	CreatedAt      time.Time       `json:"created_at"`
	EventReference string          `json:"event_reference"`
}

type BillSnapshot struct {
	ID             int64           `json:"id"`
	SessionID      uuid.UUID       `json:"session_id"`
	BranchID       int64           `json:"branch_id"`
	Subtotal       pgtype.Numeric  `json:"subtotal"`
	DiscountAmount pgtype.Numeric  `json:"discount_amount"`
	TaxAmount      pgtype.Numeric  `json:"tax_amount"`
	ServiceCharge  pgtype.Numeric  `json:"service_charge"`
	TipAmount      pgtype.Numeric  `json:"tip_amount"`
	Total          pgtype.Numeric  `json:"total"`
	Currency       string          `json:"currency"`
	SourceOrderIds json.RawMessage `json:"source_order_ids"`
	CreatedByActor string          `json:"created_by_actor"`
	CreatedAt      time.Time       `json:"created_at"`
}

type Branch struct {
	ID                    int64           `json:"id"`
	RestaurantID          int64           `json:"restaurant_id"`
	Name                  string          `json:"name"`
	Address               string          `json:"address"`
	Timezone              string          `json:"timezone"`
	CreatedAt             time.Time       `json:"created_at"`
	SessionTimeoutMinutes int16           `json:"session_timeout_minutes"`
	OrderPrefix           string          `json:"order_prefix"`
	BranchCode            string          `json:"branch_code"`
	OrganizationID        int64           `json:"organization_id"`
	Status                string          `json:"status"`
	SupportMetadataJson   json.RawMessage `json:"support_metadata_json"`
}

type Cart struct {
	ID            int64       `json:"id"`
	SessionID     uuid.UUID   `json:"session_id"`
	ParticipantID pgtype.Int8 `json:"participant_id"`
}

type CartItem struct {
	ID                    int64           `json:"id"`
	CartID                int64           `json:"cart_id"`
	MenuItemID            int64           `json:"menu_item_id"`
	Quantity              int16           `json:"quantity"`
	SelectedModifiersJson json.RawMessage `json:"selected_modifiers_json"`
	Note                  string          `json:"note"`
}

type Customer struct {
	ID           int64              `json:"id"`
	RestaurantID int64              `json:"restaurant_id"`
	PhoneE164    string             `json:"phone_e164"`
	DisplayName  string             `json:"display_name"`
	OptedIn      bool               `json:"opted_in"`
	OptedInAt    pgtype.Timestamptz `json:"opted_in_at"`
	LastSeenAt   time.Time          `json:"last_seen_at"`
	VisitCount   int32              `json:"visit_count"`
	CreatedAt    time.Time          `json:"created_at"`
}

type Entitlement struct {
	Key         string    `json:"key"`
	Kind        string    `json:"kind"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type EventLog struct {
	ID        int64           `json:"id"`
	SessionID pgtype.UUID     `json:"session_id"`
	BranchID  pgtype.Int8     `json:"branch_id"`
	EventType string          `json:"event_type"`
	ActorType string          `json:"actor_type"`
	ActorID   pgtype.Text     `json:"actor_id"`
	Payload   json.RawMessage `json:"payload"`
	CreatedAt time.Time       `json:"created_at"`
}

type IdempotencyKey struct {
	ID                   int64       `json:"id"`
	ScopeType            string      `json:"scope_type"`
	ScopeID              string      `json:"scope_id"`
	ActorType            string      `json:"actor_type"`
	ActorID              string      `json:"actor_id"`
	Key                  string      `json:"key"`
	RequestHash          string      `json:"request_hash"`
	ResponseResourceType pgtype.Text `json:"response_resource_type"`
	ResponseResourceID   pgtype.Text `json:"response_resource_id"`
	Status               string      `json:"status"`
	CreatedAt            time.Time   `json:"created_at"`
	ExpiresAt            time.Time   `json:"expires_at"`
}

type ItemModifier struct {
	ID            int64          `json:"id"`
	ItemID        int64          `json:"item_id"`
	Name          string         `json:"name"`
	PriceDelta    pgtype.Numeric `json:"price_delta"`
	IsRequired    bool           `json:"is_required"`
	ModifierGroup string         `json:"modifier_group"`
}

type MenuCategory struct {
	ID       int64  `json:"id"`
	BranchID int64  `json:"branch_id"`
	Name     string `json:"name"`
	Position int16  `json:"position"`
	IsActive bool   `json:"is_active"`
}

type MenuItem struct {
	ID                int64          `json:"id"`
	CategoryID        int64          `json:"category_id"`
	BranchID          int64          `json:"branch_id"`
	Name              string         `json:"name"`
	Description       string         `json:"description"`
	Price             pgtype.Numeric `json:"price"`
	IsAvailable       bool           `json:"is_available"`
	Position          int16          `json:"position"`
	IsFeatured        bool           `json:"is_featured"`
	FeaturedSortOrder int16          `json:"featured_sort_order"`
	DietaryFlags      []string       `json:"dietary_flags"`
	ItemBadges        []string       `json:"item_badges"`
	SpiceLevel        int16          `json:"spice_level"`
	ImageUrl          pgtype.Text    `json:"image_url"`
}

type Order struct {
	ID                    uuid.UUID      `json:"id"`
	SessionID             uuid.UUID      `json:"session_id"`
	BranchID              int64          `json:"branch_id"`
	PlacedByParticipantID pgtype.Int8    `json:"placed_by_participant_id"`
	Status                OrderStatus    `json:"status"`
	IdempotencyKey        string         `json:"idempotency_key"`
	TotalAmount           pgtype.Numeric `json:"total_amount"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	OrderNumber           pgtype.Text    `json:"order_number"`
	PromoID               pgtype.Int8    `json:"promo_id"`
	DiscountAmount        pgtype.Numeric `json:"discount_amount"`
	OrderBusinessDate     pgtype.Date    `json:"order_business_date"`
	OrderNumberDisplay    string         `json:"order_number_display"`
	OrderOperationalID    string         `json:"order_operational_id"`
}

type OrderItem struct {
	ID                    int64           `json:"id"`
	OrderID               uuid.UUID       `json:"order_id"`
	MenuItemID            int64           `json:"menu_item_id"`
	Quantity              int16           `json:"quantity"`
	UnitPrice             pgtype.Numeric  `json:"unit_price"`
	SelectedModifiersJson json.RawMessage `json:"selected_modifiers_json"`
	Note                  string          `json:"note"`
}

type OrderSequence struct {
	BranchID int64       `json:"branch_id"`
	Date     pgtype.Date `json:"date"`
	LastSeq  int32       `json:"last_seq"`
}

type Organization struct {
	ID                  int64           `json:"id"`
	Code                string          `json:"code"`
	Name                string          `json:"name"`
	LegalName           string          `json:"legal_name"`
	Status              string          `json:"status"`
	PrimaryContactEmail string          `json:"primary_contact_email"`
	SettingsJson        json.RawMessage `json:"settings_json"`
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
}

type OrganizationBranchMembership struct {
	ID             int64     `json:"id"`
	OrganizationID int64     `json:"organization_id"`
	BranchID       int64     `json:"branch_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type OrganizationEntitlementOverride struct {
	OrganizationID          int64       `json:"organization_id"`
	EntitlementKey          string      `json:"entitlement_key"`
	Enabled                 pgtype.Bool `json:"enabled"`
	LimitValue              pgtype.Int8 `json:"limit_value"`
	Reason                  string      `json:"reason"`
	CreatedByPlatformUserID pgtype.Int8 `json:"created_by_platform_user_id"`
	CreatedAt               time.Time   `json:"created_at"`
	UpdatedAt               time.Time   `json:"updated_at"`
}

type OrganizationMember struct {
	ID               int64       `json:"id"`
	OrganizationID   int64       `json:"organization_id"`
	StaffID          int64       `json:"staff_id"`
	Role             string      `json:"role"`
	Status           string      `json:"status"`
	InvitedByStaffID pgtype.Int8 `json:"invited_by_staff_id"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

type OrganizationPlanAssignment struct {
	OrganizationID           int64       `json:"organization_id"`
	PlanID                   int64       `json:"plan_id"`
	Status                   string      `json:"status"`
	AssignedByPlatformUserID pgtype.Int8 `json:"assigned_by_platform_user_id"`
	CreatedAt                time.Time   `json:"created_at"`
	UpdatedAt                time.Time   `json:"updated_at"`
}

type Payment struct {
	ID                  int64              `json:"id"`
	SessionID           uuid.UUID          `json:"session_id"`
	OrderID             pgtype.UUID        `json:"order_id"`
	Amount              pgtype.Numeric     `json:"amount"`
	Method              PaymentMethod      `json:"method"`
	Status              PaymentStatus      `json:"status"`
	InitiatedAt         time.Time          `json:"initiated_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
	Subtotal            pgtype.Numeric     `json:"subtotal"`
	TaxAmount           pgtype.Numeric     `json:"tax_amount"`
	ServiceCharge       pgtype.Numeric     `json:"service_charge"`
	TipAmount           pgtype.Numeric     `json:"tip_amount"`
	BillSnapshotID      pgtype.Int8        `json:"bill_snapshot_id"`
	BranchID            int64              `json:"branch_id"`
	Currency            string             `json:"currency"`
	Provider            pgtype.Text        `json:"provider"`
	ProviderPaymentRef  pgtype.Text        `json:"provider_payment_ref"`
	ProviderOrderRef    pgtype.Text        `json:"provider_order_ref"`
	SettledByStaffID    pgtype.Int8        `json:"settled_by_staff_id"`
	SettledAt           pgtype.Timestamptz `json:"settled_at"`
	PaymentBusinessDate pgtype.Date        `json:"payment_business_date"`
	PaymentSequence     int32              `json:"payment_sequence"`
	PaymentReference    string             `json:"payment_reference"`
}

type PaymentSequence struct {
	BranchID int64       `json:"branch_id"`
	Date     pgtype.Date `json:"date"`
	LastSeq  int32       `json:"last_seq"`
}

type PaymentWebhookEvent struct {
	ID              int64              `json:"id"`
	ExternalEventID string             `json:"external_event_id"`
	Provider        string             `json:"provider"`
	EventType       string             `json:"event_type"`
	Payload         json.RawMessage    `json:"payload"`
	Processed       bool               `json:"processed"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
	PaymentID       pgtype.Int8        `json:"payment_id"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	CreatedAt       time.Time          `json:"created_at"`
	RawPayload      pgtype.Text        `json:"raw_payload"`
	Headers         json.RawMessage    `json:"headers"`
}

type PlanEntitlement struct {
	PlanID         int64       `json:"plan_id"`
	EntitlementKey string      `json:"entitlement_key"`
	Enabled        bool        `json:"enabled"`
	LimitValue     pgtype.Int8 `json:"limit_value"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type PlatformAuditLog struct {
	ID               int64           `json:"id"`
	PlatformUserID   pgtype.Int8     `json:"platform_user_id"`
	Action           string          `json:"action"`
	TargetType       string          `json:"target_type"`
	TargetID         string          `json:"target_id"`
	OrganizationID   pgtype.Int8     `json:"organization_id"`
	BranchID         pgtype.Int8     `json:"branch_id"`
	SupportSessionID pgtype.Int8     `json:"support_session_id"`
	RequestID        string          `json:"request_id"`
	Payload          json.RawMessage `json:"payload"`
	CreatedAt        time.Time       `json:"created_at"`
}

type PlatformFeatureFlag struct {
	Key            string    `json:"key"`
	Name           string    `json:"name"`
	Description    string    `json:"description"`
	DefaultEnabled bool      `json:"default_enabled"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type PlatformFlagBranchOverride struct {
	BranchID                int64       `json:"branch_id"`
	FlagKey                 string      `json:"flag_key"`
	Enabled                 bool        `json:"enabled"`
	Reason                  string      `json:"reason"`
	UpdatedByPlatformUserID pgtype.Int8 `json:"updated_by_platform_user_id"`
	CreatedAt               time.Time   `json:"created_at"`
	UpdatedAt               time.Time   `json:"updated_at"`
}

type PlatformFlagGlobalOverride struct {
	FlagKey                 string      `json:"flag_key"`
	Enabled                 bool        `json:"enabled"`
	UpdatedByPlatformUserID pgtype.Int8 `json:"updated_by_platform_user_id"`
	CreatedAt               time.Time   `json:"created_at"`
	UpdatedAt               time.Time   `json:"updated_at"`
}

type PlatformFlagOrganizationOverride struct {
	OrganizationID          int64       `json:"organization_id"`
	FlagKey                 string      `json:"flag_key"`
	Enabled                 bool        `json:"enabled"`
	Reason                  string      `json:"reason"`
	UpdatedByPlatformUserID pgtype.Int8 `json:"updated_by_platform_user_id"`
	CreatedAt               time.Time   `json:"created_at"`
	UpdatedAt               time.Time   `json:"updated_at"`
}

type PlatformMfaChallenge struct {
	ID             uuid.UUID          `json:"id"`
	PlatformUserID int64              `json:"platform_user_id"`
	ChallengeHash  string             `json:"challenge_hash"`
	IssuedAt       time.Time          `json:"issued_at"`
	ExpiresAt      time.Time          `json:"expires_at"`
	ConsumedAt     pgtype.Timestamptz `json:"consumed_at"`
	Ip             *netip.Addr        `json:"ip"`
	UserAgent      pgtype.Text        `json:"user_agent"`
}

type PlatformSession struct {
	ID             uuid.UUID          `json:"id"`
	PlatformUserID int64              `json:"platform_user_id"`
	TokenHash      string             `json:"token_hash"`
	DeviceName     string             `json:"device_name"`
	CreatedAt      time.Time          `json:"created_at"`
	LastSeenAt     time.Time          `json:"last_seen_at"`
	ExpiresAt      time.Time          `json:"expires_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
}

type PlatformSupportSession struct {
	ID                       int64       `json:"id"`
	PlatformUserID           int64       `json:"platform_user_id"`
	OrganizationID           int64       `json:"organization_id"`
	BranchID                 pgtype.Int8 `json:"branch_id"`
	Reason                   string      `json:"reason"`
	ApprovedByPlatformUserID pgtype.Int8 `json:"approved_by_platform_user_id"`
	StartsAt                 time.Time   `json:"starts_at"`
	ExpiresAt                time.Time   `json:"expires_at"`
	CreatedAt                time.Time   `json:"created_at"`
}

type PlatformUser struct {
	ID           int64     `json:"id"`
	Email        string    `json:"email"`
	DisplayName  string    `json:"display_name"`
	PasswordHash string    `json:"password_hash"`
	Status       string    `json:"status"`
	MfaRequired  bool      `json:"mfa_required"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type PlatformUserMfa struct {
	PlatformUserID  int64              `json:"platform_user_id"`
	SecretEncrypted string             `json:"secret_encrypted"`
	Status          string             `json:"status"`
	RecoveryCodes   json.RawMessage    `json:"recovery_codes"`
	EnrolledAt      pgtype.Timestamptz `json:"enrolled_at"`
	LastUsedAt      pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
}

type PlatformUserRole struct {
	PlatformUserID int64     `json:"platform_user_id"`
	Role           string    `json:"role"`
	CreatedAt      time.Time `json:"created_at"`
}

type Promo struct {
	ID              int64          `json:"id"`
	BranchID        int64          `json:"branch_id"`
	Code            string         `json:"code"`
	Type            PromoType      `json:"type"`
	Value           pgtype.Numeric `json:"value"`
	MinOrderAmount  pgtype.Numeric `json:"min_order_amount"`
	MaxUses         pgtype.Int4    `json:"max_uses"`
	UsesPerPhone    int32          `json:"uses_per_phone"`
	ValidFrom       time.Time      `json:"valid_from"`
	ValidUntil      time.Time      `json:"valid_until"`
	TimeWindowStart pgtype.Time    `json:"time_window_start"`
	TimeWindowEnd   pgtype.Time    `json:"time_window_end"`
	IsActive        bool           `json:"is_active"`
	Description     pgtype.Text    `json:"description"`
	CreatedBy       pgtype.Int8    `json:"created_by"`
	CreatedAt       time.Time      `json:"created_at"`
	RedeemedCount   int32          `json:"redeemed_count"`
}

type PromoRedemption struct {
	ID         int64       `json:"id"`
	PromoID    int64       `json:"promo_id"`
	OrderID    uuid.UUID   `json:"order_id"`
	PhoneE164  pgtype.Text `json:"phone_e164"`
	RedeemedAt time.Time   `json:"redeemed_at"`
}

type Restaurant struct {
	ID             int64           `json:"id"`
	Name           string          `json:"name"`
	Slug           string          `json:"slug"`
	SettingsJson   json.RawMessage `json:"settings_json"`
	CreatedAt      time.Time       `json:"created_at"`
	LogoUrl        pgtype.Text     `json:"logo_url"`
	OrganizationID int64           `json:"organization_id"`
}

type RestaurantSubscription struct {
	ID                 int64              `json:"id"`
	RestaurantID       int64              `json:"restaurant_id"`
	PlanID             int64              `json:"plan_id"`
	Status             string             `json:"status"`
	TrialEndsAt        pgtype.Timestamptz `json:"trial_ends_at"`
	CurrentPeriodStart time.Time          `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
}

type Session struct {
	ID                     uuid.UUID          `json:"id"`
	BranchID               int64              `json:"branch_id"`
	TableID                int64              `json:"table_id"`
	HostParticipantID      pgtype.Int8        `json:"host_participant_id"`
	Status                 SessionStatus      `json:"status"`
	SessionToken           string             `json:"session_token"`
	CreatedAt              time.Time          `json:"created_at"`
	ClosedAt               pgtype.Timestamptz `json:"closed_at"`
	WarnedAt               pgtype.Timestamptz `json:"warned_at"`
	CustomerID             pgtype.Int8        `json:"customer_id"`
	SessionBusinessDate    pgtype.Date        `json:"session_business_date"`
	VisitNumber            int32              `json:"visit_number"`
	SessionNumber          string             `json:"session_number"`
	AwaitingReactivationAt pgtype.Timestamptz `json:"awaiting_reactivation_at"`
}

type SessionEvent struct {
	ID             uuid.UUID       `json:"id"`
	Sequence       int64           `json:"sequence"`
	OrganizationID int64           `json:"organization_id"`
	BranchID       int64           `json:"branch_id"`
	SessionID      uuid.UUID       `json:"session_id"`
	Event          string          `json:"event"`
	Payload        json.RawMessage `json:"payload"`
	CreatedAt      time.Time       `json:"created_at"`
}

type SessionParticipant struct {
	ID                int64              `json:"id"`
	SessionID         uuid.UUID          `json:"session_id"`
	DisplayName       string             `json:"display_name"`
	DeviceFingerprint string             `json:"device_fingerprint"`
	JoinedAt          time.Time          `json:"joined_at"`
	LastSeenAt        time.Time          `json:"last_seen_at"`
	IsHost            bool               `json:"is_host"`
	CredentialVersion int32              `json:"credential_version"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason     pgtype.Text        `json:"revoked_reason"`
	PhoneE164         pgtype.Text        `json:"phone_e164"`
}

type SessionSequence struct {
	BranchID int64       `json:"branch_id"`
	Date     pgtype.Date `json:"date"`
	LastSeq  int32       `json:"last_seq"`
}

type Staff struct {
	ID           int64     `json:"id"`
	BranchID     int64     `json:"branch_id"`
	Name         string    `json:"name"`
	Role         StaffRole `json:"role"`
	PinHash      string    `json:"pin_hash"`
	CreatedAt    time.Time `json:"created_at"`
	IsActive     bool      `json:"is_active"`
	StaffCode    string    `json:"staff_code"`
	TokenVersion int32     `json:"token_version"`
	PinVersion   int32     `json:"pin_version"`
}

type StaffSession struct {
	ID           uuid.UUID          `json:"id"`
	StaffID      int64              `json:"staff_id"`
	BranchID     int64              `json:"branch_id"`
	TokenHash    string             `json:"token_hash"`
	DeviceName   string             `json:"device_name"`
	TokenVersion int32              `json:"token_version"`
	PinVersion   int32              `json:"pin_version"`
	CreatedAt    time.Time          `json:"created_at"`
	LastSeenAt   time.Time          `json:"last_seen_at"`
	ExpiresAt    time.Time          `json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
}

type SubscriptionPlan struct {
	ID           int64           `json:"id"`
	Name         string          `json:"name"`
	Tier         PlanTier        `json:"tier"`
	PriceMonthly pgtype.Numeric  `json:"price_monthly"`
	FeaturesJson json.RawMessage `json:"features_json"`
	CreatedAt    time.Time       `json:"created_at"`
}

type Table struct {
	ID          int64       `json:"id"`
	BranchID    int64       `json:"branch_id"`
	Identifier  string      `json:"identifier"`
	Capacity    int16       `json:"capacity"`
	QrCodeToken string      `json:"qr_code_token"`
	Status      TableStatus `json:"status"`
	CreatedAt   time.Time   `json:"created_at"`
}

type TenantTheme struct {
	RestaurantID            int64           `json:"restaurant_id"`
	Preset                  string          `json:"preset"`
	TokensJson              json.RawMessage `json:"tokens_json"`
	UpdatedByPlatformUserID pgtype.Int8     `json:"updated_by_platform_user_id"`
	CreatedAt               time.Time       `json:"created_at"`
	UpdatedAt               time.Time       `json:"updated_at"`
}

type ThemePreset struct {
	Key         string    `json:"key"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}
