// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
  session_id,
  branch_id,
  placed_by_participant_id,
  idempotency_key,
  total_amount,
  order_number,
  promo_id,
  discount_amount,
  order_business_date,
  order_number_display,
  order_operational_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, session_id, branch_id, placed_by_participant_id, status, idempotency_key, total_amount, created_at, updated_at, order_number, promo_id, discount_amount, order_business_date, order_number_display, order_operational_id
`

type CreateOrderParams struct {
	SessionID             uuid.UUID      `json:"session_id"`
	BranchID              int64          `json:"branch_id"`
	PlacedByParticipantID pgtype.Int8    `json:"placed_by_participant_id"`
	IdempotencyKey        string         `json:"idempotency_key"`
	TotalAmount           pgtype.Numeric `json:"total_amount"`
	OrderNumber           pgtype.Text    `json:"order_number"`
	PromoID               pgtype.Int8    `json:"promo_id"`
	DiscountAmount        pgtype.Numeric `json:"discount_amount"`
	OrderBusinessDate     pgtype.Date    `json:"order_business_date"`
	OrderNumberDisplay    string         `json:"order_number_display"`
	OrderOperationalID    string         `json:"order_operational_id"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.SessionID,
		arg.BranchID,
		arg.PlacedByParticipantID,
		arg.IdempotencyKey,
		arg.TotalAmount,
		arg.OrderNumber,
		arg.PromoID,
		arg.DiscountAmount,
		arg.OrderBusinessDate,
		arg.OrderNumberDisplay,
		arg.OrderOperationalID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.BranchID,
		&i.PlacedByParticipantID,
		&i.Status,
		&i.IdempotencyKey,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderNumber,
		&i.PromoID,
		&i.DiscountAmount,
		&i.OrderBusinessDate,
		&i.OrderNumberDisplay,
		&i.OrderOperationalID,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, menu_item_id, quantity, unit_price, selected_modifiers_json, note)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, order_id, menu_item_id, quantity, unit_price, selected_modifiers_json, note
`

type CreateOrderItemParams struct {
	OrderID               uuid.UUID       `json:"order_id"`
	MenuItemID            int64           `json:"menu_item_id"`
	Quantity              int16           `json:"quantity"`
	UnitPrice             pgtype.Numeric  `json:"unit_price"`
	SelectedModifiersJson json.RawMessage `json:"selected_modifiers_json"`
	Note                  string          `json:"note"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.MenuItemID,
		arg.Quantity,
		arg.UnitPrice,
		arg.SelectedModifiersJson,
		arg.Note,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.MenuItemID,
		&i.Quantity,
		&i.UnitPrice,
		&i.SelectedModifiersJson,
		&i.Note,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, session_id, branch_id, placed_by_participant_id, status, idempotency_key, total_amount, created_at, updated_at, order_number, promo_id, discount_amount, order_business_date, order_number_display, order_operational_id FROM orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.BranchID,
		&i.PlacedByParticipantID,
		&i.Status,
		&i.IdempotencyKey,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderNumber,
		&i.PromoID,
		&i.DiscountAmount,
		&i.OrderBusinessDate,
		&i.OrderNumberDisplay,
		&i.OrderOperationalID,
	)
	return i, err
}

const getOrderByIdempotencyKey = `-- name: GetOrderByIdempotencyKey :one
SELECT id, session_id, branch_id, placed_by_participant_id, status, idempotency_key, total_amount, created_at, updated_at, order_number, promo_id, discount_amount, order_business_date, order_number_display, order_operational_id FROM orders WHERE idempotency_key = $1
`

func (q *Queries) GetOrderByIdempotencyKey(ctx context.Context, idempotencyKey string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByIdempotencyKey, idempotencyKey)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.BranchID,
		&i.PlacedByParticipantID,
		&i.Status,
		&i.IdempotencyKey,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderNumber,
		&i.PromoID,
		&i.DiscountAmount,
		&i.OrderBusinessDate,
		&i.OrderNumberDisplay,
		&i.OrderOperationalID,
	)
	return i, err
}

const getOrderByScopedIdempotencyKey = `-- name: GetOrderByScopedIdempotencyKey :one
SELECT id, session_id, branch_id, placed_by_participant_id, status, idempotency_key, total_amount, created_at, updated_at, order_number, promo_id, discount_amount, order_business_date, order_number_display, order_operational_id FROM orders
WHERE session_id = $1
  AND placed_by_participant_id = $2
  AND idempotency_key = $3
`

type GetOrderByScopedIdempotencyKeyParams struct {
	SessionID             uuid.UUID   `json:"session_id"`
	PlacedByParticipantID pgtype.Int8 `json:"placed_by_participant_id"`
	IdempotencyKey        string      `json:"idempotency_key"`
}

func (q *Queries) GetOrderByScopedIdempotencyKey(ctx context.Context, arg GetOrderByScopedIdempotencyKeyParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByScopedIdempotencyKey, arg.SessionID, arg.PlacedByParticipantID, arg.IdempotencyKey)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.BranchID,
		&i.PlacedByParticipantID,
		&i.Status,
		&i.IdempotencyKey,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderNumber,
		&i.PromoID,
		&i.DiscountAmount,
		&i.OrderBusinessDate,
		&i.OrderNumberDisplay,
		&i.OrderOperationalID,
	)
	return i, err
}

const listActiveOrdersForBranch = `-- name: ListActiveOrdersForBranch :many
SELECT
    o.id, o.session_id, o.branch_id, o.placed_by_participant_id, o.status, o.idempotency_key, o.total_amount, o.created_at, o.updated_at, o.order_number, o.promo_id, o.discount_amount, o.order_business_date, o.order_number_display, o.order_operational_id,
    t.identifier AS table_identifier
FROM orders o
JOIN sessions s ON s.id = o.session_id
JOIN tables t ON t.id = s.table_id
WHERE o.branch_id = $1
  AND o.status IN ('pending', 'confirmed', 'preparing', 'ready')
ORDER BY o.created_at ASC
`

type ListActiveOrdersForBranchRow struct {
	ID                    uuid.UUID      `json:"id"`
	SessionID             uuid.UUID      `json:"session_id"`
	BranchID              int64          `json:"branch_id"`
	PlacedByParticipantID pgtype.Int8    `json:"placed_by_participant_id"`
	Status                OrderStatus    `json:"status"`
	IdempotencyKey        string         `json:"idempotency_key"`
	TotalAmount           pgtype.Numeric `json:"total_amount"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	OrderNumber           pgtype.Text    `json:"order_number"`
	PromoID               pgtype.Int8    `json:"promo_id"`
	DiscountAmount        pgtype.Numeric `json:"discount_amount"`
	OrderBusinessDate     pgtype.Date    `json:"order_business_date"`
	OrderNumberDisplay    string         `json:"order_number_display"`
	OrderOperationalID    string         `json:"order_operational_id"`
	TableIdentifier       string         `json:"table_identifier"`
}

func (q *Queries) ListActiveOrdersForBranch(ctx context.Context, branchID int64) ([]ListActiveOrdersForBranchRow, error) {
	rows, err := q.db.Query(ctx, listActiveOrdersForBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveOrdersForBranchRow{}
	for rows.Next() {
		var i ListActiveOrdersForBranchRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.BranchID,
			&i.PlacedByParticipantID,
			&i.Status,
			&i.IdempotencyKey,
			&i.TotalAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrderNumber,
			&i.PromoID,
			&i.DiscountAmount,
			&i.OrderBusinessDate,
			&i.OrderNumberDisplay,
			&i.OrderOperationalID,
			&i.TableIdentifier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, menu_item_id, quantity, unit_price, selected_modifiers_json, note FROM order_items WHERE order_id = $1 ORDER BY id ASC
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.MenuItemID,
			&i.Quantity,
			&i.UnitPrice,
			&i.SelectedModifiersJson,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersForSession = `-- name: ListOrdersForSession :many
SELECT id, session_id, branch_id, placed_by_participant_id, status, idempotency_key, total_amount, created_at, updated_at, order_number, promo_id, discount_amount, order_business_date, order_number_display, order_operational_id FROM orders
WHERE session_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersForSession(ctx context.Context, sessionID uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.BranchID,
			&i.PlacedByParticipantID,
			&i.Status,
			&i.IdempotencyKey,
			&i.TotalAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrderNumber,
			&i.PromoID,
			&i.DiscountAmount,
			&i.OrderBusinessDate,
			&i.OrderNumberDisplay,
			&i.OrderOperationalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextOrderNumber = `-- name: NextOrderNumber :one
INSERT INTO order_sequences (branch_id, date, last_seq)
VALUES ($1, $2, 1001)
ON CONFLICT (branch_id, date)
DO UPDATE SET last_seq = order_sequences.last_seq + 1
RETURNING last_seq
`

type NextOrderNumberParams struct {
	BranchID int64       `json:"branch_id"`
	Date     pgtype.Date `json:"date"`
}

func (q *Queries) NextOrderNumber(ctx context.Context, arg NextOrderNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextOrderNumber, arg.BranchID, arg.Date)
	var last_seq int32
	err := row.Scan(&last_seq)
	return last_seq, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, session_id, branch_id, placed_by_participant_id, status, idempotency_key, total_amount, created_at, updated_at, order_number, promo_id, discount_amount, order_business_date, order_number_display, order_operational_id
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID   `json:"id"`
	Status OrderStatus `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.BranchID,
		&i.PlacedByParticipantID,
		&i.Status,
		&i.IdempotencyKey,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderNumber,
		&i.PromoID,
		&i.DiscountAmount,
		&i.OrderBusinessDate,
		&i.OrderNumberDisplay,
		&i.OrderOperationalID,
	)
	return i, err
}

const updateOrderStatusExpected = `-- name: UpdateOrderStatusExpected :one
UPDATE orders
SET status = $4, updated_at = NOW()
WHERE id = $1 AND branch_id = $2 AND status = $3
RETURNING id, session_id, branch_id, placed_by_participant_id, status, idempotency_key, total_amount, created_at, updated_at, order_number, promo_id, discount_amount, order_business_date, order_number_display, order_operational_id
`

type UpdateOrderStatusExpectedParams struct {
	ID       uuid.UUID   `json:"id"`
	BranchID int64       `json:"branch_id"`
	Status   OrderStatus `json:"status"`
	Status_2 OrderStatus `json:"status_2"`
}

func (q *Queries) UpdateOrderStatusExpected(ctx context.Context, arg UpdateOrderStatusExpectedParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatusExpected,
		arg.ID,
		arg.BranchID,
		arg.Status,
		arg.Status_2,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.BranchID,
		&i.PlacedByParticipantID,
		&i.Status,
		&i.IdempotencyKey,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderNumber,
		&i.PromoID,
		&i.DiscountAmount,
		&i.OrderBusinessDate,
		&i.OrderNumberDisplay,
		&i.OrderOperationalID,
	)
	return i, err
}

const updateOrderStatusScoped = `-- name: UpdateOrderStatusScoped :one
UPDATE orders
SET status = $3, updated_at = NOW()
WHERE id = $1 AND branch_id = $2
RETURNING id, session_id, branch_id, placed_by_participant_id, status, idempotency_key, total_amount, created_at, updated_at, order_number, promo_id, discount_amount, order_business_date, order_number_display, order_operational_id
`

type UpdateOrderStatusScopedParams struct {
	ID       uuid.UUID   `json:"id"`
	BranchID int64       `json:"branch_id"`
	Status   OrderStatus `json:"status"`
}

func (q *Queries) UpdateOrderStatusScoped(ctx context.Context, arg UpdateOrderStatusScopedParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatusScoped, arg.ID, arg.BranchID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.BranchID,
		&i.PlacedByParticipantID,
		&i.Status,
		&i.IdempotencyKey,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderNumber,
		&i.PromoID,
		&i.DiscountAmount,
		&i.OrderBusinessDate,
		&i.OrderNumberDisplay,
		&i.OrderOperationalID,
	)
	return i, err
}
