// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const getOrganizationByBranchID = `-- name: GetOrganizationByBranchID :one
SELECT o.id, o.code, o.name, o.legal_name, o.status, o.primary_contact_email, o.settings_json, o.created_at, o.updated_at
FROM organizations o
JOIN branches b ON b.organization_id = o.id
WHERE b.id = $1
`

func (q *Queries) GetOrganizationByBranchID(ctx context.Context, id int64) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByBranchID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.LegalName,
		&i.Status,
		&i.PrimaryContactEmail,
		&i.SettingsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByCode = `-- name: GetOrganizationByCode :one
SELECT id, code, name, legal_name, status, primary_contact_email, settings_json, created_at, updated_at FROM organizations WHERE code = $1
`

func (q *Queries) GetOrganizationByCode(ctx context.Context, code string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByCode, code)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.LegalName,
		&i.Status,
		&i.PrimaryContactEmail,
		&i.SettingsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, code, name, legal_name, status, primary_contact_email, settings_json, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id int64) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.LegalName,
		&i.Status,
		&i.PrimaryContactEmail,
		&i.SettingsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByRestaurantID = `-- name: GetOrganizationByRestaurantID :one
SELECT o.id, o.code, o.name, o.legal_name, o.status, o.primary_contact_email, o.settings_json, o.created_at, o.updated_at
FROM organizations o
JOIN restaurants r ON r.organization_id = o.id
WHERE r.id = $1
`

func (q *Queries) GetOrganizationByRestaurantID(ctx context.Context, id int64) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByRestaurantID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.LegalName,
		&i.Status,
		&i.PrimaryContactEmail,
		&i.SettingsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationMembershipForStaff = `-- name: GetOrganizationMembershipForStaff :one
SELECT id, organization_id, staff_id, role, status, invited_by_staff_id, created_at, updated_at FROM organization_members
WHERE organization_id = $1
  AND staff_id = $2
  AND status = 'active'
`

type GetOrganizationMembershipForStaffParams struct {
	OrganizationID int64 `json:"organization_id"`
	StaffID        int64 `json:"staff_id"`
}

func (q *Queries) GetOrganizationMembershipForStaff(ctx context.Context, arg GetOrganizationMembershipForStaffParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getOrganizationMembershipForStaff, arg.OrganizationID, arg.StaffID)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StaffID,
		&i.Role,
		&i.Status,
		&i.InvitedByStaffID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRestaurantByOrganizationID = `-- name: GetRestaurantByOrganizationID :one
SELECT id, name, slug, settings_json, created_at, logo_url, organization_id FROM restaurants WHERE organization_id = $1
`

func (q *Queries) GetRestaurantByOrganizationID(ctx context.Context, organizationID int64) (Restaurant, error) {
	row := q.db.QueryRow(ctx, getRestaurantByOrganizationID, organizationID)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SettingsJson,
		&i.CreatedAt,
		&i.LogoUrl,
		&i.OrganizationID,
	)
	return i, err
}

const listBranchesForOrganization = `-- name: ListBranchesForOrganization :many
SELECT id, restaurant_id, name, address, timezone, created_at, session_timeout_minutes, order_prefix, branch_code, organization_id, status, support_metadata_json
FROM branches
WHERE organization_id = $1
ORDER BY name ASC, id ASC
`

func (q *Queries) ListBranchesForOrganization(ctx context.Context, organizationID int64) ([]Branch, error) {
	rows, err := q.db.Query(ctx, listBranchesForOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Branch{}
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.Name,
			&i.Address,
			&i.Timezone,
			&i.CreatedAt,
			&i.SessionTimeoutMinutes,
			&i.OrderPrefix,
			&i.BranchCode,
			&i.OrganizationID,
			&i.Status,
			&i.SupportMetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBranchStatus = `-- name: UpdateBranchStatus :one
UPDATE branches
SET status = $2
WHERE id = $1
RETURNING id, restaurant_id, name, address, timezone, created_at, session_timeout_minutes, order_prefix, branch_code, organization_id, status, support_metadata_json
`

type UpdateBranchStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateBranchStatus(ctx context.Context, arg UpdateBranchStatusParams) (Branch, error) {
	row := q.db.QueryRow(ctx, updateBranchStatus, arg.ID, arg.Status)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Name,
		&i.Address,
		&i.Timezone,
		&i.CreatedAt,
		&i.SessionTimeoutMinutes,
		&i.OrderPrefix,
		&i.BranchCode,
		&i.OrganizationID,
		&i.Status,
		&i.SupportMetadataJson,
	)
	return i, err
}

const updateOrganizationSettings = `-- name: UpdateOrganizationSettings :one
UPDATE organizations
SET
    name = $2,
    legal_name = $3,
    primary_contact_email = $4,
    settings_json = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, code, name, legal_name, status, primary_contact_email, settings_json, created_at, updated_at
`

type UpdateOrganizationSettingsParams struct {
	ID                  int64           `json:"id"`
	Name                string          `json:"name"`
	LegalName           string          `json:"legal_name"`
	PrimaryContactEmail string          `json:"primary_contact_email"`
	SettingsJson        json.RawMessage `json:"settings_json"`
}

func (q *Queries) UpdateOrganizationSettings(ctx context.Context, arg UpdateOrganizationSettingsParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationSettings,
		arg.ID,
		arg.Name,
		arg.LegalName,
		arg.PrimaryContactEmail,
		arg.SettingsJson,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.LegalName,
		&i.Status,
		&i.PrimaryContactEmail,
		&i.SettingsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrganizationStatus = `-- name: UpdateOrganizationStatus :one
UPDATE organizations
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, code, name, legal_name, status, primary_contact_email, settings_json, created_at, updated_at
`

type UpdateOrganizationStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateOrganizationStatus(ctx context.Context, arg UpdateOrganizationStatusParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationStatus, arg.ID, arg.Status)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.LegalName,
		&i.Status,
		&i.PrimaryContactEmail,
		&i.SettingsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
