// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: participants.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createParticipant = `-- name: CreateParticipant :one
INSERT INTO session_participants (session_id, display_name, device_fingerprint, is_host)
VALUES ($1, $2, $3, $4)
RETURNING id, session_id, display_name, device_fingerprint, joined_at, last_seen_at, is_host, credential_version, revoked_at, revoked_reason
`

type CreateParticipantParams struct {
	SessionID         uuid.UUID `json:"session_id"`
	DisplayName       string    `json:"display_name"`
	DeviceFingerprint string    `json:"device_fingerprint"`
	IsHost            bool      `json:"is_host"`
}

func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) (SessionParticipant, error) {
	row := q.db.QueryRow(ctx, createParticipant,
		arg.SessionID,
		arg.DisplayName,
		arg.DeviceFingerprint,
		arg.IsHost,
	)
	var i SessionParticipant
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DisplayName,
		&i.DeviceFingerprint,
		&i.JoinedAt,
		&i.LastSeenAt,
		&i.IsHost,
		&i.CredentialVersion,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const getParticipantByID = `-- name: GetParticipantByID :one
SELECT id, session_id, display_name, device_fingerprint, joined_at, last_seen_at, is_host, credential_version, revoked_at, revoked_reason FROM session_participants WHERE id = $1
`

func (q *Queries) GetParticipantByID(ctx context.Context, id int64) (SessionParticipant, error) {
	row := q.db.QueryRow(ctx, getParticipantByID, id)
	var i SessionParticipant
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.DisplayName,
		&i.DeviceFingerprint,
		&i.JoinedAt,
		&i.LastSeenAt,
		&i.IsHost,
		&i.CredentialVersion,
		&i.RevokedAt,
		&i.RevokedReason,
	)
	return i, err
}

const listParticipantsBySession = `-- name: ListParticipantsBySession :many
SELECT id, session_id, display_name, device_fingerprint, joined_at, last_seen_at, is_host, credential_version, revoked_at, revoked_reason FROM session_participants
WHERE session_id = $1
ORDER BY joined_at ASC
`

func (q *Queries) ListParticipantsBySession(ctx context.Context, sessionID uuid.UUID) ([]SessionParticipant, error) {
	rows, err := q.db.Query(ctx, listParticipantsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionParticipant{}
	for rows.Next() {
		var i SessionParticipant
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.DisplayName,
			&i.DeviceFingerprint,
			&i.JoinedAt,
			&i.LastSeenAt,
			&i.IsHost,
			&i.CredentialVersion,
			&i.RevokedAt,
			&i.RevokedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateParticipantLastSeen = `-- name: UpdateParticipantLastSeen :exec
UPDATE session_participants
SET last_seen_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateParticipantLastSeen(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateParticipantLastSeen, id)
	return err
}
