// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (session_id, order_id, amount, method)
VALUES ($1, $2, $3, $4)
RETURNING id, session_id, order_id, amount, method, status, initiated_at, completed_at, subtotal, tax_amount, service_charge, tip_amount
`

type CreatePaymentParams struct {
	SessionID uuid.UUID      `json:"session_id"`
	OrderID   pgtype.UUID    `json:"order_id"`
	Amount    pgtype.Numeric `json:"amount"`
	Method    PaymentMethod  `json:"method"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.SessionID,
		arg.OrderID,
		arg.Amount,
		arg.Method,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.OrderID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.InitiatedAt,
		&i.CompletedAt,
		&i.Subtotal,
		&i.TaxAmount,
		&i.ServiceCharge,
		&i.TipAmount,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, session_id, order_id, amount, method, status, initiated_at, completed_at, subtotal, tax_amount, service_charge, tip_amount FROM payments WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.OrderID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.InitiatedAt,
		&i.CompletedAt,
		&i.Subtotal,
		&i.TaxAmount,
		&i.ServiceCharge,
		&i.TipAmount,
	)
	return i, err
}

const insertWebhookEvent = `-- name: InsertWebhookEvent :one
INSERT INTO payment_webhook_events (external_event_id, provider, event_type, payload)
VALUES ($1, $2, $3, $4)
ON CONFLICT (external_event_id) DO NOTHING
RETURNING id, external_event_id, provider, event_type, payload, processed, processed_at, payment_id, error_message, created_at
`

type InsertWebhookEventParams struct {
	ExternalEventID string          `json:"external_event_id"`
	Provider        string          `json:"provider"`
	EventType       string          `json:"event_type"`
	Payload         json.RawMessage `json:"payload"`
}

func (q *Queries) InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (PaymentWebhookEvent, error) {
	row := q.db.QueryRow(ctx, insertWebhookEvent,
		arg.ExternalEventID,
		arg.Provider,
		arg.EventType,
		arg.Payload,
	)
	var i PaymentWebhookEvent
	err := row.Scan(
		&i.ID,
		&i.ExternalEventID,
		&i.Provider,
		&i.EventType,
		&i.Payload,
		&i.Processed,
		&i.ProcessedAt,
		&i.PaymentID,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listPaymentsForSession = `-- name: ListPaymentsForSession :many
SELECT id, session_id, order_id, amount, method, status, initiated_at, completed_at, subtotal, tax_amount, service_charge, tip_amount FROM payments WHERE session_id = $1 ORDER BY initiated_at DESC
`

func (q *Queries) ListPaymentsForSession(ctx context.Context, sessionID uuid.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.OrderID,
			&i.Amount,
			&i.Method,
			&i.Status,
			&i.InitiatedAt,
			&i.CompletedAt,
			&i.Subtotal,
			&i.TaxAmount,
			&i.ServiceCharge,
			&i.TipAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnprocessedWebhooks = `-- name: ListUnprocessedWebhooks :many
SELECT id, external_event_id, provider, event_type, payload, processed, processed_at, payment_id, error_message, created_at FROM payment_webhook_events
WHERE processed = FALSE
ORDER BY created_at ASC
LIMIT 50
`

func (q *Queries) ListUnprocessedWebhooks(ctx context.Context) ([]PaymentWebhookEvent, error) {
	rows, err := q.db.Query(ctx, listUnprocessedWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentWebhookEvent{}
	for rows.Next() {
		var i PaymentWebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.ExternalEventID,
			&i.Provider,
			&i.EventType,
			&i.Payload,
			&i.Processed,
			&i.ProcessedAt,
			&i.PaymentID,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookProcessed = `-- name: MarkWebhookProcessed :exec
UPDATE payment_webhook_events
SET processed = TRUE, processed_at = NOW(), payment_id = $2, error_message = $3
WHERE id = $1
`

type MarkWebhookProcessedParams struct {
	ID           int64       `json:"id"`
	PaymentID    pgtype.Int8 `json:"payment_id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) MarkWebhookProcessed(ctx context.Context, arg MarkWebhookProcessedParams) error {
	_, err := q.db.Exec(ctx, markWebhookProcessed, arg.ID, arg.PaymentID, arg.ErrorMessage)
	return err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status = $2,
    completed_at = CASE WHEN $2::payment_status = 'completed' THEN NOW() ELSE completed_at END
WHERE id = $1
RETURNING id, session_id, order_id, amount, method, status, initiated_at, completed_at, subtotal, tax_amount, service_charge, tip_amount
`

type UpdatePaymentStatusParams struct {
	ID     int64         `json:"id"`
	Status PaymentStatus `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.ID, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.OrderID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.InitiatedAt,
		&i.CompletedAt,
		&i.Subtotal,
		&i.TaxAmount,
		&i.ServiceCharge,
		&i.TipAmount,
	)
	return i, err
}
