// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBillSnapshot = `-- name: CreateBillSnapshot :one
INSERT INTO bill_snapshots (
  session_id,
  branch_id,
  subtotal,
  discount_amount,
  tax_amount,
  service_charge,
  tip_amount,
  total,
  currency,
  source_order_ids,
  created_by_actor
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, session_id, branch_id, subtotal, discount_amount, tax_amount, service_charge, tip_amount, total, currency, source_order_ids, created_by_actor, created_at
`

type CreateBillSnapshotParams struct {
	SessionID      uuid.UUID       `json:"session_id"`
	BranchID       int64           `json:"branch_id"`
	Subtotal       pgtype.Numeric  `json:"subtotal"`
	DiscountAmount pgtype.Numeric  `json:"discount_amount"`
	TaxAmount      pgtype.Numeric  `json:"tax_amount"`
	ServiceCharge  pgtype.Numeric  `json:"service_charge"`
	TipAmount      pgtype.Numeric  `json:"tip_amount"`
	Total          pgtype.Numeric  `json:"total"`
	Currency       string          `json:"currency"`
	SourceOrderIds json.RawMessage `json:"source_order_ids"`
	CreatedByActor string          `json:"created_by_actor"`
}

func (q *Queries) CreateBillSnapshot(ctx context.Context, arg CreateBillSnapshotParams) (BillSnapshot, error) {
	row := q.db.QueryRow(ctx, createBillSnapshot,
		arg.SessionID,
		arg.BranchID,
		arg.Subtotal,
		arg.DiscountAmount,
		arg.TaxAmount,
		arg.ServiceCharge,
		arg.TipAmount,
		arg.Total,
		arg.Currency,
		arg.SourceOrderIds,
		arg.CreatedByActor,
	)
	var i BillSnapshot
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.BranchID,
		&i.Subtotal,
		&i.DiscountAmount,
		&i.TaxAmount,
		&i.ServiceCharge,
		&i.TipAmount,
		&i.Total,
		&i.Currency,
		&i.SourceOrderIds,
		&i.CreatedByActor,
		&i.CreatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
  session_id,
  order_id,
  amount,
  method,
  status,
  bill_snapshot_id,
  branch_id,
  currency,
  provider,
  provider_payment_ref,
  provider_order_ref,
  payment_business_date,
  payment_sequence,
  payment_reference
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, session_id, order_id, amount, method, status, initiated_at, completed_at, subtotal, tax_amount, service_charge, tip_amount, bill_snapshot_id, branch_id, currency, provider, provider_payment_ref, provider_order_ref, settled_by_staff_id, settled_at, payment_business_date, payment_sequence, payment_reference
`

type CreatePaymentParams struct {
	SessionID           uuid.UUID      `json:"session_id"`
	OrderID             pgtype.UUID    `json:"order_id"`
	Amount              pgtype.Numeric `json:"amount"`
	Method              PaymentMethod  `json:"method"`
	Status              PaymentStatus  `json:"status"`
	BillSnapshotID      pgtype.Int8    `json:"bill_snapshot_id"`
	BranchID            int64          `json:"branch_id"`
	Currency            string         `json:"currency"`
	Provider            pgtype.Text    `json:"provider"`
	ProviderPaymentRef  pgtype.Text    `json:"provider_payment_ref"`
	ProviderOrderRef    pgtype.Text    `json:"provider_order_ref"`
	PaymentBusinessDate pgtype.Date    `json:"payment_business_date"`
	PaymentSequence     int32          `json:"payment_sequence"`
	PaymentReference    string         `json:"payment_reference"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.SessionID,
		arg.OrderID,
		arg.Amount,
		arg.Method,
		arg.Status,
		arg.BillSnapshotID,
		arg.BranchID,
		arg.Currency,
		arg.Provider,
		arg.ProviderPaymentRef,
		arg.ProviderOrderRef,
		arg.PaymentBusinessDate,
		arg.PaymentSequence,
		arg.PaymentReference,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.OrderID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.InitiatedAt,
		&i.CompletedAt,
		&i.Subtotal,
		&i.TaxAmount,
		&i.ServiceCharge,
		&i.TipAmount,
		&i.BillSnapshotID,
		&i.BranchID,
		&i.Currency,
		&i.Provider,
		&i.ProviderPaymentRef,
		&i.ProviderOrderRef,
		&i.SettledByStaffID,
		&i.SettledAt,
		&i.PaymentBusinessDate,
		&i.PaymentSequence,
		&i.PaymentReference,
	)
	return i, err
}

const getBillSnapshotByID = `-- name: GetBillSnapshotByID :one
SELECT id, session_id, branch_id, subtotal, discount_amount, tax_amount, service_charge, tip_amount, total, currency, source_order_ids, created_by_actor, created_at FROM bill_snapshots WHERE id = $1
`

func (q *Queries) GetBillSnapshotByID(ctx context.Context, id int64) (BillSnapshot, error) {
	row := q.db.QueryRow(ctx, getBillSnapshotByID, id)
	var i BillSnapshot
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.BranchID,
		&i.Subtotal,
		&i.DiscountAmount,
		&i.TaxAmount,
		&i.ServiceCharge,
		&i.TipAmount,
		&i.Total,
		&i.Currency,
		&i.SourceOrderIds,
		&i.CreatedByActor,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, session_id, order_id, amount, method, status, initiated_at, completed_at, subtotal, tax_amount, service_charge, tip_amount, bill_snapshot_id, branch_id, currency, provider, provider_payment_ref, provider_order_ref, settled_by_staff_id, settled_at, payment_business_date, payment_sequence, payment_reference FROM payments WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.OrderID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.InitiatedAt,
		&i.CompletedAt,
		&i.Subtotal,
		&i.TaxAmount,
		&i.ServiceCharge,
		&i.TipAmount,
		&i.BillSnapshotID,
		&i.BranchID,
		&i.Currency,
		&i.Provider,
		&i.ProviderPaymentRef,
		&i.ProviderOrderRef,
		&i.SettledByStaffID,
		&i.SettledAt,
		&i.PaymentBusinessDate,
		&i.PaymentSequence,
		&i.PaymentReference,
	)
	return i, err
}

const getPaymentByProviderRef = `-- name: GetPaymentByProviderRef :one
SELECT id, session_id, order_id, amount, method, status, initiated_at, completed_at, subtotal, tax_amount, service_charge, tip_amount, bill_snapshot_id, branch_id, currency, provider, provider_payment_ref, provider_order_ref, settled_by_staff_id, settled_at, payment_business_date, payment_sequence, payment_reference FROM payments
WHERE provider = $1 AND provider_payment_ref = $2
`

type GetPaymentByProviderRefParams struct {
	Provider           pgtype.Text `json:"provider"`
	ProviderPaymentRef pgtype.Text `json:"provider_payment_ref"`
}

func (q *Queries) GetPaymentByProviderRef(ctx context.Context, arg GetPaymentByProviderRefParams) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByProviderRef, arg.Provider, arg.ProviderPaymentRef)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.OrderID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.InitiatedAt,
		&i.CompletedAt,
		&i.Subtotal,
		&i.TaxAmount,
		&i.ServiceCharge,
		&i.TipAmount,
		&i.BillSnapshotID,
		&i.BranchID,
		&i.Currency,
		&i.Provider,
		&i.ProviderPaymentRef,
		&i.ProviderOrderRef,
		&i.SettledByStaffID,
		&i.SettledAt,
		&i.PaymentBusinessDate,
		&i.PaymentSequence,
		&i.PaymentReference,
	)
	return i, err
}

const insertWebhookEvent = `-- name: InsertWebhookEvent :one
INSERT INTO payment_webhook_events (external_event_id, provider, event_type, payload, raw_payload, headers)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (external_event_id) DO NOTHING
RETURNING id, external_event_id, provider, event_type, payload, processed, processed_at, payment_id, error_message, created_at, raw_payload, headers
`

type InsertWebhookEventParams struct {
	ExternalEventID string          `json:"external_event_id"`
	Provider        string          `json:"provider"`
	EventType       string          `json:"event_type"`
	Payload         json.RawMessage `json:"payload"`
	RawPayload      pgtype.Text     `json:"raw_payload"`
	Headers         json.RawMessage `json:"headers"`
}

func (q *Queries) InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (PaymentWebhookEvent, error) {
	row := q.db.QueryRow(ctx, insertWebhookEvent,
		arg.ExternalEventID,
		arg.Provider,
		arg.EventType,
		arg.Payload,
		arg.RawPayload,
		arg.Headers,
	)
	var i PaymentWebhookEvent
	err := row.Scan(
		&i.ID,
		&i.ExternalEventID,
		&i.Provider,
		&i.EventType,
		&i.Payload,
		&i.Processed,
		&i.ProcessedAt,
		&i.PaymentID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.RawPayload,
		&i.Headers,
	)
	return i, err
}

const listPaymentsForBranchByStatus = `-- name: ListPaymentsForBranchByStatus :many
SELECT
    p.id, p.session_id, p.order_id, p.amount, p.method, p.status, p.initiated_at, p.completed_at, p.subtotal, p.tax_amount, p.service_charge, p.tip_amount, p.bill_snapshot_id, p.branch_id, p.currency, p.provider, p.provider_payment_ref, p.provider_order_ref, p.settled_by_staff_id, p.settled_at, p.payment_business_date, p.payment_sequence, p.payment_reference,
    t.identifier AS table_identifier,
    s.session_number AS session_number
FROM payments p
JOIN sessions s ON s.id = p.session_id
JOIN tables t ON t.id = s.table_id
WHERE p.branch_id = $1 AND p.status = $2
ORDER BY p.initiated_at ASC
`

type ListPaymentsForBranchByStatusParams struct {
	BranchID int64         `json:"branch_id"`
	Status   PaymentStatus `json:"status"`
}

type ListPaymentsForBranchByStatusRow struct {
	ID                  int64              `json:"id"`
	SessionID           uuid.UUID          `json:"session_id"`
	OrderID             pgtype.UUID        `json:"order_id"`
	Amount              pgtype.Numeric     `json:"amount"`
	Method              PaymentMethod      `json:"method"`
	Status              PaymentStatus      `json:"status"`
	InitiatedAt         time.Time          `json:"initiated_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
	Subtotal            pgtype.Numeric     `json:"subtotal"`
	TaxAmount           pgtype.Numeric     `json:"tax_amount"`
	ServiceCharge       pgtype.Numeric     `json:"service_charge"`
	TipAmount           pgtype.Numeric     `json:"tip_amount"`
	BillSnapshotID      pgtype.Int8        `json:"bill_snapshot_id"`
	BranchID            int64              `json:"branch_id"`
	Currency            string             `json:"currency"`
	Provider            pgtype.Text        `json:"provider"`
	ProviderPaymentRef  pgtype.Text        `json:"provider_payment_ref"`
	ProviderOrderRef    pgtype.Text        `json:"provider_order_ref"`
	SettledByStaffID    pgtype.Int8        `json:"settled_by_staff_id"`
	SettledAt           pgtype.Timestamptz `json:"settled_at"`
	PaymentBusinessDate pgtype.Date        `json:"payment_business_date"`
	PaymentSequence     int32              `json:"payment_sequence"`
	PaymentReference    string             `json:"payment_reference"`
	TableIdentifier     string             `json:"table_identifier"`
	SessionNumber       string             `json:"session_number"`
}

func (q *Queries) ListPaymentsForBranchByStatus(ctx context.Context, arg ListPaymentsForBranchByStatusParams) ([]ListPaymentsForBranchByStatusRow, error) {
	rows, err := q.db.Query(ctx, listPaymentsForBranchByStatus, arg.BranchID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentsForBranchByStatusRow{}
	for rows.Next() {
		var i ListPaymentsForBranchByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.OrderID,
			&i.Amount,
			&i.Method,
			&i.Status,
			&i.InitiatedAt,
			&i.CompletedAt,
			&i.Subtotal,
			&i.TaxAmount,
			&i.ServiceCharge,
			&i.TipAmount,
			&i.BillSnapshotID,
			&i.BranchID,
			&i.Currency,
			&i.Provider,
			&i.ProviderPaymentRef,
			&i.ProviderOrderRef,
			&i.SettledByStaffID,
			&i.SettledAt,
			&i.PaymentBusinessDate,
			&i.PaymentSequence,
			&i.PaymentReference,
			&i.TableIdentifier,
			&i.SessionNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsForSession = `-- name: ListPaymentsForSession :many
SELECT id, session_id, order_id, amount, method, status, initiated_at, completed_at, subtotal, tax_amount, service_charge, tip_amount, bill_snapshot_id, branch_id, currency, provider, provider_payment_ref, provider_order_ref, settled_by_staff_id, settled_at, payment_business_date, payment_sequence, payment_reference FROM payments WHERE session_id = $1 ORDER BY initiated_at DESC
`

func (q *Queries) ListPaymentsForSession(ctx context.Context, sessionID uuid.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.OrderID,
			&i.Amount,
			&i.Method,
			&i.Status,
			&i.InitiatedAt,
			&i.CompletedAt,
			&i.Subtotal,
			&i.TaxAmount,
			&i.ServiceCharge,
			&i.TipAmount,
			&i.BillSnapshotID,
			&i.BranchID,
			&i.Currency,
			&i.Provider,
			&i.ProviderPaymentRef,
			&i.ProviderOrderRef,
			&i.SettledByStaffID,
			&i.SettledAt,
			&i.PaymentBusinessDate,
			&i.PaymentSequence,
			&i.PaymentReference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnprocessedWebhooks = `-- name: ListUnprocessedWebhooks :many
SELECT id, external_event_id, provider, event_type, payload, processed, processed_at, payment_id, error_message, created_at, raw_payload, headers FROM payment_webhook_events
WHERE processed = FALSE
ORDER BY created_at ASC
LIMIT 50
`

func (q *Queries) ListUnprocessedWebhooks(ctx context.Context) ([]PaymentWebhookEvent, error) {
	rows, err := q.db.Query(ctx, listUnprocessedWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentWebhookEvent{}
	for rows.Next() {
		var i PaymentWebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.ExternalEventID,
			&i.Provider,
			&i.EventType,
			&i.Payload,
			&i.Processed,
			&i.ProcessedAt,
			&i.PaymentID,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.RawPayload,
			&i.Headers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookProcessed = `-- name: MarkWebhookProcessed :exec
UPDATE payment_webhook_events
SET processed = TRUE, processed_at = NOW(), payment_id = $2, error_message = $3
WHERE id = $1
`

type MarkWebhookProcessedParams struct {
	ID           int64       `json:"id"`
	PaymentID    pgtype.Int8 `json:"payment_id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) MarkWebhookProcessed(ctx context.Context, arg MarkWebhookProcessedParams) error {
	_, err := q.db.Exec(ctx, markWebhookProcessed, arg.ID, arg.PaymentID, arg.ErrorMessage)
	return err
}

const nextPaymentNumber = `-- name: NextPaymentNumber :one
INSERT INTO payment_sequences (branch_id, date, last_seq)
VALUES ($1, $2, 1)
ON CONFLICT (branch_id, date)
DO UPDATE SET last_seq = payment_sequences.last_seq + 1
RETURNING last_seq
`

type NextPaymentNumberParams struct {
	BranchID int64       `json:"branch_id"`
	Date     pgtype.Date `json:"date"`
}

func (q *Queries) NextPaymentNumber(ctx context.Context, arg NextPaymentNumberParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextPaymentNumber, arg.BranchID, arg.Date)
	var last_seq int32
	err := row.Scan(&last_seq)
	return last_seq, err
}

const settlePaymentByStaff = `-- name: SettlePaymentByStaff :one
UPDATE payments
SET status = 'completed',
    settled_by_staff_id = $2,
    settled_at = NOW(),
    completed_at = NOW()
WHERE id = $1
  AND branch_id = $3
  AND status = 'requires_staff_confirmation'
RETURNING id, session_id, order_id, amount, method, status, initiated_at, completed_at, subtotal, tax_amount, service_charge, tip_amount, bill_snapshot_id, branch_id, currency, provider, provider_payment_ref, provider_order_ref, settled_by_staff_id, settled_at, payment_business_date, payment_sequence, payment_reference
`

type SettlePaymentByStaffParams struct {
	ID               int64       `json:"id"`
	SettledByStaffID pgtype.Int8 `json:"settled_by_staff_id"`
	BranchID         int64       `json:"branch_id"`
}

func (q *Queries) SettlePaymentByStaff(ctx context.Context, arg SettlePaymentByStaffParams) (Payment, error) {
	row := q.db.QueryRow(ctx, settlePaymentByStaff, arg.ID, arg.SettledByStaffID, arg.BranchID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.OrderID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.InitiatedAt,
		&i.CompletedAt,
		&i.Subtotal,
		&i.TaxAmount,
		&i.ServiceCharge,
		&i.TipAmount,
		&i.BillSnapshotID,
		&i.BranchID,
		&i.Currency,
		&i.Provider,
		&i.ProviderPaymentRef,
		&i.ProviderOrderRef,
		&i.SettledByStaffID,
		&i.SettledAt,
		&i.PaymentBusinessDate,
		&i.PaymentSequence,
		&i.PaymentReference,
	)
	return i, err
}

const sumCompletedPaymentsForSession = `-- name: SumCompletedPaymentsForSession :one
SELECT COALESCE(SUM(amount), 0)::numeric
FROM payments
WHERE session_id = $1
  AND status = 'completed'
`

func (q *Queries) SumCompletedPaymentsForSession(ctx context.Context, sessionID uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, sumCompletedPaymentsForSession, sessionID)
	var column_1 pgtype.Numeric
	err := row.Scan(&column_1)
	return column_1, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status = $2,
    completed_at = CASE WHEN $2::payment_status = 'completed' THEN NOW() ELSE completed_at END
WHERE id = $1
RETURNING id, session_id, order_id, amount, method, status, initiated_at, completed_at, subtotal, tax_amount, service_charge, tip_amount, bill_snapshot_id, branch_id, currency, provider, provider_payment_ref, provider_order_ref, settled_by_staff_id, settled_at, payment_business_date, payment_sequence, payment_reference
`

type UpdatePaymentStatusParams struct {
	ID     int64         `json:"id"`
	Status PaymentStatus `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.ID, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.OrderID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.InitiatedAt,
		&i.CompletedAt,
		&i.Subtotal,
		&i.TaxAmount,
		&i.ServiceCharge,
		&i.TipAmount,
		&i.BillSnapshotID,
		&i.BranchID,
		&i.Currency,
		&i.Provider,
		&i.ProviderPaymentRef,
		&i.ProviderOrderRef,
		&i.SettledByStaffID,
		&i.SettledAt,
		&i.PaymentBusinessDate,
		&i.PaymentSequence,
		&i.PaymentReference,
	)
	return i, err
}

const updatePaymentStatusExpected = `-- name: UpdatePaymentStatusExpected :one
UPDATE payments
SET status = $3,
    completed_at = CASE WHEN $3::payment_status = 'completed' THEN NOW() ELSE completed_at END
WHERE id = $1 AND status = $2
RETURNING id, session_id, order_id, amount, method, status, initiated_at, completed_at, subtotal, tax_amount, service_charge, tip_amount, bill_snapshot_id, branch_id, currency, provider, provider_payment_ref, provider_order_ref, settled_by_staff_id, settled_at, payment_business_date, payment_sequence, payment_reference
`

type UpdatePaymentStatusExpectedParams struct {
	ID       int64         `json:"id"`
	Status   PaymentStatus `json:"status"`
	Status_2 PaymentStatus `json:"status_2"`
}

func (q *Queries) UpdatePaymentStatusExpected(ctx context.Context, arg UpdatePaymentStatusExpectedParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatusExpected, arg.ID, arg.Status, arg.Status_2)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.OrderID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.InitiatedAt,
		&i.CompletedAt,
		&i.Subtotal,
		&i.TaxAmount,
		&i.ServiceCharge,
		&i.TipAmount,
		&i.BillSnapshotID,
		&i.BranchID,
		&i.Currency,
		&i.Provider,
		&i.ProviderPaymentRef,
		&i.ProviderOrderRef,
		&i.SettledByStaffID,
		&i.SettledAt,
		&i.PaymentBusinessDate,
		&i.PaymentSequence,
		&i.PaymentReference,
	)
	return i, err
}
