// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_mfa.sql

package sqlc

import (
	"context"
	"encoding/json"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const activatePlatformMFA = `-- name: ActivatePlatformMFA :one
UPDATE platform_user_mfa
SET status = 'active',
    recovery_codes = $2,
    enrolled_at = NOW(),
    last_used_at = NOW(),
    updated_at = NOW()
WHERE platform_user_id = $1 AND status = 'pending'
RETURNING platform_user_id, secret_encrypted, status, recovery_codes, enrolled_at, last_used_at, created_at, updated_at
`

type ActivatePlatformMFAParams struct {
	PlatformUserID int64           `json:"platform_user_id"`
	RecoveryCodes  json.RawMessage `json:"recovery_codes"`
}

func (q *Queries) ActivatePlatformMFA(ctx context.Context, arg ActivatePlatformMFAParams) (PlatformUserMfa, error) {
	row := q.db.QueryRow(ctx, activatePlatformMFA, arg.PlatformUserID, arg.RecoveryCodes)
	var i PlatformUserMfa
	err := row.Scan(
		&i.PlatformUserID,
		&i.SecretEncrypted,
		&i.Status,
		&i.RecoveryCodes,
		&i.EnrolledAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const consumePlatformMFAChallenge = `-- name: ConsumePlatformMFAChallenge :exec
UPDATE platform_mfa_challenges
SET consumed_at = NOW()
WHERE challenge_hash = $1 AND consumed_at IS NULL
`

func (q *Queries) ConsumePlatformMFAChallenge(ctx context.Context, challengeHash string) error {
	_, err := q.db.Exec(ctx, consumePlatformMFAChallenge, challengeHash)
	return err
}

const consumeRecoveryCodes = `-- name: ConsumeRecoveryCodes :exec
UPDATE platform_user_mfa
SET recovery_codes = $2,
    last_used_at = NOW(),
    updated_at = NOW()
WHERE platform_user_id = $1
`

type ConsumeRecoveryCodesParams struct {
	PlatformUserID int64           `json:"platform_user_id"`
	RecoveryCodes  json.RawMessage `json:"recovery_codes"`
}

func (q *Queries) ConsumeRecoveryCodes(ctx context.Context, arg ConsumeRecoveryCodesParams) error {
	_, err := q.db.Exec(ctx, consumeRecoveryCodes, arg.PlatformUserID, arg.RecoveryCodes)
	return err
}

const createPlatformMFAChallenge = `-- name: CreatePlatformMFAChallenge :one
INSERT INTO platform_mfa_challenges (platform_user_id, challenge_hash, expires_at, ip, user_agent)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, platform_user_id, challenge_hash, issued_at, expires_at, consumed_at, ip, user_agent
`

type CreatePlatformMFAChallengeParams struct {
	PlatformUserID int64       `json:"platform_user_id"`
	ChallengeHash  string      `json:"challenge_hash"`
	ExpiresAt      time.Time   `json:"expires_at"`
	Ip             *netip.Addr `json:"ip"`
	UserAgent      pgtype.Text `json:"user_agent"`
}

func (q *Queries) CreatePlatformMFAChallenge(ctx context.Context, arg CreatePlatformMFAChallengeParams) (PlatformMfaChallenge, error) {
	row := q.db.QueryRow(ctx, createPlatformMFAChallenge,
		arg.PlatformUserID,
		arg.ChallengeHash,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var i PlatformMfaChallenge
	err := row.Scan(
		&i.ID,
		&i.PlatformUserID,
		&i.ChallengeHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.Ip,
		&i.UserAgent,
	)
	return i, err
}

const disablePlatformMFA = `-- name: DisablePlatformMFA :exec
UPDATE platform_user_mfa
SET status = 'disabled',
    recovery_codes = '[]'::jsonb,
    updated_at = NOW()
WHERE platform_user_id = $1
`

func (q *Queries) DisablePlatformMFA(ctx context.Context, platformUserID int64) error {
	_, err := q.db.Exec(ctx, disablePlatformMFA, platformUserID)
	return err
}

const getPlatformMFA = `-- name: GetPlatformMFA :one
SELECT platform_user_id, secret_encrypted, status, recovery_codes, enrolled_at, last_used_at, created_at, updated_at FROM platform_user_mfa WHERE platform_user_id = $1
`

func (q *Queries) GetPlatformMFA(ctx context.Context, platformUserID int64) (PlatformUserMfa, error) {
	row := q.db.QueryRow(ctx, getPlatformMFA, platformUserID)
	var i PlatformUserMfa
	err := row.Scan(
		&i.PlatformUserID,
		&i.SecretEncrypted,
		&i.Status,
		&i.RecoveryCodes,
		&i.EnrolledAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformMFAChallengeByHash = `-- name: GetPlatformMFAChallengeByHash :one
SELECT id, platform_user_id, challenge_hash, issued_at, expires_at, consumed_at, ip, user_agent FROM platform_mfa_challenges
WHERE challenge_hash = $1
  AND consumed_at IS NULL
  AND expires_at > NOW()
`

func (q *Queries) GetPlatformMFAChallengeByHash(ctx context.Context, challengeHash string) (PlatformMfaChallenge, error) {
	row := q.db.QueryRow(ctx, getPlatformMFAChallengeByHash, challengeHash)
	var i PlatformMfaChallenge
	err := row.Scan(
		&i.ID,
		&i.PlatformUserID,
		&i.ChallengeHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.Ip,
		&i.UserAgent,
	)
	return i, err
}

const touchPlatformMFAUse = `-- name: TouchPlatformMFAUse :exec
UPDATE platform_user_mfa
SET last_used_at = NOW(),
    updated_at = NOW()
WHERE platform_user_id = $1
`

func (q *Queries) TouchPlatformMFAUse(ctx context.Context, platformUserID int64) error {
	_, err := q.db.Exec(ctx, touchPlatformMFAUse, platformUserID)
	return err
}

const upsertPlatformMFAPending = `-- name: UpsertPlatformMFAPending :one
INSERT INTO platform_user_mfa (platform_user_id, secret_encrypted, status, recovery_codes)
VALUES ($1, $2, 'pending', '[]'::jsonb)
ON CONFLICT (platform_user_id) DO UPDATE
SET secret_encrypted = EXCLUDED.secret_encrypted,
    status = 'pending',
    recovery_codes = '[]'::jsonb,
    updated_at = NOW()
RETURNING platform_user_id, secret_encrypted, status, recovery_codes, enrolled_at, last_used_at, created_at, updated_at
`

type UpsertPlatformMFAPendingParams struct {
	PlatformUserID  int64  `json:"platform_user_id"`
	SecretEncrypted string `json:"secret_encrypted"`
}

func (q *Queries) UpsertPlatformMFAPending(ctx context.Context, arg UpsertPlatformMFAPendingParams) (PlatformUserMfa, error) {
	row := q.db.QueryRow(ctx, upsertPlatformMFAPending, arg.PlatformUserID, arg.SecretEncrypted)
	var i PlatformUserMfa
	err := row.Scan(
		&i.PlatformUserID,
		&i.SecretEncrypted,
		&i.Status,
		&i.RecoveryCodes,
		&i.EnrolledAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
