// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_analytics.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const platformActiveBranches = `-- name: PlatformActiveBranches :one
SELECT COUNT(DISTINCT b.id)::BIGINT AS count
FROM branches b
WHERE ($1::bigint IS NULL OR b.organization_id = $1)
  AND EXISTS (
    SELECT 1 FROM sessions s
    WHERE s.branch_id = b.id
      AND s.created_at >= $2::timestamptz AND s.created_at < $3::timestamptz
  )
`

type PlatformActiveBranchesParams struct {
	OrganizationID pgtype.Int8 `json:"organization_id"`
	FromTime       time.Time   `json:"from_time"`
	ToTime         time.Time   `json:"to_time"`
}

func (q *Queries) PlatformActiveBranches(ctx context.Context, arg PlatformActiveBranchesParams) (int64, error) {
	row := q.db.QueryRow(ctx, platformActiveBranches, arg.OrganizationID, arg.FromTime, arg.ToTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const platformActiveDiners = `-- name: PlatformActiveDiners :one
SELECT COUNT(*)::BIGINT AS count
FROM session_participants sp
JOIN sessions s ON s.id = sp.session_id
JOIN branches b ON b.id = s.branch_id
WHERE ($1::bigint IS NULL OR b.organization_id = $1)
  AND sp.revoked_at IS NULL
  AND s.status IN ('active', 'payment_pending', 'awaiting_reactivation')
`

func (q *Queries) PlatformActiveDiners(ctx context.Context, organizationID pgtype.Int8) (int64, error) {
	row := q.db.QueryRow(ctx, platformActiveDiners, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const platformAuthzDenialsPerDay = `-- name: PlatformAuthzDenialsPerDay :many
SELECT DATE(created_at AT TIME ZONE 'UTC') AS day, COUNT(*)::BIGINT AS count
FROM audit_log
WHERE ($1::bigint IS NULL OR organization_id = $1)
  AND result = 'denied'
  AND created_at >= $2::timestamptz AND created_at < $3::timestamptz
GROUP BY day
ORDER BY day
`

type PlatformAuthzDenialsPerDayParams struct {
	OrganizationID pgtype.Int8 `json:"organization_id"`
	FromTime       time.Time   `json:"from_time"`
	ToTime         time.Time   `json:"to_time"`
}

type PlatformAuthzDenialsPerDayRow struct {
	Day   pgtype.Date `json:"day"`
	Count int64       `json:"count"`
}

func (q *Queries) PlatformAuthzDenialsPerDay(ctx context.Context, arg PlatformAuthzDenialsPerDayParams) ([]PlatformAuthzDenialsPerDayRow, error) {
	rows, err := q.db.Query(ctx, platformAuthzDenialsPerDay, arg.OrganizationID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformAuthzDenialsPerDayRow{}
	for rows.Next() {
		var i PlatformAuthzDenialsPerDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformGMV = `-- name: PlatformGMV :one
SELECT COALESCE(SUM(p.amount), 0)::TEXT AS gmv
FROM payments p
JOIN branches b ON b.id = p.branch_id
WHERE ($1::bigint IS NULL OR b.organization_id = $1)
  AND p.completed_at >= $2::timestamptz AND p.completed_at < $3::timestamptz
  AND p.status IN ('completed', 'partially_refunded')
`

type PlatformGMVParams struct {
	OrganizationID pgtype.Int8 `json:"organization_id"`
	FromTime       time.Time   `json:"from_time"`
	ToTime         time.Time   `json:"to_time"`
}

func (q *Queries) PlatformGMV(ctx context.Context, arg PlatformGMVParams) (string, error) {
	row := q.db.QueryRow(ctx, platformGMV, arg.OrganizationID, arg.FromTime, arg.ToTime)
	var gmv string
	err := row.Scan(&gmv)
	return gmv, err
}

const platformOrdersPerDay = `-- name: PlatformOrdersPerDay :many
SELECT DATE(o.created_at AT TIME ZONE 'UTC') AS day, COUNT(*)::BIGINT AS count
FROM orders o
JOIN branches b ON b.id = o.branch_id
WHERE ($1::bigint IS NULL OR b.organization_id = $1)
  AND o.created_at >= $2::timestamptz AND o.created_at < $3::timestamptz
  AND o.status <> 'cancelled'
GROUP BY day
ORDER BY day
`

type PlatformOrdersPerDayParams struct {
	OrganizationID pgtype.Int8 `json:"organization_id"`
	FromTime       time.Time   `json:"from_time"`
	ToTime         time.Time   `json:"to_time"`
}

type PlatformOrdersPerDayRow struct {
	Day   pgtype.Date `json:"day"`
	Count int64       `json:"count"`
}

func (q *Queries) PlatformOrdersPerDay(ctx context.Context, arg PlatformOrdersPerDayParams) ([]PlatformOrdersPerDayRow, error) {
	rows, err := q.db.Query(ctx, platformOrdersPerDay, arg.OrganizationID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformOrdersPerDayRow{}
	for rows.Next() {
		var i PlatformOrdersPerDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformParticipantJoinsPerDay = `-- name: PlatformParticipantJoinsPerDay :many
SELECT DATE(sp.joined_at AT TIME ZONE 'UTC') AS day, COUNT(*)::BIGINT AS count
FROM session_participants sp
JOIN sessions s ON s.id = sp.session_id
JOIN branches b ON b.id = s.branch_id
WHERE ($1::bigint IS NULL OR b.organization_id = $1)
  AND sp.joined_at >= $2::timestamptz AND sp.joined_at < $3::timestamptz
GROUP BY day
ORDER BY day
`

type PlatformParticipantJoinsPerDayParams struct {
	OrganizationID pgtype.Int8 `json:"organization_id"`
	FromTime       time.Time   `json:"from_time"`
	ToTime         time.Time   `json:"to_time"`
}

type PlatformParticipantJoinsPerDayRow struct {
	Day   pgtype.Date `json:"day"`
	Count int64       `json:"count"`
}

func (q *Queries) PlatformParticipantJoinsPerDay(ctx context.Context, arg PlatformParticipantJoinsPerDayParams) ([]PlatformParticipantJoinsPerDayRow, error) {
	rows, err := q.db.Query(ctx, platformParticipantJoinsPerDay, arg.OrganizationID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformParticipantJoinsPerDayRow{}
	for rows.Next() {
		var i PlatformParticipantJoinsPerDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformPaymentsPerDay = `-- name: PlatformPaymentsPerDay :many
SELECT DATE(p.completed_at AT TIME ZONE 'UTC') AS day, COUNT(*)::BIGINT AS count
FROM payments p
JOIN branches b ON b.id = p.branch_id
WHERE ($1::bigint IS NULL OR b.organization_id = $1)
  AND p.completed_at >= $2::timestamptz AND p.completed_at < $3::timestamptz
  AND p.status IN ('completed', 'partially_refunded')
GROUP BY day
ORDER BY day
`

type PlatformPaymentsPerDayParams struct {
	OrganizationID pgtype.Int8 `json:"organization_id"`
	FromTime       time.Time   `json:"from_time"`
	ToTime         time.Time   `json:"to_time"`
}

type PlatformPaymentsPerDayRow struct {
	Day   pgtype.Date `json:"day"`
	Count int64       `json:"count"`
}

func (q *Queries) PlatformPaymentsPerDay(ctx context.Context, arg PlatformPaymentsPerDayParams) ([]PlatformPaymentsPerDayRow, error) {
	rows, err := q.db.Query(ctx, platformPaymentsPerDay, arg.OrganizationID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformPaymentsPerDayRow{}
	for rows.Next() {
		var i PlatformPaymentsPerDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformRevenueByBranch = `-- name: PlatformRevenueByBranch :many
SELECT b.id AS branch_id, b.name AS branch_name, b.branch_code,
       COUNT(*)::BIGINT AS count,
       COALESCE(SUM(p.amount), 0)::TEXT AS revenue
FROM payments p
JOIN branches b ON b.id = p.branch_id
WHERE ($1::bigint IS NULL OR b.organization_id = $1)
  AND p.completed_at >= $2::timestamptz AND p.completed_at < $3::timestamptz
  AND p.status IN ('completed', 'partially_refunded')
GROUP BY b.id, b.name, b.branch_code
ORDER BY SUM(p.amount) DESC NULLS LAST
LIMIT 100
`

type PlatformRevenueByBranchParams struct {
	OrganizationID pgtype.Int8 `json:"organization_id"`
	FromTime       time.Time   `json:"from_time"`
	ToTime         time.Time   `json:"to_time"`
}

type PlatformRevenueByBranchRow struct {
	BranchID   int64  `json:"branch_id"`
	BranchName string `json:"branch_name"`
	BranchCode string `json:"branch_code"`
	Count      int64  `json:"count"`
	Revenue    string `json:"revenue"`
}

func (q *Queries) PlatformRevenueByBranch(ctx context.Context, arg PlatformRevenueByBranchParams) ([]PlatformRevenueByBranchRow, error) {
	rows, err := q.db.Query(ctx, platformRevenueByBranch, arg.OrganizationID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformRevenueByBranchRow{}
	for rows.Next() {
		var i PlatformRevenueByBranchRow
		if err := rows.Scan(
			&i.BranchID,
			&i.BranchName,
			&i.BranchCode,
			&i.Count,
			&i.Revenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformRevenueByOrg = `-- name: PlatformRevenueByOrg :many
SELECT o.id AS organization_id, o.code AS organization_code,
       COUNT(*)::BIGINT AS count,
       COALESCE(SUM(p.amount), 0)::TEXT AS revenue
FROM payments p
JOIN branches b ON b.id = p.branch_id
JOIN organizations o ON o.id = b.organization_id
WHERE ($1::bigint IS NULL OR b.organization_id = $1)
  AND p.completed_at >= $2::timestamptz AND p.completed_at < $3::timestamptz
  AND p.status IN ('completed', 'partially_refunded')
GROUP BY o.id, o.code
ORDER BY SUM(p.amount) DESC NULLS LAST
LIMIT 100
`

type PlatformRevenueByOrgParams struct {
	OrganizationID pgtype.Int8 `json:"organization_id"`
	FromTime       time.Time   `json:"from_time"`
	ToTime         time.Time   `json:"to_time"`
}

type PlatformRevenueByOrgRow struct {
	OrganizationID   int64  `json:"organization_id"`
	OrganizationCode string `json:"organization_code"`
	Count            int64  `json:"count"`
	Revenue          string `json:"revenue"`
}

func (q *Queries) PlatformRevenueByOrg(ctx context.Context, arg PlatformRevenueByOrgParams) ([]PlatformRevenueByOrgRow, error) {
	rows, err := q.db.Query(ctx, platformRevenueByOrg, arg.OrganizationID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformRevenueByOrgRow{}
	for rows.Next() {
		var i PlatformRevenueByOrgRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.OrganizationCode,
			&i.Count,
			&i.Revenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformRevenuePerDay = `-- name: PlatformRevenuePerDay :many
SELECT DATE(p.completed_at AT TIME ZONE 'UTC') AS day,
       COUNT(*)::BIGINT AS count,
       COALESCE(SUM(p.amount), 0)::TEXT AS revenue
FROM payments p
JOIN branches b ON b.id = p.branch_id
WHERE ($1::bigint IS NULL OR b.organization_id = $1)
  AND p.completed_at >= $2::timestamptz AND p.completed_at < $3::timestamptz
  AND p.status IN ('completed', 'partially_refunded')
GROUP BY day
ORDER BY day
`

type PlatformRevenuePerDayParams struct {
	OrganizationID pgtype.Int8 `json:"organization_id"`
	FromTime       time.Time   `json:"from_time"`
	ToTime         time.Time   `json:"to_time"`
}

type PlatformRevenuePerDayRow struct {
	Day     pgtype.Date `json:"day"`
	Count   int64       `json:"count"`
	Revenue string      `json:"revenue"`
}

func (q *Queries) PlatformRevenuePerDay(ctx context.Context, arg PlatformRevenuePerDayParams) ([]PlatformRevenuePerDayRow, error) {
	rows, err := q.db.Query(ctx, platformRevenuePerDay, arg.OrganizationID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformRevenuePerDayRow{}
	for rows.Next() {
		var i PlatformRevenuePerDayRow
		if err := rows.Scan(&i.Day, &i.Count, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformSessionsPerDay = `-- name: PlatformSessionsPerDay :many

SELECT DATE(s.created_at AT TIME ZONE 'UTC') AS day, COUNT(*)::BIGINT AS count
FROM sessions s
JOIN branches b ON b.id = s.branch_id
WHERE ($1::bigint IS NULL OR b.organization_id = $1)
  AND s.created_at >= $2::timestamptz AND s.created_at < $3::timestamptz
GROUP BY day
ORDER BY day
`

type PlatformSessionsPerDayParams struct {
	OrganizationID pgtype.Int8 `json:"organization_id"`
	FromTime       time.Time   `json:"from_time"`
	ToTime         time.Time   `json:"to_time"`
}

type PlatformSessionsPerDayRow struct {
	Day   pgtype.Date `json:"day"`
	Count int64       `json:"count"`
}

// Platform (cross-tenant) analytics. On-demand aggregation; optional org filter via
// sqlc.narg('organization_id') (NULL = platform-wide). UTC day bucketing for cross-tenant
// consistency. Operator-facing; not entitlement-gated.
func (q *Queries) PlatformSessionsPerDay(ctx context.Context, arg PlatformSessionsPerDayParams) ([]PlatformSessionsPerDayRow, error) {
	rows, err := q.db.Query(ctx, platformSessionsPerDay, arg.OrganizationID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformSessionsPerDayRow{}
	for rows.Next() {
		var i PlatformSessionsPerDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformWebhookFailuresPerDay = `-- name: PlatformWebhookFailuresPerDay :many
SELECT DATE(pwe.created_at AT TIME ZONE 'UTC') AS day, COUNT(*)::BIGINT AS count
FROM payment_webhook_events pwe
LEFT JOIN payments p ON p.id = pwe.payment_id
LEFT JOIN branches b ON b.id = p.branch_id
WHERE ($1::bigint IS NULL OR b.organization_id = $1)
  AND pwe.created_at >= $2::timestamptz AND pwe.created_at < $3::timestamptz
  AND ((pwe.error_message IS NOT NULL AND pwe.error_message <> '') OR pwe.processed = FALSE)
GROUP BY day
ORDER BY day
`

type PlatformWebhookFailuresPerDayParams struct {
	OrganizationID pgtype.Int8 `json:"organization_id"`
	FromTime       time.Time   `json:"from_time"`
	ToTime         time.Time   `json:"to_time"`
}

type PlatformWebhookFailuresPerDayRow struct {
	Day   pgtype.Date `json:"day"`
	Count int64       `json:"count"`
}

func (q *Queries) PlatformWebhookFailuresPerDay(ctx context.Context, arg PlatformWebhookFailuresPerDayParams) ([]PlatformWebhookFailuresPerDayRow, error) {
	rows, err := q.db.Query(ctx, platformWebhookFailuresPerDay, arg.OrganizationID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformWebhookFailuresPerDayRow{}
	for rows.Next() {
		var i PlatformWebhookFailuresPerDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
