// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addPlatformUserRole = `-- name: AddPlatformUserRole :exec
INSERT INTO platform_user_roles (platform_user_id, role)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddPlatformUserRoleParams struct {
	PlatformUserID int64  `json:"platform_user_id"`
	Role           string `json:"role"`
}

func (q *Queries) AddPlatformUserRole(ctx context.Context, arg AddPlatformUserRoleParams) error {
	_, err := q.db.Exec(ctx, addPlatformUserRole, arg.PlatformUserID, arg.Role)
	return err
}

const createOrganizationBranchMembership = `-- name: CreateOrganizationBranchMembership :exec
INSERT INTO organization_branch_memberships (organization_id, branch_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateOrganizationBranchMembershipParams struct {
	OrganizationID int64 `json:"organization_id"`
	BranchID       int64 `json:"branch_id"`
}

func (q *Queries) CreateOrganizationBranchMembership(ctx context.Context, arg CreateOrganizationBranchMembershipParams) error {
	_, err := q.db.Exec(ctx, createOrganizationBranchMembership, arg.OrganizationID, arg.BranchID)
	return err
}

const createOrganizationMember = `-- name: CreateOrganizationMember :one
INSERT INTO organization_members (organization_id, staff_id, role, status)
VALUES ($1, $2, $3, 'active')
RETURNING id, organization_id, staff_id, role, status, invited_by_staff_id, created_at, updated_at
`

type CreateOrganizationMemberParams struct {
	OrganizationID int64  `json:"organization_id"`
	StaffID        int64  `json:"staff_id"`
	Role           string `json:"role"`
}

func (q *Queries) CreateOrganizationMember(ctx context.Context, arg CreateOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, createOrganizationMember, arg.OrganizationID, arg.StaffID, arg.Role)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.StaffID,
		&i.Role,
		&i.Status,
		&i.InvitedByStaffID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPlatformBranch = `-- name: CreatePlatformBranch :one
INSERT INTO branches (restaurant_id, organization_id, name, address, timezone, branch_code, order_prefix)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, restaurant_id, name, address, timezone, created_at, session_timeout_minutes, order_prefix, branch_code, organization_id, status, support_metadata_json
`

type CreatePlatformBranchParams struct {
	RestaurantID   int64  `json:"restaurant_id"`
	OrganizationID int64  `json:"organization_id"`
	Name           string `json:"name"`
	Address        string `json:"address"`
	Timezone       string `json:"timezone"`
	BranchCode     string `json:"branch_code"`
	OrderPrefix    string `json:"order_prefix"`
}

func (q *Queries) CreatePlatformBranch(ctx context.Context, arg CreatePlatformBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, createPlatformBranch,
		arg.RestaurantID,
		arg.OrganizationID,
		arg.Name,
		arg.Address,
		arg.Timezone,
		arg.BranchCode,
		arg.OrderPrefix,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Name,
		&i.Address,
		&i.Timezone,
		&i.CreatedAt,
		&i.SessionTimeoutMinutes,
		&i.OrderPrefix,
		&i.BranchCode,
		&i.OrganizationID,
		&i.Status,
		&i.SupportMetadataJson,
	)
	return i, err
}

const createPlatformOrganization = `-- name: CreatePlatformOrganization :one
INSERT INTO organizations (code, name, legal_name, primary_contact_email, settings_json)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, name, legal_name, status, primary_contact_email, settings_json, created_at, updated_at
`

type CreatePlatformOrganizationParams struct {
	Code                string          `json:"code"`
	Name                string          `json:"name"`
	LegalName           string          `json:"legal_name"`
	PrimaryContactEmail string          `json:"primary_contact_email"`
	SettingsJson        json.RawMessage `json:"settings_json"`
}

func (q *Queries) CreatePlatformOrganization(ctx context.Context, arg CreatePlatformOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createPlatformOrganization,
		arg.Code,
		arg.Name,
		arg.LegalName,
		arg.PrimaryContactEmail,
		arg.SettingsJson,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.LegalName,
		&i.Status,
		&i.PrimaryContactEmail,
		&i.SettingsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPlatformRestaurant = `-- name: CreatePlatformRestaurant :one
INSERT INTO restaurants (name, slug, settings_json, organization_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, settings_json, created_at, logo_url, organization_id
`

type CreatePlatformRestaurantParams struct {
	Name           string          `json:"name"`
	Slug           string          `json:"slug"`
	SettingsJson   json.RawMessage `json:"settings_json"`
	OrganizationID int64           `json:"organization_id"`
}

func (q *Queries) CreatePlatformRestaurant(ctx context.Context, arg CreatePlatformRestaurantParams) (Restaurant, error) {
	row := q.db.QueryRow(ctx, createPlatformRestaurant,
		arg.Name,
		arg.Slug,
		arg.SettingsJson,
		arg.OrganizationID,
	)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SettingsJson,
		&i.CreatedAt,
		&i.LogoUrl,
		&i.OrganizationID,
	)
	return i, err
}

const createPlatformSession = `-- name: CreatePlatformSession :one
INSERT INTO platform_sessions (platform_user_id, token_hash, device_name, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, platform_user_id, token_hash, device_name, created_at, last_seen_at, expires_at, revoked_at
`

type CreatePlatformSessionParams struct {
	PlatformUserID int64     `json:"platform_user_id"`
	TokenHash      string    `json:"token_hash"`
	DeviceName     string    `json:"device_name"`
	ExpiresAt      time.Time `json:"expires_at"`
}

func (q *Queries) CreatePlatformSession(ctx context.Context, arg CreatePlatformSessionParams) (PlatformSession, error) {
	row := q.db.QueryRow(ctx, createPlatformSession,
		arg.PlatformUserID,
		arg.TokenHash,
		arg.DeviceName,
		arg.ExpiresAt,
	)
	var i PlatformSession
	err := row.Scan(
		&i.ID,
		&i.PlatformUserID,
		&i.TokenHash,
		&i.DeviceName,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const createPlatformSupportSession = `-- name: CreatePlatformSupportSession :one
INSERT INTO platform_support_sessions (
    platform_user_id, organization_id, branch_id, reason,
    approved_by_platform_user_id, starts_at, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, platform_user_id, organization_id, branch_id, reason, approved_by_platform_user_id, starts_at, expires_at, created_at
`

type CreatePlatformSupportSessionParams struct {
	PlatformUserID           int64       `json:"platform_user_id"`
	OrganizationID           int64       `json:"organization_id"`
	BranchID                 pgtype.Int8 `json:"branch_id"`
	Reason                   string      `json:"reason"`
	ApprovedByPlatformUserID pgtype.Int8 `json:"approved_by_platform_user_id"`
	StartsAt                 time.Time   `json:"starts_at"`
	ExpiresAt                time.Time   `json:"expires_at"`
}

func (q *Queries) CreatePlatformSupportSession(ctx context.Context, arg CreatePlatformSupportSessionParams) (PlatformSupportSession, error) {
	row := q.db.QueryRow(ctx, createPlatformSupportSession,
		arg.PlatformUserID,
		arg.OrganizationID,
		arg.BranchID,
		arg.Reason,
		arg.ApprovedByPlatformUserID,
		arg.StartsAt,
		arg.ExpiresAt,
	)
	var i PlatformSupportSession
	err := row.Scan(
		&i.ID,
		&i.PlatformUserID,
		&i.OrganizationID,
		&i.BranchID,
		&i.Reason,
		&i.ApprovedByPlatformUserID,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActivePlatformSessionByTokenHash = `-- name: GetActivePlatformSessionByTokenHash :one
SELECT id, platform_user_id, token_hash, device_name, created_at, last_seen_at, expires_at, revoked_at FROM platform_sessions
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

func (q *Queries) GetActivePlatformSessionByTokenHash(ctx context.Context, tokenHash string) (PlatformSession, error) {
	row := q.db.QueryRow(ctx, getActivePlatformSessionByTokenHash, tokenHash)
	var i PlatformSession
	err := row.Scan(
		&i.ID,
		&i.PlatformUserID,
		&i.TokenHash,
		&i.DeviceName,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getPlatformSupportSessionByID = `-- name: GetPlatformSupportSessionByID :one
SELECT id, platform_user_id, organization_id, branch_id, reason, approved_by_platform_user_id, starts_at, expires_at, created_at FROM platform_support_sessions WHERE id = $1
`

func (q *Queries) GetPlatformSupportSessionByID(ctx context.Context, id int64) (PlatformSupportSession, error) {
	row := q.db.QueryRow(ctx, getPlatformSupportSessionByID, id)
	var i PlatformSupportSession
	err := row.Scan(
		&i.ID,
		&i.PlatformUserID,
		&i.OrganizationID,
		&i.BranchID,
		&i.Reason,
		&i.ApprovedByPlatformUserID,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPlatformUserByEmail = `-- name: GetPlatformUserByEmail :one
SELECT id, email, display_name, password_hash, status, mfa_required, created_at, updated_at FROM platform_users WHERE email = $1
`

func (q *Queries) GetPlatformUserByEmail(ctx context.Context, email string) (PlatformUser, error) {
	row := q.db.QueryRow(ctx, getPlatformUserByEmail, email)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.MfaRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformUserByID = `-- name: GetPlatformUserByID :one
SELECT id, email, display_name, password_hash, status, mfa_required, created_at, updated_at FROM platform_users WHERE id = $1
`

func (q *Queries) GetPlatformUserByID(ctx context.Context, id int64) (PlatformUser, error) {
	row := q.db.QueryRow(ctx, getPlatformUserByID, id)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.MfaRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPlatformAuditLog = `-- name: InsertPlatformAuditLog :exec
INSERT INTO platform_audit_log (
    platform_user_id, action, target_type, target_id,
    organization_id, branch_id, support_session_id, request_id, payload
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertPlatformAuditLogParams struct {
	PlatformUserID   pgtype.Int8     `json:"platform_user_id"`
	Action           string          `json:"action"`
	TargetType       string          `json:"target_type"`
	TargetID         string          `json:"target_id"`
	OrganizationID   pgtype.Int8     `json:"organization_id"`
	BranchID         pgtype.Int8     `json:"branch_id"`
	SupportSessionID pgtype.Int8     `json:"support_session_id"`
	RequestID        string          `json:"request_id"`
	Payload          json.RawMessage `json:"payload"`
}

func (q *Queries) InsertPlatformAuditLog(ctx context.Context, arg InsertPlatformAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertPlatformAuditLog,
		arg.PlatformUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.OrganizationID,
		arg.BranchID,
		arg.SupportSessionID,
		arg.RequestID,
		arg.Payload,
	)
	return err
}

const listPlatformAuditLog = `-- name: ListPlatformAuditLog :many
SELECT id, platform_user_id, action, target_type, target_id, organization_id, branch_id, support_session_id, request_id, payload, created_at FROM platform_audit_log
WHERE ($1::BIGINT IS NULL OR platform_user_id = $1)
  AND ($2::TEXT IS NULL OR action = $2)
  AND ($3::TEXT IS NULL OR target_type = $3)
  AND ($4::BIGINT IS NULL OR organization_id = $4)
  AND ($5::BIGINT IS NULL OR branch_id = $5)
  AND ($6::TIMESTAMPTZ IS NULL OR created_at >= $6)
  AND ($7::TIMESTAMPTZ IS NULL OR created_at < $7)
ORDER BY created_at DESC, id DESC
LIMIT 200
`

type ListPlatformAuditLogParams struct {
	PlatformUserID pgtype.Int8        `json:"platform_user_id"`
	Action         pgtype.Text        `json:"action"`
	TargetType     pgtype.Text        `json:"target_type"`
	OrganizationID pgtype.Int8        `json:"organization_id"`
	BranchID       pgtype.Int8        `json:"branch_id"`
	FromTime       pgtype.Timestamptz `json:"from_time"`
	ToTime         pgtype.Timestamptz `json:"to_time"`
}

func (q *Queries) ListPlatformAuditLog(ctx context.Context, arg ListPlatformAuditLogParams) ([]PlatformAuditLog, error) {
	rows, err := q.db.Query(ctx, listPlatformAuditLog,
		arg.PlatformUserID,
		arg.Action,
		arg.TargetType,
		arg.OrganizationID,
		arg.BranchID,
		arg.FromTime,
		arg.ToTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformAuditLog{}
	for rows.Next() {
		var i PlatformAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.PlatformUserID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.OrganizationID,
			&i.BranchID,
			&i.SupportSessionID,
			&i.RequestID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformOrganizations = `-- name: ListPlatformOrganizations :many
SELECT id, code, name, legal_name, status, primary_contact_email, settings_json, created_at, updated_at FROM organizations ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListPlatformOrganizations(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listPlatformOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.LegalName,
			&i.Status,
			&i.PrimaryContactEmail,
			&i.SettingsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformRolesForUser = `-- name: ListPlatformRolesForUser :many
SELECT role FROM platform_user_roles WHERE platform_user_id = $1 ORDER BY role ASC
`

func (q *Queries) ListPlatformRolesForUser(ctx context.Context, platformUserID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listPlatformRolesForUser, platformUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformSupportSessions = `-- name: ListPlatformSupportSessions :many
SELECT id, platform_user_id, organization_id, branch_id, reason, approved_by_platform_user_id, starts_at, expires_at, created_at FROM platform_support_sessions
ORDER BY created_at DESC, id DESC
LIMIT 200
`

func (q *Queries) ListPlatformSupportSessions(ctx context.Context) ([]PlatformSupportSession, error) {
	rows, err := q.db.Query(ctx, listPlatformSupportSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformSupportSession{}
	for rows.Next() {
		var i PlatformSupportSession
		if err := rows.Scan(
			&i.ID,
			&i.PlatformUserID,
			&i.OrganizationID,
			&i.BranchID,
			&i.Reason,
			&i.ApprovedByPlatformUserID,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformUsers = `-- name: ListPlatformUsers :many
SELECT id, email, display_name, password_hash, status, mfa_required, created_at, updated_at FROM platform_users ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListPlatformUsers(ctx context.Context) ([]PlatformUser, error) {
	rows, err := q.db.Query(ctx, listPlatformUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformUser{}
	for rows.Next() {
		var i PlatformUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.PasswordHash,
			&i.Status,
			&i.MfaRequired,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePlatformSession = `-- name: RevokePlatformSession :exec
UPDATE platform_sessions SET revoked_at = NOW()
WHERE id = $1 AND platform_user_id = $2 AND revoked_at IS NULL
`

type RevokePlatformSessionParams struct {
	ID             uuid.UUID `json:"id"`
	PlatformUserID int64     `json:"platform_user_id"`
}

func (q *Queries) RevokePlatformSession(ctx context.Context, arg RevokePlatformSessionParams) error {
	_, err := q.db.Exec(ctx, revokePlatformSession, arg.ID, arg.PlatformUserID)
	return err
}

const touchPlatformSession = `-- name: TouchPlatformSession :exec
UPDATE platform_sessions SET last_seen_at = NOW() WHERE id = $1
`

func (q *Queries) TouchPlatformSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchPlatformSession, id)
	return err
}

const upsertPlatformUser = `-- name: UpsertPlatformUser :one
INSERT INTO platform_users (email, display_name, password_hash, status, mfa_required)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (email) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    password_hash = EXCLUDED.password_hash,
    status = EXCLUDED.status,
    mfa_required = EXCLUDED.mfa_required,
    updated_at = NOW()
RETURNING id, email, display_name, password_hash, status, mfa_required, created_at, updated_at
`

type UpsertPlatformUserParams struct {
	Email        string `json:"email"`
	DisplayName  string `json:"display_name"`
	PasswordHash string `json:"password_hash"`
	Status       string `json:"status"`
	MfaRequired  bool   `json:"mfa_required"`
}

func (q *Queries) UpsertPlatformUser(ctx context.Context, arg UpsertPlatformUserParams) (PlatformUser, error) {
	row := q.db.QueryRow(ctx, upsertPlatformUser,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Status,
		arg.MfaRequired,
	)
	var i PlatformUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.MfaRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
