// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: promos.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPromoRedemptions = `-- name: CountPromoRedemptions :one
SELECT COUNT(*) FROM promo_redemptions WHERE promo_id = $1
`

func (q *Queries) CountPromoRedemptions(ctx context.Context, promoID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPromoRedemptions, promoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPromoRedemptionsByPhone = `-- name: CountPromoRedemptionsByPhone :one
SELECT COUNT(*) FROM promo_redemptions
WHERE promo_id = $1 AND phone_e164 = $2
`

type CountPromoRedemptionsByPhoneParams struct {
	PromoID   int64       `json:"promo_id"`
	PhoneE164 pgtype.Text `json:"phone_e164"`
}

func (q *Queries) CountPromoRedemptionsByPhone(ctx context.Context, arg CountPromoRedemptionsByPhoneParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPromoRedemptionsByPhone, arg.PromoID, arg.PhoneE164)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPromo = `-- name: CreatePromo :one
INSERT INTO promos (
  branch_id, code, type, value, min_order_amount,
  max_uses, uses_per_phone, valid_from, valid_until,
  time_window_start, time_window_end, description, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, branch_id, code, type, value, min_order_amount, max_uses, uses_per_phone, valid_from, valid_until, time_window_start, time_window_end, is_active, description, created_by, created_at, redeemed_count
`

type CreatePromoParams struct {
	BranchID        int64          `json:"branch_id"`
	Code            string         `json:"code"`
	Type            PromoType      `json:"type"`
	Value           pgtype.Numeric `json:"value"`
	MinOrderAmount  pgtype.Numeric `json:"min_order_amount"`
	MaxUses         pgtype.Int4    `json:"max_uses"`
	UsesPerPhone    int32          `json:"uses_per_phone"`
	ValidFrom       time.Time      `json:"valid_from"`
	ValidUntil      time.Time      `json:"valid_until"`
	TimeWindowStart pgtype.Time    `json:"time_window_start"`
	TimeWindowEnd   pgtype.Time    `json:"time_window_end"`
	Description     pgtype.Text    `json:"description"`
	CreatedBy       pgtype.Int8    `json:"created_by"`
}

func (q *Queries) CreatePromo(ctx context.Context, arg CreatePromoParams) (Promo, error) {
	row := q.db.QueryRow(ctx, createPromo,
		arg.BranchID,
		arg.Code,
		arg.Type,
		arg.Value,
		arg.MinOrderAmount,
		arg.MaxUses,
		arg.UsesPerPhone,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.TimeWindowStart,
		arg.TimeWindowEnd,
		arg.Description,
		arg.CreatedBy,
	)
	var i Promo
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.MinOrderAmount,
		&i.MaxUses,
		&i.UsesPerPhone,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.TimeWindowStart,
		&i.TimeWindowEnd,
		&i.IsActive,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RedeemedCount,
	)
	return i, err
}

const createPromoRedemption = `-- name: CreatePromoRedemption :one
INSERT INTO promo_redemptions (promo_id, order_id, phone_e164)
VALUES ($1, $2, $3) RETURNING id, promo_id, order_id, phone_e164, redeemed_at
`

type CreatePromoRedemptionParams struct {
	PromoID   int64       `json:"promo_id"`
	OrderID   uuid.UUID   `json:"order_id"`
	PhoneE164 pgtype.Text `json:"phone_e164"`
}

func (q *Queries) CreatePromoRedemption(ctx context.Context, arg CreatePromoRedemptionParams) (PromoRedemption, error) {
	row := q.db.QueryRow(ctx, createPromoRedemption, arg.PromoID, arg.OrderID, arg.PhoneE164)
	var i PromoRedemption
	err := row.Scan(
		&i.ID,
		&i.PromoID,
		&i.OrderID,
		&i.PhoneE164,
		&i.RedeemedAt,
	)
	return i, err
}

const deactivatePromo = `-- name: DeactivatePromo :exec
UPDATE promos SET is_active = FALSE WHERE id = $1 AND branch_id = $2
`

type DeactivatePromoParams struct {
	ID       int64 `json:"id"`
	BranchID int64 `json:"branch_id"`
}

func (q *Queries) DeactivatePromo(ctx context.Context, arg DeactivatePromoParams) error {
	_, err := q.db.Exec(ctx, deactivatePromo, arg.ID, arg.BranchID)
	return err
}

const getPromoByCode = `-- name: GetPromoByCode :one

SELECT id, branch_id, code, type, value, min_order_amount, max_uses, uses_per_phone, valid_from, valid_until, time_window_start, time_window_end, is_active, description, created_by, created_at, redeemed_count FROM promos
WHERE branch_id = $1
  AND LOWER(code) = LOWER($2)
  AND is_active = TRUE
  AND valid_from <= now()
  AND valid_until >= now()
  AND (
    time_window_start IS NULL
    OR (
      time_window_start <= (NOW() AT TIME ZONE (SELECT b.timezone FROM branches b WHERE b.id = promos.branch_id))::time
      AND (NOW() AT TIME ZONE (SELECT b.timezone FROM branches b WHERE b.id = promos.branch_id))::time <= time_window_end
    )
  )
`

type GetPromoByCodeParams struct {
	BranchID int64  `json:"branch_id"`
	Lower    string `json:"lower"`
}

// Daily time windows are owner-entered wall-clock times for the BRANCH, so
// they are compared against branch-local time, not the DB server's LOCALTIME
// (UTC in production — a lunch-hour promo would silently never match at
// Indian lunch hours).
func (q *Queries) GetPromoByCode(ctx context.Context, arg GetPromoByCodeParams) (Promo, error) {
	row := q.db.QueryRow(ctx, getPromoByCode, arg.BranchID, arg.Lower)
	var i Promo
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.MinOrderAmount,
		&i.MaxUses,
		&i.UsesPerPhone,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.TimeWindowStart,
		&i.TimeWindowEnd,
		&i.IsActive,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RedeemedCount,
	)
	return i, err
}

const getPromoByCodeForUpdate = `-- name: GetPromoByCodeForUpdate :one
SELECT id, branch_id, code, type, value, min_order_amount, max_uses, uses_per_phone, valid_from, valid_until, time_window_start, time_window_end, is_active, description, created_by, created_at, redeemed_count FROM promos
WHERE branch_id = $1
  AND LOWER(code) = LOWER($2)
  AND is_active = TRUE
  AND valid_from <= now()
  AND valid_until >= now()
  AND (
    time_window_start IS NULL
    OR (
      time_window_start <= (NOW() AT TIME ZONE (SELECT b.timezone FROM branches b WHERE b.id = promos.branch_id))::time
      AND (NOW() AT TIME ZONE (SELECT b.timezone FROM branches b WHERE b.id = promos.branch_id))::time <= time_window_end
    )
  )
FOR UPDATE
`

type GetPromoByCodeForUpdateParams struct {
	BranchID int64  `json:"branch_id"`
	Lower    string `json:"lower"`
}

func (q *Queries) GetPromoByCodeForUpdate(ctx context.Context, arg GetPromoByCodeForUpdateParams) (Promo, error) {
	row := q.db.QueryRow(ctx, getPromoByCodeForUpdate, arg.BranchID, arg.Lower)
	var i Promo
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.MinOrderAmount,
		&i.MaxUses,
		&i.UsesPerPhone,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.TimeWindowStart,
		&i.TimeWindowEnd,
		&i.IsActive,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RedeemedCount,
	)
	return i, err
}

const getPromoByID = `-- name: GetPromoByID :one
SELECT id, branch_id, code, type, value, min_order_amount, max_uses, uses_per_phone, valid_from, valid_until, time_window_start, time_window_end, is_active, description, created_by, created_at, redeemed_count FROM promos WHERE id = $1
`

func (q *Queries) GetPromoByID(ctx context.Context, id int64) (Promo, error) {
	row := q.db.QueryRow(ctx, getPromoByID, id)
	var i Promo
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Code,
		&i.Type,
		&i.Value,
		&i.MinOrderAmount,
		&i.MaxUses,
		&i.UsesPerPhone,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.TimeWindowStart,
		&i.TimeWindowEnd,
		&i.IsActive,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RedeemedCount,
	)
	return i, err
}

const incrementPromoRedemptionCount = `-- name: IncrementPromoRedemptionCount :exec
UPDATE promos
SET redeemed_count = redeemed_count + 1
WHERE id = $1
`

func (q *Queries) IncrementPromoRedemptionCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementPromoRedemptionCount, id)
	return err
}

const listPromosForBranch = `-- name: ListPromosForBranch :many
SELECT id, branch_id, code, type, value, min_order_amount, max_uses, uses_per_phone, valid_from, valid_until, time_window_start, time_window_end, is_active, description, created_by, created_at, redeemed_count FROM promos WHERE branch_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPromosForBranch(ctx context.Context, branchID int64) ([]Promo, error) {
	rows, err := q.db.Query(ctx, listPromosForBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Promo{}
	for rows.Next() {
		var i Promo
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Code,
			&i.Type,
			&i.Value,
			&i.MinOrderAmount,
			&i.MaxUses,
			&i.UsesPerPhone,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.TimeWindowStart,
			&i.TimeWindowEnd,
			&i.IsActive,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.RedeemedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
