// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AbandonSession(ctx context.Context, id uuid.UUID) error
	// Accepts both active and awaiting_reactivation states; the latter is the
	// terminal stage of the awaiting_reactivation pipeline.
	AbandonStaleSession(ctx context.Context, id uuid.UUID) error
	ActivatePlatformMFA(ctx context.Context, arg ActivatePlatformMFAParams) (PlatformUserMfa, error)
	AddCartItem(ctx context.Context, arg AddCartItemParams) (CartItem, error)
	AddPlatformUserRole(ctx context.Context, arg AddPlatformUserRoleParams) error
	BumpAllParticipantCredentialVersions(ctx context.Context, sessionID uuid.UUID) error
	ClearCart(ctx context.Context, cartID int64) error
	CloseSessionIfActive(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error
	ConsumePlatformMFAChallenge(ctx context.Context, challengeHash string) error
	ConsumeRecoveryCodes(ctx context.Context, arg ConsumeRecoveryCodesParams) error
	CountItemsInCategory(ctx context.Context, categoryID int64) (int64, error)
	CountPromoRedemptions(ctx context.Context, promoID int64) (int64, error)
	CountPromoRedemptionsByPhone(ctx context.Context, arg CountPromoRedemptionsByPhoneParams) (int64, error)
	CreateAssistanceRequest(ctx context.Context, arg CreateAssistanceRequestParams) (AssistanceRequest, error)
	CreateBillSnapshot(ctx context.Context, arg CreateBillSnapshotParams) (BillSnapshot, error)
	CreateFeatureFlag(ctx context.Context, arg CreateFeatureFlagParams) (PlatformFeatureFlag, error)
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error)
	CreateItemModifier(ctx context.Context, arg CreateItemModifierParams) (ItemModifier, error)
	CreateItemModifierScoped(ctx context.Context, arg CreateItemModifierScopedParams) (ItemModifier, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateOrganizationBranchMembership(ctx context.Context, arg CreateOrganizationBranchMembershipParams) error
	CreateOrganizationMember(ctx context.Context, arg CreateOrganizationMemberParams) (OrganizationMember, error)
	CreateParticipant(ctx context.Context, arg CreateParticipantParams) (SessionParticipant, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePlan(ctx context.Context, arg CreatePlanParams) (SubscriptionPlan, error)
	CreatePlatformBranch(ctx context.Context, arg CreatePlatformBranchParams) (Branch, error)
	CreatePlatformMFAChallenge(ctx context.Context, arg CreatePlatformMFAChallengeParams) (PlatformMfaChallenge, error)
	CreatePlatformOrganization(ctx context.Context, arg CreatePlatformOrganizationParams) (Organization, error)
	CreatePlatformRestaurant(ctx context.Context, arg CreatePlatformRestaurantParams) (Restaurant, error)
	CreatePlatformSession(ctx context.Context, arg CreatePlatformSessionParams) (PlatformSession, error)
	CreatePlatformSupportSession(ctx context.Context, arg CreatePlatformSupportSessionParams) (PlatformSupportSession, error)
	CreatePromo(ctx context.Context, arg CreatePromoParams) (Promo, error)
	CreatePromoRedemption(ctx context.Context, arg CreatePromoRedemptionParams) (PromoRedemption, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error)
	CreateStaffSession(ctx context.Context, arg CreateStaffSessionParams) (StaffSession, error)
	CreateTable(ctx context.Context, arg CreateTableParams) (Table, error)
	DeactivatePromo(ctx context.Context, arg DeactivatePromoParams) error
	DeactivateStaff(ctx context.Context, id int64) error
	DeleteBranchFlagOverride(ctx context.Context, arg DeleteBranchFlagOverrideParams) error
	DeleteCustomer(ctx context.Context, arg DeleteCustomerParams) error
	DeleteGlobalFlagOverride(ctx context.Context, flagKey string) error
	DeleteItemModifier(ctx context.Context, id int64) error
	DeleteItemModifierScoped(ctx context.Context, arg DeleteItemModifierScopedParams) error
	DeleteMenuCategory(ctx context.Context, arg DeleteMenuCategoryParams) error
	DeleteMenuItem(ctx context.Context, arg DeleteMenuItemParams) error
	DeleteOrganizationEntitlementOverride(ctx context.Context, arg DeleteOrganizationEntitlementOverrideParams) error
	DeleteOrganizationFlagOverride(ctx context.Context, arg DeleteOrganizationFlagOverrideParams) error
	DeletePlanEntitlements(ctx context.Context, planID int64) error
	DisablePlatformMFA(ctx context.Context, platformUserID int64) error
	FailIdempotencyKey(ctx context.Context, arg FailIdempotencyKeyParams) error
	GetActivePlatformSessionByTokenHash(ctx context.Context, tokenHash string) (PlatformSession, error)
	GetActiveSessionForTable(ctx context.Context, tableID int64) (Session, error)
	GetActiveStaffSessionByTokenHash(ctx context.Context, tokenHash string) (StaffSession, error)
	GetAssistanceRequestByID(ctx context.Context, id int64) (AssistanceRequest, error)
	GetBillSnapshotByID(ctx context.Context, id int64) (BillSnapshot, error)
	GetBranchByCode(ctx context.Context, branchCode string) (Branch, error)
	GetBranchByID(ctx context.Context, id int64) (Branch, error)
	// Returns order count per hour-of-day (0–23) in the branch's configured timezone.
	GetBusyHours(ctx context.Context, arg GetBusyHoursParams) ([]GetBusyHoursRow, error)
	GetCartByID(ctx context.Context, id int64) (Cart, error)
	GetCartBySessionAndParticipant(ctx context.Context, arg GetCartBySessionAndParticipantParams) (Cart, error)
	GetCartItem(ctx context.Context, id int64) (CartItem, error)
	GetCustomerByID(ctx context.Context, id int64) (Customer, error)
	GetCustomerByPhone(ctx context.Context, arg GetCustomerByPhoneParams) (Customer, error)
	GetCustomerSessionHistory(ctx context.Context, customerID pgtype.Int8) ([]GetCustomerSessionHistoryRow, error)
	GetCustomerSessionHistoryScoped(ctx context.Context, arg GetCustomerSessionHistoryScopedParams) ([]GetCustomerSessionHistoryScopedRow, error)
	GetEntitlement(ctx context.Context, key string) (Entitlement, error)
	GetEventsBySession(ctx context.Context, sessionID pgtype.UUID) ([]EventLog, error)
	GetFeatureFlag(ctx context.Context, key string) (PlatformFeatureFlag, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error)
	GetMenuCategoryByID(ctx context.Context, id int64) (MenuCategory, error)
	GetMenuItemByID(ctx context.Context, id int64) (MenuItem, error)
	GetMenuItemsByIDs(ctx context.Context, dollar_1 []int64) ([]MenuItem, error)
	GetModifierWithItemBranch(ctx context.Context, id int64) (GetModifierWithItemBranchRow, error)
	GetOldestActiveParticipant(ctx context.Context, sessionID uuid.UUID) (SessionParticipant, error)
	GetOrCreateCart(ctx context.Context, arg GetOrCreateCartParams) (Cart, error)
	GetOrCreateSessionCart(ctx context.Context, sessionID uuid.UUID) (Cart, error)
	GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error)
	GetOrderByIdempotencyKey(ctx context.Context, idempotencyKey string) (Order, error)
	GetOrderByScopedIdempotencyKey(ctx context.Context, arg GetOrderByScopedIdempotencyKeyParams) (Order, error)
	// Returns daily order count and revenue for a branch within a time window.
	GetOrderVolume(ctx context.Context, arg GetOrderVolumeParams) ([]GetOrderVolumeRow, error)
	// Returns order count per UTC hour-of-day (0-23) across an organization.
	GetOrganizationBusyHours(ctx context.Context, arg GetOrganizationBusyHoursParams) ([]GetOrganizationBusyHoursRow, error)
	GetOrganizationByBranchID(ctx context.Context, id int64) (Organization, error)
	GetOrganizationByCode(ctx context.Context, code string) (Organization, error)
	GetOrganizationByID(ctx context.Context, id int64) (Organization, error)
	GetOrganizationByRestaurantID(ctx context.Context, id int64) (Organization, error)
	GetOrganizationMembershipForStaff(ctx context.Context, arg GetOrganizationMembershipForStaffParams) (OrganizationMember, error)
	// Returns daily UTC order count and revenue across an organization.
	GetOrganizationOrderVolume(ctx context.Context, arg GetOrganizationOrderVolumeParams) ([]GetOrganizationOrderVolumeRow, error)
	GetOrganizationPlanAssignment(ctx context.Context, organizationID int64) (OrganizationPlanAssignment, error)
	// Returns the most ordered menu items across an organization within a time window.
	GetOrganizationTopOrderedItems(ctx context.Context, arg GetOrganizationTopOrderedItemsParams) ([]GetOrganizationTopOrderedItemsRow, error)
	GetParticipantByID(ctx context.Context, id int64) (SessionParticipant, error)
	GetPaymentByID(ctx context.Context, id int64) (Payment, error)
	GetPaymentByProviderRef(ctx context.Context, arg GetPaymentByProviderRefParams) (Payment, error)
	GetPlanByID(ctx context.Context, id int64) (SubscriptionPlan, error)
	GetPlanByTier(ctx context.Context, tier PlanTier) (SubscriptionPlan, error)
	GetPlatformMFA(ctx context.Context, platformUserID int64) (PlatformUserMfa, error)
	GetPlatformMFAChallengeByHash(ctx context.Context, challengeHash string) (PlatformMfaChallenge, error)
	GetPlatformSupportSessionByID(ctx context.Context, id int64) (PlatformSupportSession, error)
	GetPlatformUserByEmail(ctx context.Context, email string) (PlatformUser, error)
	GetPlatformUserByID(ctx context.Context, id int64) (PlatformUser, error)
	GetPromoByCode(ctx context.Context, arg GetPromoByCodeParams) (Promo, error)
	GetPromoByCodeForUpdate(ctx context.Context, arg GetPromoByCodeForUpdateParams) (Promo, error)
	GetPromoByID(ctx context.Context, id int64) (Promo, error)
	GetRecentEventsByBranch(ctx context.Context, branchID pgtype.Int8) ([]EventLog, error)
	GetRestaurantByBranchID(ctx context.Context, id int64) (Restaurant, error)
	GetRestaurantByID(ctx context.Context, id int64) (Restaurant, error)
	GetRestaurantByOrganizationID(ctx context.Context, organizationID int64) (Restaurant, error)
	GetRestaurantBySlug(ctx context.Context, slug string) (Restaurant, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetSessionByToken(ctx context.Context, sessionToken string) (Session, error)
	GetSessionParticipantByID(ctx context.Context, id int64) (SessionParticipant, error)
	GetStaffByBranchAndCode(ctx context.Context, arg GetStaffByBranchAndCodeParams) (Staff, error)
	GetStaffByID(ctx context.Context, id int64) (Staff, error)
	GetSubscriptionByRestaurant(ctx context.Context, restaurantID int64) (GetSubscriptionByRestaurantRow, error)
	GetTableByID(ctx context.Context, id int64) (Table, error)
	GetTableByQRToken(ctx context.Context, qrCodeToken string) (Table, error)
	GetTenantThemeByRestaurant(ctx context.Context, restaurantID int64) (TenantTheme, error)
	GetThemePreset(ctx context.Context, key string) (ThemePreset, error)
	// Returns the most ordered menu items for a branch within a time window.
	GetTopOrderedItems(ctx context.Context, arg GetTopOrderedItemsParams) ([]GetTopOrderedItemsRow, error)
	HasNonTerminalPaymentForSession(ctx context.Context, sessionID uuid.UUID) (bool, error)
	IncrementPromoRedemptionCount(ctx context.Context, id int64) error
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error
	InsertEventLog(ctx context.Context, arg InsertEventLogParams) error
	InsertMenuCategory(ctx context.Context, arg InsertMenuCategoryParams) (MenuCategory, error)
	InsertMenuItem(ctx context.Context, arg InsertMenuItemParams) (MenuItem, error)
	InsertPlatformAuditLog(ctx context.Context, arg InsertPlatformAuditLogParams) error
	InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (PaymentWebhookEvent, error)
	LinkSessionToCustomer(ctx context.Context, arg LinkSessionToCustomerParams) error
	ListActiveAssistanceForBranch(ctx context.Context, branchID int64) ([]ListActiveAssistanceForBranchRow, error)
	ListActiveOrderItemsForBranch(ctx context.Context, branchID int64) ([]ListActiveOrderItemsForBranchRow, error)
	ListActiveOrdersForBranch(ctx context.Context, branchID int64) ([]ListActiveOrdersForBranchRow, error)
	ListActiveSessionsForBranch(ctx context.Context, branchID int64) ([]Session, error)
	// Returns active sessions older than the grace floor — candidates for the
	// awaiting_reactivation transition. The worker still has to verify Redis
	// presence absence before transitioning.
	ListActiveSessionsForReactivationScan(ctx context.Context, dollar_1 time.Time) ([]ListActiveSessionsForReactivationScanRow, error)
	ListActiveStaffForBranch(ctx context.Context, branchID int64) ([]Staff, error)
	ListAllMenuCategoriesForBranch(ctx context.Context, branchID int64) ([]MenuCategory, error)
	ListAllMenuItemsForCategory(ctx context.Context, categoryID int64) ([]MenuItem, error)
	ListAssistanceForSession(ctx context.Context, sessionID uuid.UUID) ([]AssistanceRequest, error)
	ListAuditLogForBranch(ctx context.Context, arg ListAuditLogForBranchParams) ([]AuditLog, error)
	ListAuditLogForOrganization(ctx context.Context, arg ListAuditLogForOrganizationParams) ([]AuditLog, error)
	ListAuditLogPlatform(ctx context.Context, arg ListAuditLogPlatformParams) ([]AuditLog, error)
	ListBranchFlagOverrides(ctx context.Context, branchID int64) ([]PlatformFlagBranchOverride, error)
	ListBranchesForOrganization(ctx context.Context, organizationID int64) ([]Branch, error)
	ListCartItems(ctx context.Context, cartID int64) ([]ListCartItemsRow, error)
	ListEntitlementCatalog(ctx context.Context) ([]Entitlement, error)
	// Queries used by background worker routines.
	// Finds sessions that have exceeded their branch-configured timeout.
	ListExpiredSessions(ctx context.Context) ([]ListExpiredSessionsRow, error)
	ListFeatureFlags(ctx context.Context) ([]PlatformFeatureFlag, error)
	ListFeaturedMenuItems(ctx context.Context, branchID int64) ([]MenuItem, error)
	ListGlobalFlagOverrides(ctx context.Context) ([]PlatformFlagGlobalOverride, error)
	ListMenuCategoriesForBranch(ctx context.Context, branchID int64) ([]MenuCategory, error)
	ListMenuItemsForCategory(ctx context.Context, categoryID int64) ([]MenuItem, error)
	ListModifiersForItem(ctx context.Context, itemID int64) ([]ItemModifier, error)
	ListModifiersForItems(ctx context.Context, dollar_1 []int64) ([]ItemModifier, error)
	ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	ListOrdersForSession(ctx context.Context, sessionID uuid.UUID) ([]Order, error)
	ListOrganizationEntitlementOverrides(ctx context.Context, organizationID int64) ([]OrganizationEntitlementOverride, error)
	ListOrganizationFlagOverrides(ctx context.Context, organizationID int64) ([]PlatformFlagOrganizationOverride, error)
	ListParticipantsBySession(ctx context.Context, sessionID uuid.UUID) ([]SessionParticipant, error)
	ListPaymentsForBranchByStatus(ctx context.Context, arg ListPaymentsForBranchByStatusParams) ([]ListPaymentsForBranchByStatusRow, error)
	ListPaymentsForSession(ctx context.Context, sessionID uuid.UUID) ([]Payment, error)
	ListPlanEntitlements(ctx context.Context, planID int64) ([]PlanEntitlement, error)
	ListPlans(ctx context.Context) ([]SubscriptionPlan, error)
	ListPlatformAuditLog(ctx context.Context, arg ListPlatformAuditLogParams) ([]PlatformAuditLog, error)
	ListPlatformOrganizations(ctx context.Context) ([]Organization, error)
	ListPlatformRolesForUser(ctx context.Context, platformUserID int64) ([]string, error)
	ListPlatformSupportSessions(ctx context.Context) ([]PlatformSupportSession, error)
	ListPlatformUsers(ctx context.Context) ([]PlatformUser, error)
	ListPromosForBranch(ctx context.Context, branchID int64) ([]Promo, error)
	// Returns sessions whose reactivation window has been exceeded. Caller is
	// responsible for verifying no non-terminal payment exists before abandoning
	// (TIM-1 in payment-finalization-invariants.md).
	ListSessionsAwaitingReactivationExpired(ctx context.Context, dollar_1 time.Time) ([]ListSessionsAwaitingReactivationExpiredRow, error)
	ListSessionsExpiringSoon(ctx context.Context) ([]ListSessionsExpiringSoonRow, error)
	ListStaffForBranch(ctx context.Context, branchID int64) ([]Staff, error)
	ListTablesForBranch(ctx context.Context, branchID int64) ([]Table, error)
	ListThemePresets(ctx context.Context) ([]ThemePreset, error)
	ListUnprocessedWebhooks(ctx context.Context) ([]PaymentWebhookEvent, error)
	ListWebhookEventsByPayment(ctx context.Context, paymentID pgtype.Int8) ([]PaymentWebhookEvent, error)
	MarkSessionWarned(ctx context.Context, id uuid.UUID) error
	MarkWebhookProcessed(ctx context.Context, arg MarkWebhookProcessedParams) error
	NextOrderNumber(ctx context.Context, arg NextOrderNumberParams) (int32, error)
	NextPaymentNumber(ctx context.Context, arg NextPaymentNumberParams) (int32, error)
	NextSessionNumber(ctx context.Context, arg NextSessionNumberParams) (int32, error)
	PlatformActiveBranches(ctx context.Context, arg PlatformActiveBranchesParams) (int64, error)
	PlatformActiveDiners(ctx context.Context, organizationID pgtype.Int8) (int64, error)
	PlatformAuthzDenialsPerDay(ctx context.Context, arg PlatformAuthzDenialsPerDayParams) ([]PlatformAuthzDenialsPerDayRow, error)
	PlatformGMV(ctx context.Context, arg PlatformGMVParams) (string, error)
	PlatformOrdersPerDay(ctx context.Context, arg PlatformOrdersPerDayParams) ([]PlatformOrdersPerDayRow, error)
	PlatformParticipantJoinsPerDay(ctx context.Context, arg PlatformParticipantJoinsPerDayParams) ([]PlatformParticipantJoinsPerDayRow, error)
	PlatformPaymentsPerDay(ctx context.Context, arg PlatformPaymentsPerDayParams) ([]PlatformPaymentsPerDayRow, error)
	PlatformRevenueByBranch(ctx context.Context, arg PlatformRevenueByBranchParams) ([]PlatformRevenueByBranchRow, error)
	PlatformRevenueByOrg(ctx context.Context, arg PlatformRevenueByOrgParams) ([]PlatformRevenueByOrgRow, error)
	PlatformRevenuePerDay(ctx context.Context, arg PlatformRevenuePerDayParams) ([]PlatformRevenuePerDayRow, error)
	// Platform (cross-tenant) analytics. On-demand aggregation; optional org filter via
	// sqlc.narg('organization_id') (NULL = platform-wide). UTC day bucketing for cross-tenant
	// consistency. Operator-facing; not entitlement-gated.
	PlatformSessionsPerDay(ctx context.Context, arg PlatformSessionsPerDayParams) ([]PlatformSessionsPerDayRow, error)
	PlatformWebhookFailuresPerDay(ctx context.Context, arg PlatformWebhookFailuresPerDayParams) ([]PlatformWebhookFailuresPerDayRow, error)
	ReactivateSession(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	RefreshTableQRToken(ctx context.Context, arg RefreshTableQRTokenParams) (Table, error)
	RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error
	RevokeAllParticipants(ctx context.Context, arg RevokeAllParticipantsParams) error
	RevokePlatformSession(ctx context.Context, arg RevokePlatformSessionParams) error
	RevokeStaffSessionsForStaff(ctx context.Context, staffID int64) error
	SearchCustomersByPhone(ctx context.Context, arg SearchCustomersByPhoneParams) ([]Customer, error)
	// Sets is_host = true for exactly the new host and false for everyone else in
	// the session, in a single statement. Used for host reassignment.
	SetParticipantHostFlags(ctx context.Context, arg SetParticipantHostFlagsParams) error
	SetSessionHost(ctx context.Context, arg SetSessionHostParams) error
	SettlePaymentByStaff(ctx context.Context, arg SettlePaymentByStaffParams) (Payment, error)
	SumCompletedPaymentsForSession(ctx context.Context, sessionID uuid.UUID) (pgtype.Numeric, error)
	TouchPlatformMFAUse(ctx context.Context, platformUserID int64) error
	TouchPlatformSession(ctx context.Context, id uuid.UUID) error
	TouchStaffSession(ctx context.Context, id uuid.UUID) error
	TransitionSessionToActive(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	TransitionSessionToAwaitingReactivation(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	TransitionSessionToPaymentPending(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	UpdateAssistanceStatus(ctx context.Context, arg UpdateAssistanceStatusParams) (AssistanceRequest, error)
	UpdateAssistanceStatusScoped(ctx context.Context, arg UpdateAssistanceStatusScopedParams) (AssistanceRequest, error)
	UpdateBranchOrderPrefix(ctx context.Context, arg UpdateBranchOrderPrefixParams) error
	UpdateBranchSessionTimeout(ctx context.Context, arg UpdateBranchSessionTimeoutParams) error
	UpdateBranchStatus(ctx context.Context, arg UpdateBranchStatusParams) (Branch, error)
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error)
	UpdateFeatureFlag(ctx context.Context, arg UpdateFeatureFlagParams) (PlatformFeatureFlag, error)
	UpdateMenuCategory(ctx context.Context, arg UpdateMenuCategoryParams) (MenuCategory, error)
	UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error)
	UpdateMenuItemAvailability(ctx context.Context, arg UpdateMenuItemAvailabilityParams) error
	UpdateMenuItemAvailabilityScoped(ctx context.Context, arg UpdateMenuItemAvailabilityScopedParams) error
	UpdateMenuItemFeatured(ctx context.Context, arg UpdateMenuItemFeaturedParams) error
	UpdateMenuItemFeaturedScoped(ctx context.Context, arg UpdateMenuItemFeaturedScopedParams) error
	UpdateMenuItemScoped(ctx context.Context, arg UpdateMenuItemScopedParams) (MenuItem, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateOrderStatusExpected(ctx context.Context, arg UpdateOrderStatusExpectedParams) (Order, error)
	UpdateOrderStatusScoped(ctx context.Context, arg UpdateOrderStatusScopedParams) (Order, error)
	UpdateOrganizationSettings(ctx context.Context, arg UpdateOrganizationSettingsParams) (Organization, error)
	UpdateOrganizationStatus(ctx context.Context, arg UpdateOrganizationStatusParams) (Organization, error)
	UpdateParticipantLastSeen(ctx context.Context, id int64) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdatePaymentStatusExpected(ctx context.Context, arg UpdatePaymentStatusExpectedParams) (Payment, error)
	UpdatePlan(ctx context.Context, arg UpdatePlanParams) (SubscriptionPlan, error)
	UpdateRestaurantLogoByBranchID(ctx context.Context, arg UpdateRestaurantLogoByBranchIDParams) error
	UpdateStaffPIN(ctx context.Context, arg UpdateStaffPINParams) error
	UpdateTableStatus(ctx context.Context, arg UpdateTableStatusParams) error
	UpsertBranchFlagOverride(ctx context.Context, arg UpsertBranchFlagOverrideParams) (PlatformFlagBranchOverride, error)
	UpsertCustomer(ctx context.Context, arg UpsertCustomerParams) (Customer, error)
	UpsertGlobalFlagOverride(ctx context.Context, arg UpsertGlobalFlagOverrideParams) (PlatformFlagGlobalOverride, error)
	UpsertOrganizationEntitlementOverride(ctx context.Context, arg UpsertOrganizationEntitlementOverrideParams) (OrganizationEntitlementOverride, error)
	UpsertOrganizationFlagOverride(ctx context.Context, arg UpsertOrganizationFlagOverrideParams) (PlatformFlagOrganizationOverride, error)
	UpsertOrganizationPlanAssignment(ctx context.Context, arg UpsertOrganizationPlanAssignmentParams) (OrganizationPlanAssignment, error)
	UpsertPlanEntitlement(ctx context.Context, arg UpsertPlanEntitlementParams) (PlanEntitlement, error)
	UpsertPlatformMFAPending(ctx context.Context, arg UpsertPlatformMFAPendingParams) (PlatformUserMfa, error)
	UpsertPlatformUser(ctx context.Context, arg UpsertPlatformUserParams) (PlatformUser, error)
	UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (RestaurantSubscription, error)
	UpsertTenantTheme(ctx context.Context, arg UpsertTenantThemeParams) (TenantTheme, error)
}

var _ Querier = (*Queries)(nil)
