// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AbandonSession(ctx context.Context, id uuid.UUID) error
	AbandonStaleSession(ctx context.Context, id uuid.UUID) error
	AddCartItem(ctx context.Context, arg AddCartItemParams) (CartItem, error)
	ClearCart(ctx context.Context, cartID int64) error
	CloseSessionIfActive(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	CountItemsInCategory(ctx context.Context, categoryID int64) (int64, error)
	CreateAssistanceRequest(ctx context.Context, arg CreateAssistanceRequestParams) (AssistanceRequest, error)
	CreateItemModifier(ctx context.Context, arg CreateItemModifierParams) (ItemModifier, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateParticipant(ctx context.Context, arg CreateParticipantParams) (SessionParticipant, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error)
	CreateTable(ctx context.Context, arg CreateTableParams) (Table, error)
	DeactivateStaff(ctx context.Context, id int64) error
	DeleteCustomer(ctx context.Context, arg DeleteCustomerParams) error
	DeleteItemModifier(ctx context.Context, id int64) error
	DeleteMenuCategory(ctx context.Context, arg DeleteMenuCategoryParams) error
	DeleteMenuItem(ctx context.Context, arg DeleteMenuItemParams) error
	GetActiveSessionForTable(ctx context.Context, tableID int64) (Session, error)
	GetAssistanceRequestByID(ctx context.Context, id int64) (AssistanceRequest, error)
	GetBranchByID(ctx context.Context, id int64) (Branch, error)
	// Returns order count per hour-of-day (0–23) in the branch's configured timezone.
	GetBusyHours(ctx context.Context, arg GetBusyHoursParams) ([]GetBusyHoursRow, error)
	GetCartByID(ctx context.Context, id int64) (Cart, error)
	GetCartBySessionAndParticipant(ctx context.Context, arg GetCartBySessionAndParticipantParams) (Cart, error)
	GetCartItem(ctx context.Context, id int64) (CartItem, error)
	GetCustomerByPhone(ctx context.Context, arg GetCustomerByPhoneParams) (Customer, error)
	GetCustomerSessionHistory(ctx context.Context, customerID pgtype.Int8) ([]GetCustomerSessionHistoryRow, error)
	GetEventsBySession(ctx context.Context, sessionID pgtype.UUID) ([]EventLog, error)
	GetMenuItemByID(ctx context.Context, id int64) (MenuItem, error)
	GetMenuItemsByIDs(ctx context.Context, dollar_1 []int64) ([]MenuItem, error)
	GetOrCreateCart(ctx context.Context, arg GetOrCreateCartParams) (Cart, error)
	GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error)
	GetOrderByIdempotencyKey(ctx context.Context, idempotencyKey string) (Order, error)
	// Returns daily order count and revenue for a branch within a time window.
	GetOrderVolume(ctx context.Context, arg GetOrderVolumeParams) ([]GetOrderVolumeRow, error)
	GetParticipantByID(ctx context.Context, id int64) (SessionParticipant, error)
	GetPaymentByID(ctx context.Context, id int64) (Payment, error)
	GetPlanByTier(ctx context.Context, tier PlanTier) (SubscriptionPlan, error)
	GetRecentEventsByBranch(ctx context.Context, branchID pgtype.Int8) ([]EventLog, error)
	GetRestaurantByBranchID(ctx context.Context, id int64) (Restaurant, error)
	GetRestaurantByID(ctx context.Context, id int64) (Restaurant, error)
	GetRestaurantBySlug(ctx context.Context, slug string) (Restaurant, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetSessionByToken(ctx context.Context, sessionToken string) (Session, error)
	GetStaffByID(ctx context.Context, id int64) (Staff, error)
	GetSubscriptionByRestaurant(ctx context.Context, restaurantID int64) (GetSubscriptionByRestaurantRow, error)
	GetTableByID(ctx context.Context, id int64) (Table, error)
	GetTableByQRToken(ctx context.Context, qrCodeToken string) (Table, error)
	// Returns the most ordered menu items for a branch within a time window.
	GetTopOrderedItems(ctx context.Context, arg GetTopOrderedItemsParams) ([]GetTopOrderedItemsRow, error)
	InsertEventLog(ctx context.Context, arg InsertEventLogParams) error
	InsertMenuCategory(ctx context.Context, arg InsertMenuCategoryParams) (MenuCategory, error)
	InsertMenuItem(ctx context.Context, arg InsertMenuItemParams) (MenuItem, error)
	InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (PaymentWebhookEvent, error)
	LinkSessionToCustomer(ctx context.Context, arg LinkSessionToCustomerParams) error
	ListActiveAssistanceForBranch(ctx context.Context, branchID int64) ([]AssistanceRequest, error)
	ListActiveOrdersForBranch(ctx context.Context, branchID int64) ([]ListActiveOrdersForBranchRow, error)
	ListActiveSessionsForBranch(ctx context.Context, branchID int64) ([]Session, error)
	ListActiveStaffForBranch(ctx context.Context, branchID int64) ([]Staff, error)
	ListAllMenuCategoriesForBranch(ctx context.Context, branchID int64) ([]MenuCategory, error)
	ListAllMenuItemsForCategory(ctx context.Context, categoryID int64) ([]MenuItem, error)
	ListAssistanceForSession(ctx context.Context, sessionID uuid.UUID) ([]AssistanceRequest, error)
	ListCartItems(ctx context.Context, cartID int64) ([]ListCartItemsRow, error)
	// Queries used by background worker routines.
	// Finds sessions that have exceeded their branch-configured timeout.
	ListExpiredSessions(ctx context.Context) ([]ListExpiredSessionsRow, error)
	ListFeaturedMenuItems(ctx context.Context, branchID int64) ([]MenuItem, error)
	ListMenuCategoriesForBranch(ctx context.Context, branchID int64) ([]MenuCategory, error)
	ListMenuItemsForCategory(ctx context.Context, categoryID int64) ([]MenuItem, error)
	ListModifiersForItem(ctx context.Context, itemID int64) ([]ItemModifier, error)
	ListModifiersForItems(ctx context.Context, dollar_1 []int64) ([]ItemModifier, error)
	ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	ListOrdersForSession(ctx context.Context, sessionID uuid.UUID) ([]Order, error)
	ListParticipantsBySession(ctx context.Context, sessionID uuid.UUID) ([]SessionParticipant, error)
	ListPaymentsForSession(ctx context.Context, sessionID uuid.UUID) ([]Payment, error)
	ListPlans(ctx context.Context) ([]SubscriptionPlan, error)
	ListSessionsExpiringSoon(ctx context.Context) ([]ListSessionsExpiringSoonRow, error)
	ListStaffForBranch(ctx context.Context, branchID int64) ([]Staff, error)
	ListTablesForBranch(ctx context.Context, branchID int64) ([]Table, error)
	ListUnprocessedWebhooks(ctx context.Context) ([]PaymentWebhookEvent, error)
	MarkSessionWarned(ctx context.Context, id uuid.UUID) error
	MarkWebhookProcessed(ctx context.Context, arg MarkWebhookProcessedParams) error
	RefreshTableQRToken(ctx context.Context, arg RefreshTableQRTokenParams) (Table, error)
	RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error
	SearchCustomersByPhone(ctx context.Context, arg SearchCustomersByPhoneParams) ([]Customer, error)
	SetSessionHost(ctx context.Context, arg SetSessionHostParams) error
	UpdateAssistanceStatus(ctx context.Context, arg UpdateAssistanceStatusParams) (AssistanceRequest, error)
	UpdateBranchSessionTimeout(ctx context.Context, arg UpdateBranchSessionTimeoutParams) error
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error)
	UpdateMenuCategory(ctx context.Context, arg UpdateMenuCategoryParams) (MenuCategory, error)
	UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error)
	UpdateMenuItemAvailability(ctx context.Context, arg UpdateMenuItemAvailabilityParams) error
	UpdateMenuItemFeatured(ctx context.Context, arg UpdateMenuItemFeaturedParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateParticipantLastSeen(ctx context.Context, id int64) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdateRestaurantLogoByBranchID(ctx context.Context, arg UpdateRestaurantLogoByBranchIDParams) error
	UpdateStaffPIN(ctx context.Context, arg UpdateStaffPINParams) error
	UpdateTableStatus(ctx context.Context, arg UpdateTableStatusParams) error
	UpsertCustomer(ctx context.Context, arg UpsertCustomerParams) (Customer, error)
	UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (RestaurantSubscription, error)
}

var _ Querier = (*Queries)(nil)
