// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: restaurants.sql

package sqlc

import (
	"context"
)

const getRestaurantByBranchID = `-- name: GetRestaurantByBranchID :one
SELECT r.id, r.name, r.slug, r.settings_json, r.created_at
FROM restaurants r
JOIN branches b ON b.restaurant_id = r.id
WHERE b.id = $1
`

func (q *Queries) GetRestaurantByBranchID(ctx context.Context, id int64) (Restaurant, error) {
	row := q.db.QueryRow(ctx, getRestaurantByBranchID, id)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SettingsJson,
		&i.CreatedAt,
	)
	return i, err
}

const getRestaurantBySlug = `-- name: GetRestaurantBySlug :one
SELECT id, name, slug, settings_json, created_at FROM restaurants WHERE slug = $1
`

func (q *Queries) GetRestaurantBySlug(ctx context.Context, slug string) (Restaurant, error) {
	row := q.db.QueryRow(ctx, getRestaurantBySlug, slug)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SettingsJson,
		&i.CreatedAt,
	)
	return i, err
}
