// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const abandonSession = `-- name: AbandonSession :exec
UPDATE sessions
SET status = 'abandoned', closed_at = NOW()
WHERE id = $1 AND status = 'active'
`

func (q *Queries) AbandonSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, abandonSession, id)
	return err
}

const closeSession = `-- name: CloseSession :exec
UPDATE sessions
SET status = 'closed', closed_at = NOW()
WHERE id = $1 AND status = 'active'
`

func (q *Queries) CloseSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, closeSession, id)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (branch_id, table_id, session_token)
VALUES ($1, $2, $3)
RETURNING id, branch_id, table_id, host_participant_id, status, session_token, created_at, closed_at
`

type CreateSessionParams struct {
	BranchID     int64  `json:"branch_id"`
	TableID      int64  `json:"table_id"`
	SessionToken string `json:"session_token"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.BranchID, arg.TableID, arg.SessionToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.TableID,
		&i.HostParticipantID,
		&i.Status,
		&i.SessionToken,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getActiveSessionForTable = `-- name: GetActiveSessionForTable :one
SELECT id, branch_id, table_id, host_participant_id, status, session_token, created_at, closed_at FROM sessions
WHERE table_id = $1 AND status = 'active'
LIMIT 1
`

func (q *Queries) GetActiveSessionForTable(ctx context.Context, tableID int64) (Session, error) {
	row := q.db.QueryRow(ctx, getActiveSessionForTable, tableID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.TableID,
		&i.HostParticipantID,
		&i.Status,
		&i.SessionToken,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, branch_id, table_id, host_participant_id, status, session_token, created_at, closed_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.TableID,
		&i.HostParticipantID,
		&i.Status,
		&i.SessionToken,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, branch_id, table_id, host_participant_id, status, session_token, created_at, closed_at FROM sessions WHERE session_token = $1 AND status = 'active'
`

func (q *Queries) GetSessionByToken(ctx context.Context, sessionToken string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, sessionToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.TableID,
		&i.HostParticipantID,
		&i.Status,
		&i.SessionToken,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const listActiveSessionsForBranch = `-- name: ListActiveSessionsForBranch :many
SELECT id, branch_id, table_id, host_participant_id, status, session_token, created_at, closed_at FROM sessions
WHERE branch_id = $1 AND status = 'active'
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSessionsForBranch(ctx context.Context, branchID int64) ([]Session, error) {
	rows, err := q.db.Query(ctx, listActiveSessionsForBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.TableID,
			&i.HostParticipantID,
			&i.Status,
			&i.SessionToken,
			&i.CreatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSessionHost = `-- name: SetSessionHost :exec
UPDATE sessions SET host_participant_id = $2 WHERE id = $1
`

type SetSessionHostParams struct {
	ID                uuid.UUID   `json:"id"`
	HostParticipantID pgtype.Int8 `json:"host_participant_id"`
}

func (q *Queries) SetSessionHost(ctx context.Context, arg SetSessionHostParams) error {
	_, err := q.db.Exec(ctx, setSessionHost, arg.ID, arg.HostParticipantID)
	return err
}
