// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlanByTier = `-- name: GetPlanByTier :one
SELECT id, name, tier, price_monthly, features_json, created_at FROM subscription_plans WHERE tier = $1
`

func (q *Queries) GetPlanByTier(ctx context.Context, tier PlanTier) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, getPlanByTier, tier)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tier,
		&i.PriceMonthly,
		&i.FeaturesJson,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscriptionByRestaurant = `-- name: GetSubscriptionByRestaurant :one
SELECT
    rs.id,
    rs.restaurant_id,
    rs.plan_id,
    rs.status,
    rs.trial_ends_at,
    rs.current_period_start,
    rs.current_period_end,
    rs.created_at,
    rs.updated_at,
    sp.name        AS plan_name,
    sp.tier        AS plan_tier,
    sp.price_monthly AS plan_price_monthly,
    sp.features_json AS plan_features_json
FROM restaurant_subscriptions rs
JOIN subscription_plans sp ON sp.id = rs.plan_id
WHERE rs.restaurant_id = $1
`

type GetSubscriptionByRestaurantRow struct {
	ID                 int64              `json:"id"`
	RestaurantID       int64              `json:"restaurant_id"`
	PlanID             int64              `json:"plan_id"`
	Status             string             `json:"status"`
	TrialEndsAt        pgtype.Timestamptz `json:"trial_ends_at"`
	CurrentPeriodStart time.Time          `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	PlanName           string             `json:"plan_name"`
	PlanTier           PlanTier           `json:"plan_tier"`
	PlanPriceMonthly   pgtype.Numeric     `json:"plan_price_monthly"`
	PlanFeaturesJson   json.RawMessage    `json:"plan_features_json"`
}

func (q *Queries) GetSubscriptionByRestaurant(ctx context.Context, restaurantID int64) (GetSubscriptionByRestaurantRow, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByRestaurant, restaurantID)
	var i GetSubscriptionByRestaurantRow
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.PlanID,
		&i.Status,
		&i.TrialEndsAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlanName,
		&i.PlanTier,
		&i.PlanPriceMonthly,
		&i.PlanFeaturesJson,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT id, name, tier, price_monthly, features_json, created_at FROM subscription_plans ORDER BY price_monthly ASC
`

func (q *Queries) ListPlans(ctx context.Context) ([]SubscriptionPlan, error) {
	rows, err := q.db.Query(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionPlan{}
	for rows.Next() {
		var i SubscriptionPlan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tier,
			&i.PriceMonthly,
			&i.FeaturesJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSubscription = `-- name: UpsertSubscription :one
INSERT INTO restaurant_subscriptions (
    restaurant_id, plan_id, status, trial_ends_at,
    current_period_start, current_period_end
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (restaurant_id) DO UPDATE SET
    plan_id              = EXCLUDED.plan_id,
    status               = EXCLUDED.status,
    trial_ends_at        = EXCLUDED.trial_ends_at,
    current_period_start = EXCLUDED.current_period_start,
    current_period_end   = EXCLUDED.current_period_end,
    updated_at           = NOW()
RETURNING id, restaurant_id, plan_id, status, trial_ends_at, current_period_start, current_period_end, created_at, updated_at
`

type UpsertSubscriptionParams struct {
	RestaurantID       int64              `json:"restaurant_id"`
	PlanID             int64              `json:"plan_id"`
	Status             string             `json:"status"`
	TrialEndsAt        pgtype.Timestamptz `json:"trial_ends_at"`
	CurrentPeriodStart time.Time          `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (RestaurantSubscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscription,
		arg.RestaurantID,
		arg.PlanID,
		arg.Status,
		arg.TrialEndsAt,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
	)
	var i RestaurantSubscription
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.PlanID,
		&i.Status,
		&i.TrialEndsAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
