// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: theme.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTenantThemeByRestaurant = `-- name: GetTenantThemeByRestaurant :one
SELECT restaurant_id, preset, tokens_json, updated_by_platform_user_id, created_at, updated_at FROM tenant_themes WHERE restaurant_id = $1
`

func (q *Queries) GetTenantThemeByRestaurant(ctx context.Context, restaurantID int64) (TenantTheme, error) {
	row := q.db.QueryRow(ctx, getTenantThemeByRestaurant, restaurantID)
	var i TenantTheme
	err := row.Scan(
		&i.RestaurantID,
		&i.Preset,
		&i.TokensJson,
		&i.UpdatedByPlatformUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getThemePreset = `-- name: GetThemePreset :one
SELECT key, name, description, created_at FROM theme_presets WHERE key = $1
`

func (q *Queries) GetThemePreset(ctx context.Context, key string) (ThemePreset, error) {
	row := q.db.QueryRow(ctx, getThemePreset, key)
	var i ThemePreset
	err := row.Scan(
		&i.Key,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listThemePresets = `-- name: ListThemePresets :many
SELECT key, name, description, created_at FROM theme_presets ORDER BY key
`

func (q *Queries) ListThemePresets(ctx context.Context) ([]ThemePreset, error) {
	rows, err := q.db.Query(ctx, listThemePresets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThemePreset{}
	for rows.Next() {
		var i ThemePreset
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTenantTheme = `-- name: UpsertTenantTheme :one
INSERT INTO tenant_themes (restaurant_id, preset, tokens_json, updated_by_platform_user_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (restaurant_id)
DO UPDATE SET preset = EXCLUDED.preset, tokens_json = EXCLUDED.tokens_json,
              updated_by_platform_user_id = EXCLUDED.updated_by_platform_user_id, updated_at = NOW()
RETURNING restaurant_id, preset, tokens_json, updated_by_platform_user_id, created_at, updated_at
`

type UpsertTenantThemeParams struct {
	RestaurantID            int64           `json:"restaurant_id"`
	Preset                  string          `json:"preset"`
	TokensJson              json.RawMessage `json:"tokens_json"`
	UpdatedByPlatformUserID pgtype.Int8     `json:"updated_by_platform_user_id"`
}

func (q *Queries) UpsertTenantTheme(ctx context.Context, arg UpsertTenantThemeParams) (TenantTheme, error) {
	row := q.db.QueryRow(ctx, upsertTenantTheme,
		arg.RestaurantID,
		arg.Preset,
		arg.TokensJson,
		arg.UpdatedByPlatformUserID,
	)
	var i TenantTheme
	err := row.Scan(
		&i.RestaurantID,
		&i.Preset,
		&i.TokensJson,
		&i.UpdatedByPlatformUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
