// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const abandonStaleSession = `-- name: AbandonStaleSession :exec
UPDATE sessions
SET status = 'abandoned', closed_at = NOW()
WHERE id = $1 AND status IN ('active', 'awaiting_reactivation')
`

// Accepts both active and awaiting_reactivation states; the latter is the
// terminal stage of the awaiting_reactivation pipeline.
func (q *Queries) AbandonStaleSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, abandonStaleSession, id)
	return err
}

const listExpiredSessions = `-- name: ListExpiredSessions :many

SELECT s.id, s.branch_id, s.table_id
FROM sessions s
JOIN branches b ON b.id = s.branch_id
WHERE s.status = 'active'
  AND s.created_at < NOW() - (b.session_timeout_minutes || ' minutes')::interval
ORDER BY s.created_at ASC
`

type ListExpiredSessionsRow struct {
	ID       uuid.UUID `json:"id"`
	BranchID int64     `json:"branch_id"`
	TableID  int64     `json:"table_id"`
}

// Queries used by background worker routines.
// Finds sessions that have exceeded their branch-configured timeout.
func (q *Queries) ListExpiredSessions(ctx context.Context) ([]ListExpiredSessionsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiredSessionsRow{}
	for rows.Next() {
		var i ListExpiredSessionsRow
		if err := rows.Scan(&i.ID, &i.BranchID, &i.TableID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
