// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menu.sql

package sqlc

import (
	"context"
)

const getMenuItemByID = `-- name: GetMenuItemByID :one
SELECT id, category_id, branch_id, name, description, price, is_available, position FROM menu_items WHERE id = $1
`

func (q *Queries) GetMenuItemByID(ctx context.Context, id int64) (MenuItem, error) {
	row := q.db.QueryRow(ctx, getMenuItemByID, id)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.BranchID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.IsAvailable,
		&i.Position,
	)
	return i, err
}

const getTableByID = `-- name: GetTableByID :one
SELECT id, branch_id, identifier, capacity, qr_code_token, status, created_at FROM tables WHERE id = $1
`

func (q *Queries) GetTableByID(ctx context.Context, id int64) (Table, error) {
	row := q.db.QueryRow(ctx, getTableByID, id)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Identifier,
		&i.Capacity,
		&i.QrCodeToken,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTableByQRToken = `-- name: GetTableByQRToken :one
SELECT id, branch_id, identifier, capacity, qr_code_token, status, created_at FROM tables WHERE qr_code_token = $1
`

func (q *Queries) GetTableByQRToken(ctx context.Context, qrCodeToken string) (Table, error) {
	row := q.db.QueryRow(ctx, getTableByQRToken, qrCodeToken)
	var i Table
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Identifier,
		&i.Capacity,
		&i.QrCodeToken,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listMenuCategoriesForBranch = `-- name: ListMenuCategoriesForBranch :many
SELECT id, branch_id, name, position, is_active FROM menu_categories
WHERE branch_id = $1 AND is_active = TRUE
ORDER BY position ASC
`

func (q *Queries) ListMenuCategoriesForBranch(ctx context.Context, branchID int64) ([]MenuCategory, error) {
	rows, err := q.db.Query(ctx, listMenuCategoriesForBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuCategory{}
	for rows.Next() {
		var i MenuCategory
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Name,
			&i.Position,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItemsForCategory = `-- name: ListMenuItemsForCategory :many
SELECT id, category_id, branch_id, name, description, price, is_available, position FROM menu_items
WHERE category_id = $1 AND is_available = TRUE
ORDER BY position ASC
`

func (q *Queries) ListMenuItemsForCategory(ctx context.Context, categoryID int64) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listMenuItemsForCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuItem{}
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.BranchID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.IsAvailable,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModifiersForItem = `-- name: ListModifiersForItem :many
SELECT id, item_id, name, price_delta, is_required FROM item_modifiers WHERE item_id = $1 ORDER BY id ASC
`

func (q *Queries) ListModifiersForItem(ctx context.Context, itemID int64) ([]ItemModifier, error) {
	rows, err := q.db.Query(ctx, listModifiersForItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemModifier{}
	for rows.Next() {
		var i ItemModifier
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Name,
			&i.PriceDelta,
			&i.IsRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTablesForBranch = `-- name: ListTablesForBranch :many
SELECT id, branch_id, identifier, capacity, qr_code_token, status, created_at FROM tables WHERE branch_id = $1 ORDER BY identifier ASC
`

func (q *Queries) ListTablesForBranch(ctx context.Context, branchID int64) ([]Table, error) {
	rows, err := q.db.Query(ctx, listTablesForBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Table{}
	for rows.Next() {
		var i Table
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Identifier,
			&i.Capacity,
			&i.QrCodeToken,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTableStatus = `-- name: UpdateTableStatus :exec
UPDATE tables SET status = $2 WHERE id = $1
`

type UpdateTableStatusParams struct {
	ID     int64       `json:"id"`
	Status TableStatus `json:"status"`
}

func (q *Queries) UpdateTableStatus(ctx context.Context, arg UpdateTableStatusParams) error {
	_, err := q.db.Exec(ctx, updateTableStatus, arg.ID, arg.Status)
	return err
}
