// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AbandonSession(ctx context.Context, id uuid.UUID) error
	AbandonStaleSession(ctx context.Context, id uuid.UUID) error
	AddCartItem(ctx context.Context, arg AddCartItemParams) (CartItem, error)
	ClearCart(ctx context.Context, cartID int64) error
	CloseSession(ctx context.Context, id uuid.UUID) error
	CreateAssistanceRequest(ctx context.Context, arg CreateAssistanceRequestParams) (AssistanceRequest, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateParticipant(ctx context.Context, arg CreateParticipantParams) (SessionParticipant, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error)
	GetActiveSessionForTable(ctx context.Context, tableID int64) (Session, error)
	GetAssistanceRequestByID(ctx context.Context, id int64) (AssistanceRequest, error)
	GetBranchByID(ctx context.Context, id int64) (Branch, error)
	GetCartByID(ctx context.Context, id int64) (Cart, error)
	GetCartBySessionAndParticipant(ctx context.Context, arg GetCartBySessionAndParticipantParams) (Cart, error)
	GetCartItem(ctx context.Context, id int64) (CartItem, error)
	GetMenuItemByID(ctx context.Context, id int64) (MenuItem, error)
	GetOrCreateCart(ctx context.Context, arg GetOrCreateCartParams) (Cart, error)
	GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error)
	GetOrderByIdempotencyKey(ctx context.Context, idempotencyKey string) (Order, error)
	GetParticipantByID(ctx context.Context, id int64) (SessionParticipant, error)
	GetPaymentByID(ctx context.Context, id int64) (Payment, error)
	GetRestaurantByID(ctx context.Context, id int64) (Restaurant, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (Session, error)
	GetSessionByToken(ctx context.Context, sessionToken string) (Session, error)
	GetStaffByID(ctx context.Context, id int64) (Staff, error)
	GetTableByID(ctx context.Context, id int64) (Table, error)
	GetTableByQRToken(ctx context.Context, qrCodeToken string) (Table, error)
	InsertEventLog(ctx context.Context, arg InsertEventLogParams) error
	InsertMenuCategory(ctx context.Context, arg InsertMenuCategoryParams) (MenuCategory, error)
	InsertMenuItem(ctx context.Context, arg InsertMenuItemParams) (MenuItem, error)
	InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (PaymentWebhookEvent, error)
	ListActiveAssistanceForBranch(ctx context.Context, branchID int64) ([]AssistanceRequest, error)
	ListActiveOrdersForBranch(ctx context.Context, branchID int64) ([]ListActiveOrdersForBranchRow, error)
	ListActiveSessionsForBranch(ctx context.Context, branchID int64) ([]Session, error)
	ListAssistanceForSession(ctx context.Context, sessionID uuid.UUID) ([]AssistanceRequest, error)
	ListCartItems(ctx context.Context, cartID int64) ([]ListCartItemsRow, error)
	ListMenuCategoriesForBranch(ctx context.Context, branchID int64) ([]MenuCategory, error)
	ListMenuItemsForCategory(ctx context.Context, categoryID int64) ([]MenuItem, error)
	ListModifiersForItem(ctx context.Context, itemID int64) ([]ItemModifier, error)
	ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	ListOrdersForSession(ctx context.Context, sessionID uuid.UUID) ([]Order, error)
	ListParticipantsBySession(ctx context.Context, sessionID uuid.UUID) ([]SessionParticipant, error)
	ListPaymentsForSession(ctx context.Context, sessionID uuid.UUID) ([]Payment, error)
	ListStaffForBranch(ctx context.Context, branchID int64) ([]Staff, error)
	// Queries used by background worker routines.
	// Finds sessions active for more than the given interval (passed as an interval string, e.g. '2 hours').
	ListStaleSessions(ctx context.Context, dollar_1 pgtype.Interval) ([]ListStaleSessionsRow, error)
	ListTablesForBranch(ctx context.Context, branchID int64) ([]Table, error)
	ListUnprocessedWebhooks(ctx context.Context) ([]PaymentWebhookEvent, error)
	MarkWebhookProcessed(ctx context.Context, arg MarkWebhookProcessedParams) error
	RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error
	SetSessionHost(ctx context.Context, arg SetSessionHostParams) error
	UpdateAssistanceStatus(ctx context.Context, arg UpdateAssistanceStatusParams) (AssistanceRequest, error)
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error)
	UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (MenuItem, error)
	UpdateMenuItemAvailability(ctx context.Context, arg UpdateMenuItemAvailabilityParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateParticipantLastSeen(ctx context.Context, id int64) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdateTableStatus(ctx context.Context, arg UpdateTableStatusParams) error
}

var _ Querier = (*Queries)(nil)
