// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: staff.sql

package sqlc

import (
	"context"
)

const createStaff = `-- name: CreateStaff :one
INSERT INTO staff (branch_id, name, role, pin_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, branch_id, name, role, pin_hash, created_at
`

type CreateStaffParams struct {
	BranchID int64     `json:"branch_id"`
	Name     string    `json:"name"`
	Role     StaffRole `json:"role"`
	PinHash  string    `json:"pin_hash"`
}

func (q *Queries) CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, createStaff,
		arg.BranchID,
		arg.Name,
		arg.Role,
		arg.PinHash,
	)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.Role,
		&i.PinHash,
		&i.CreatedAt,
	)
	return i, err
}

const getBranchByID = `-- name: GetBranchByID :one
SELECT id, restaurant_id, name, address, timezone, created_at FROM branches WHERE id = $1
`

func (q *Queries) GetBranchByID(ctx context.Context, id int64) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranchByID, id)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.RestaurantID,
		&i.Name,
		&i.Address,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const getRestaurantByID = `-- name: GetRestaurantByID :one
SELECT id, name, slug, settings_json, created_at FROM restaurants WHERE id = $1
`

func (q *Queries) GetRestaurantByID(ctx context.Context, id int64) (Restaurant, error) {
	row := q.db.QueryRow(ctx, getRestaurantByID, id)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SettingsJson,
		&i.CreatedAt,
	)
	return i, err
}

const getStaffByID = `-- name: GetStaffByID :one
SELECT id, branch_id, name, role, pin_hash, created_at FROM staff WHERE id = $1
`

func (q *Queries) GetStaffByID(ctx context.Context, id int64) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaffByID, id)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.Name,
		&i.Role,
		&i.PinHash,
		&i.CreatedAt,
	)
	return i, err
}

const listStaffForBranch = `-- name: ListStaffForBranch :many
SELECT id, branch_id, name, role, pin_hash, created_at FROM staff WHERE branch_id = $1 ORDER BY name ASC
`

func (q *Queries) ListStaffForBranch(ctx context.Context, branchID int64) ([]Staff, error) {
	rows, err := q.db.Query(ctx, listStaffForBranch, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Staff{}
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.Name,
			&i.Role,
			&i.PinHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
